SynoCommunity/spksrc

cross/znc/PLIST
cross/znc/modules/palaver.cpp
cross/znc/modules/privmsg.cpp
spk/znc/Makefile

Added [privmsg](https://github.com/kylef/znc-contrib/blob/master/privmsg.cpp) and [palaver](https://github.com/cocodelabs/znc-palaver/blob/master/palaver.cpp). This will close bug #1284.

Add 'privmsg' and 'palaver' modules

---

kernel/syno-x86-5.1/Makefile

#1499: Fix for x86-5.1 NAS GPL source

---

spk/redis/src/dsm-control.sh

The log file now gets displayed in DSM

Added missing LOG_FILE var

---

cross/syncthing/Makefile
spk/syncthing/Makefile

as requested here: https://github.com/SynoCommunity/spksrc/issues/1011

update syncthing to 0.10.30

---

mk/spksrc.common.mk

like discussed here: https://github.com/SynoCommunity/spksrc/issues/1623

add vars for available arches

---

spk/couchpotatoserver-custom/src/installer.sh
spk/couchpotatoserver/src/installer.sh
spk/deluge/src/installer.sh
spk/flexget/src/installer.sh
spk/headphones-custom/src/installer.sh
spk/headphones/src/installer.sh
spk/lazylibrarian/src/installer.sh
spk/nzbget-testing/src/installer.sh
spk/nzbget/src/installer.sh
spk/rutorrent/src/installer.sh
spk/sabnzbd/src/installer.sh
spk/sickbeard-custom/src/installer.sh
spk/sickbeard/src/installer.sh
spk/sonarr/src/installer.sh
spk/transmission/src/installer.sh

as discussed here: https://github.com/SynoCommunity/spksrc/pull/1618
affected packages:
`sc-media`:
couchpotatoserver
couchpotatoserver-custom
flexget
headphones
headphones-custom
lazylibrarian
sickbeard
sickbeard-custom
sonarr
`sc-download`:
deluge
nzbget
nzbget-testing
transmission
sabnzb
rutorrent
@Dr-Bean @Diaoul any thoughts?
EDIT: Sickrage changes will come in SickRage PR :)

added dsm groups for various packages

---

cross/syncthing/Makefile
cross/syncthing/PLIST
native/go/Makefile
spk/syncthing/Makefile

this should fix https://github.com/SynoCommunity/spksrc/issues/1628

fix syncthing arm compile issues

---

cross/bitlbee/Makefile
cross/bitlbee/digests
spk/bitlbee/Makefile

Update bitlbee to 3.4.1

---

Dockerfile

Add missing packages used to compil some projects (bitlbee for example)

Add cmake and lzip to Dockerfile

---

cross/boost/Makefile
cross/boost/PLIST
cross/boost/digests
cross/deluge/Makefile
cross/libiconv/Makefile
cross/libiconv/PLIST
cross/libiconv/digests
cross/libiconv/patches/gets.patch
cross/libtorrent/Makefile
cross/libtorrent/PLIST
cross/libtorrent/digests
spk/deluge/Makefile
spk/deluge/src/app/config
spk/deluge/src/app/deluge.cgi.py
spk/deluge/src/core.conf
spk/deluge/src/deluge.sc
spk/deluge/src/dsm-control.sh
spk/deluge/src/installer.sh
spk/deluge/src/wizard/install_uifile
spk/deluge/src/wizard/install_uifile_enu

See https://github.com/SynoCommunity/spksrc/issues/540

Fix and update Deluge and dependencies

---

Makefile
mk/spksrc.spk.mk

See https://github.com/SynoCommunity/spksrc/issues/2007

Move repository-specific variables to local.mk

---

kernel/syno-armada38x-5.2/Makefile
kernel/syno-armada38x-5.2/digests
mk/spksrc.common.mk
toolchains/syno-armada38x-5.2/Makefile
toolchains/syno-armada38x-5.2/digests

see: https://github.com/SynoCommunity/spksrc/issues/2118

add toolchains for armada38x

---

cross/sabnzbd/Makefile
cross/sabnzbd/digests
spk/sabnzbd/Makefile
spk/sabnzbd/src/wizard/upgrade_uifile

Updated SABnzbd to 1.0.0
Updated digests for SABnzbd 1.0.0
Created upgrade warning
Changed provider to Github

SABnzbd update to 1.0.0

---

native/go-1.4/Makefile
native/go/Makefile

update go to 1.6.2

---

cross/sabnzbd/Makefile
cross/sabnzbd/digests
spk/sabnzbd/Makefile

Upgraded SABnzbd to 1.0.3 as per @Dr-Bean's request, I have made this its own pull request with a single commit
Fixes https://github.com/SynoCommunity/spksrc/issues/2191

Updated SABnzbd to 1.0.3

---

cross/sabnzbd/Makefile
cross/sabnzbd/digests
spk/sabnzbd/Makefile

_Motivation:_ Explain here what the reason for the pull request is.
_Linked issues:_ Optionally, add links to existing issues or other PR's

Updated SABnzbd to 1.1.0

---

cross/deluge/Makefile
cross/deluge/digests
spk/deluge/Makefile

_Motivation:_ Explain here what the reason for the pull request is.
_Linked issues:_ Optionally, add links to existing issues or other PR's

Updated Deluge to 1.3.13. Also updated to use .tar.gz

---

cross/sabnzbd-testing/Makefile
cross/sabnzbd-testing/digests
spk/sabnzbd-testing/Makefile

Updated SABnzbd to 1.1.0 RC4

---

cross/libpng/Makefile

Updated the download location as the FTP server seemed offline and using the SourceForge mirrors is more reliable

Updated download location

---

spk/plexivity/Makefile

_Motivation:_ Explain here what the reason for the pull request is.
_Linked issues:_ Optionally, add links to existing issues or other PR's

Plexivity update

---

cross/sabnzbd-testing/Makefile
cross/sabnzbd-testing/digests
spk/sabnzbd-testing/Makefile

Updated to the latest release candidate
Note: There are still issues with DSM 6.x

Updated SABnzbd to 1.1.1 RC2

---

spk/ddrescue/Makefile

Updated to correct the version information as per current standards

Updated the SPK_VERS and SPK_REV correctly for ddrescue

---

cross/sabnzbd-testing/Makefile
cross/sabnzbd-testing/digests
spk/sabnzbd-testing/Makefile

_Motivation:_ Updated to latest RC 3
_Linked issues:_ None

Updated to SABnzbd 1.1.1 RC3

---

cross/sabnzbd/Makefile
cross/sabnzbd/digests
spk/sabnzbd/Makefile

Updated to the latest version
As requested here: https://github.com/SynoCommunity/spksrc/issues/2545

Updated SABnzbd to 1.1.1

---

cross/sabnzbd-testing/Makefile
cross/sabnzbd-testing/digests
spk/sabnzbd-testing/Makefile

As there is currently no testing version and the 1.1.1 final is ahead of 1.1.1 RC3, I've updated this to final

Updated SABnzbd-Testing to 1.1.1 Final

---

cross/sabnzbd-testing/Makefile
cross/sabnzbd-testing/digests
spk/sabnzbd-testing/Makefile

_Motivation:_ Update SABnzbd testing to the new beta.
I don't have a Synology NAS myself so can't test 100% sure if it works, but the update seems pretty straightforward.

Update SABnzbd-testing to 1.2.0Beta1

---

cross/sabnzbd-testing/Makefile
cross/sabnzbd-testing/digests
spk/sabnzbd-testing/Makefile

_Motivation:_ Update SABnzbd-testing to 1.2.1Beta1

Update SABnzbd-testing to 1.2.1Beta1

---

spk/radarr/Makefile
spk/radarr/src/app/config
spk/radarr/src/config.xml
spk/radarr/src/radarr.sc

_Motivation:_ Updated to update the ports on Radarr to 8310 and 8311
_Linked issues:_ Should fix https://github.com/SynoCommunity/spksrc/issues/2652

Fixing invalid port in Radarr package

---

spk/sabnzbd-testing/Makefile

_Motivation:_ Updated build number to fix invalid published version

Updated SABnzbd version number

---

spk/sabnzbd-testing/Makefile

Updated version number of SABnzbd to enable multi-threaded par2
_Motivation:_ Enables par2cmdline-mt that has now been tested

Incrementing version of SABnzbd

---

cross/sabnzbd-testing/Makefile
cross/sabnzbd-testing/digests
spk/sabnzbd-testing/Makefile

Update SABnzbd testing to 2.0.0Beta1

---

cross/tessdata-eng/Makefile
cross/tessdata-eng/digests

Fix URL for package tessdata-eng and udpate to 3.04

---

cross/sabnzbd/Makefile
cross/sabnzbd/digests
spk/sabnzbd/Makefile

(SABnzbd 1.2.2 was a Windows-only fix)

Update SABnzbd to 1.2.3

---

cross/sabnzbd-testing/Makefile
cross/sabnzbd-testing/digests
spk/sabnzbd-testing/Makefile

Update SABnzbd-testing to 2.0.0RC1

---

cross/sabnzbd-testing/digests

Fixed filenames in digests file

Updated digests to point to correct filenames

---

cross/sabnzbd-testing/Makefile
cross/sabnzbd-testing/digests
cross/sabnzbd/Makefile
cross/sabnzbd/digests
spk/sabnzbd-testing/Makefile
spk/sabnzbd-testing/src/requirements.txt
spk/sabnzbd/Makefile
spk/sabnzbd/src/dsm-control.sh
spk/sabnzbd/src/installer.sh
spk/sabnzbd/src/requirements.txt

Updated both to the Final.
Integrated all changes from `testing` required to run the pip install.
Hope you have time to test this @KaraokeStu, just to be sure I did it 100% correctly for both packages :)

Update SABnzbd (+Testing) to 2.0.0 Final

---

cross/jackett/Makefile
cross/jackett/digests
spk/jackett/Makefile

_Motivation:_ Update to latest version of Jackett

updated jackett to v0.7.1225

---

cross/sabnzbd/Makefile
spk/sabnzbd/Makefile

_Motivation:_ Fixing the broken cross version
_Linked issues:_ Fixes https://github.com/SynoCommunity/spksrc/issues/2740 and https://github.com/SynoCommunity/spksrc/issues/2739

Updated SABnzbd to have the correct cross version

---

cross/radarr/Makefile
cross/radarr/digests
spk/radarr/Makefile
spk/radarr/src/app/config
spk/radarr/src/conf/privilege
spk/radarr/src/config.xml
spk/radarr/src/dsm-control.sh
spk/radarr/src/installer.sh
spk/radarr/src/radarr.sc
spk/radarr/src/wizard/install_uifile
spk/radarr/src/wizard/install_uifile_enu
spk/radarr/src/wizard/upgrade_uifile
spk/radarr/src/wizard/upgrade_uifile_enu

_Motivation:_ Add DSM6 Compatibility
_Linked issues:_ https://github.com/SynoCommunity/spksrc/issues/2207 + others

Radarr DSM6 Compatibility: var->.config + version checking fix

---

cross/par2cmdline/Makefile

The Makefile for par2cmdline was broken, this repairs it!

Fixed broken tabs in Makefile

---

spk/sabnzbd-testing/Makefile

Ensure the amended par2cmdline has been included

Updated sabnzbd-testing revision

---

cross/tt-rss/Makefile
spk/tt-rss/Makefile
spk/tt-rss/src/installer.sh

_Motivation:_ Upgrade tt-rss to version 17.4.
_Solves issues_: #2278

tt-rss upgrade to 17.4

---

cross/sabnzbd-testing/Makefile
cross/sabnzbd-testing/digests
spk/sabnzbd-testing/Makefile

sabnzbd-testing to 2.2.0Alpha2

---

cross/sabnzbd-testing/Makefile
cross/sabnzbd-testing/digests
spk/sabnzbd-testing/Makefile

Some bugs that required a fix, so already the next release.

SABnzbd 2.2.0 Beta 1

---

spk/sickrage/src/requirements.txt

_Motivation:_ Explain here what the reason for the pull request is.
_Linked issues:_ Optionally, add links to existing issues or other PR's

Removed lxml from requirements for package sickrage

---

spk/wallabag/src/installer.sh

using head -c instead of fold -w  (fold is not present on my 5.2 DSM)
see issu : https://github.com/SynoCommunity/spksrc/issues/2845

[wallabag] in installer.sh remove fold utility dependency

---

spk/sickrage/Makefile

Updated revision number, which was missed in the previous PR

Updated revision number for sickrage

---

spk/wallabag/Makefile

Updated wallabag revision number which was missed in the previous PR

Updated wallabag revision number

---

cross/sabnzbd-testing/Makefile
cross/sabnzbd-testing/digests
spk/sabnzbd-testing/Makefile

SABnzbd 2.2.0RC1

---

cross/sabnzbd-testing/Makefile
cross/sabnzbd-testing/digests
cross/sabnzbd/Makefile
cross/sabnzbd/digests
spk/sabnzbd-testing/Makefile
spk/sabnzbd/Makefile

Update all SABnzbd versions to 2.2.0 Final.

Update to 2.2.0 Final

---

spk/git/src/installer.sh

_Motivation:_ `git` was not in the path.

Put git in the PATH

---

cross/sabnzbd-testing/Makefile
cross/sabnzbd-testing/digests
cross/sabnzbd/Makefile
cross/sabnzbd/digests
spk/sabnzbd-testing/Makefile
spk/sabnzbd/Makefile

Update SABnzbd to 2.2.1

---

cross/unrar/patches/001-remove-defaul-env-flags.patch

Fix for unrar patch

---

mk/spksrc.spk.mk

Generates "install_conflict_packages" in INFO file
Closes #2893

Fix SPK_CONFLICT support

---

spk/radarr/src/wizard/install_uifile
spk/radarr/src/wizard/install_uifile_fre
spk/radarr/src/wizard/upgrade_uifile
spk/radarr/src/wizard/upgrade_uifile_fre
spk/sonarr/src/wizard/install_uifile
spk/sonarr/src/wizard/install_uifile_fre
spk/sonarr/src/wizard/upgrade_uifile
spk/sonarr/src/wizard/upgrade_uifile_fre

Wizard french translations for Sonarr and Radarr

---

Makefile
mk/spksrc.common.mk
mk/spksrc.service.installer
mk/spksrc.service.mk
mk/spksrc.spk.mk

Patches to:
- Shortcut was not generated and add advanceGrantPrivilege 
- User was not removed when package was uninstalled 
- Set default toolchain version to 6.1
- Show link to homepage of package in Package Center

Framework and architecture patches

---

spk/nzbget/src/service-setup.sh
spk/nzbget/src/wizard/install_uifile
spk/nzbget/src/wizard/install_uifile_fre
spk/nzbget/src/wizard/upgrade_uifile
spk/nzbget/src/wizard/upgrade_uifile_fre

Wizard french translations and permissions handling for NZBGet

---

mk/spksrc.service.mk
mk/spksrc.service.start-stop-daemon
mk/spksrc.service.start-stop-status
mk/spksrc.spk.mk
spk/demoservice/Makefile
spk/demoservice/src/service-setup.sh
spk/jackett/Makefile
spk/mosquitto/Makefile
spk/radarr/Makefile
spk/radarr/src/service-setup.sh
spk/sonarr/Makefile
spk/sonarr/src/service-setup.sh

Adapt Radarr and Sonarr to use background support
Fix package conf/ support for mosquitto

Service Support: add background command execution

---

spk/nzbget/src/wizard/install_uifile
spk/nzbget/src/wizard/install_uifile_fre
spk/nzbget/src/wizard/upgrade_uifile
spk/nzbget/src/wizard/upgrade_uifile_fre

nzbget: wizard link to Permission Management doc

---

mk/spksrc.service.start-stop-status

Here is why script not longer works

Fix start-stop-status default status wait timeout

---

mk/spksrc.service.mk

Enable busybox start-stop-daemon generic support

WIP Service: enable start-stop-daemon support

---

cross/nano/Makefile
cross/nano/digests
spk/nano/Makefile

_Motivation:_ I needed to start somewhere to learn the how build process works...

update nano to 2.9.5

---

mk/spksrc.spk.mk
spk/sabnzbd/Makefile
spk/sabnzbd/src/wizard/upgrade_uifile_fre
spk/transmission/Makefile
spk/transmission/src/wizard/install_uifile_fre
spk/transmission/src/wizard/upgrade_uifile_fre
spk/tvheadend/src/wizard/install_uifile
spk/tvheadend/src/wizard/install_uifile_fre
spk/tvheadend/src/wizard/upgrade_uifile
spk/tvheadend/src/wizard/upgrade_uifile_fre

Fix wizard packaging and various package wizards

---

cross/transmission/Makefile
cross/transmission/digests
spk/transmission/Makefile
spk/transmission/src/wizard/install_uifile
spk/transmission/src/wizard/install_uifile_fre
spk/transmission/src/wizard/upgrade_uifile
spk/transmission/src/wizard/upgrade_uifile_fre

_Motivation:_ update transmission, add link to Permissions Management FAQ
_Linked issues:_ #3303

transmission: update to 2.94

---

mk/spksrc.service.mk
spk/couchpotatoserver-custom/src/wizard/upgrade_uifile
spk/couchpotatoserver-custom/src/wizard/upgrade_uifile_fre
spk/couchpotatoserver/src/wizard/install_uifile
spk/couchpotatoserver/src/wizard/install_uifile_fre
spk/couchpotatoserver/src/wizard/upgrade_uifile
spk/couchpotatoserver/src/wizard/upgrade_uifile_fre
spk/deluge/src/wizard/install_uifile
spk/deluge/src/wizard/install_uifile_fre
spk/deluge/src/wizard/upgrade_uifile
spk/deluge/src/wizard/upgrade_uifile_fre
spk/headphones-custom/Makefile
spk/headphones-custom/src/wizard/install_uifile
spk/headphones-custom/src/wizard/install_uifile_fre
spk/headphones-custom/src/wizard/upgrade_uifile
spk/headphones-custom/src/wizard/upgrade_uifile_fre
spk/headphones/Makefile
spk/headphones/src/wizard/install_uifile
spk/headphones/src/wizard/install_uifile_fre
spk/headphones/src/wizard/upgrade_uifile
spk/headphones/src/wizard/upgrade_uifile_fre
spk/lazylibrarian/Makefile
spk/lazylibrarian/src/wizard/install_uifile
spk/lazylibrarian/src/wizard/install_uifile_fre
spk/lazylibrarian/src/wizard/upgrade_uifile
spk/lazylibrarian/src/wizard/upgrade_uifile_fre
spk/mylar/src/wizard/install_uifile
spk/mylar/src/wizard/install_uifile_fre
spk/mylar/src/wizard/upgrade_uifile
spk/mylar/src/wizard/upgrade_uifile_fre

_Motivation:_ add link to Permissions Management FAQ and french translations
_Linked issues:_ 

Translations and permissions documentation link

---

cross/sabnzbd/Makefile
cross/sabnzbd/digests
spk/sabnzbd/Makefile

Update SABnzbd to 2.3.4

---

mk/spksrc.spk.mk

_Motivation:_ I've messed up my merge conflict in an earlier PR. I've only realised after I looked at the diff on github
_Linked issues:_ #3327

Fix duplicate os_min_ver

---

spk/dnscrypt-proxy/src/conf/resource

_Motivation:_
_Linked issues:_ #3357

dnscrypt-proxy: fix conf/resource

---

spk/dante-sockd/Makefile
spk/dante-sockd/src/wizard/install_uifile_fre
spk/ps3netsrv/Makefile
spk/ps3netsrv/src/wizard/install_uifile_fre

Set of package translations for publishing

---

spk/mc/Makefile
spk/mc/src/service-setup.sh

_Motivation:_ mc package is missing mcedit, mcdiff, mcview executables in path
_Linked issues:_ #3361

Add missing mc symlinks

---

cross/sabnzbd/Makefile
cross/sabnzbd/digests
spk/sabnzbd/Makefile

_Motivation:_ Update SABnzbd to 2.3.5

Update SABnzbd to 2.3.5

---

spk/beets/Makefile
spk/beets/src/requirements.txt

_Motivation:_ Upgrade `beets` to the latest available version
_Linked issues:_ #2572

[beets] upgrade to version 1.4.7

---

mk/spksrc.common.mk
toolchains/syno-aarch64-6.1/Makefile
toolchains/syno-aarch64-6.1/digests
toolchains/syno-armada37xx-6.2/Makefile
toolchains/syno-armada37xx-6.2/digests

toolchains: aarch64 for both rtd1296 and armada37xx

---

mk/spksrc.common.mk

_Motivation:_ Reduce architecture list from "all-supported" target

framework: mark recently added archs as duplicates

---

cross/libmediainfo/Makefile
cross/libmediainfo/digests
cross/libzen/Makefile
cross/libzen/digests
cross/mediainfo/Makefile
cross/mediainfo/digests
mk/spksrc.service.installer
spk/mediainfo/Makefile
spk/mediainfo/src/service-setup.sh

_Motivation:_  Update mediainfo and move to github releases
_Linked issues:_  #3708

mediainfo: update to 19.04

---

cross/sabnzbd/Makefile
cross/sabnzbd/digests
spk/sabnzbd/Makefile

Update SABnzbd to 2.3.9

---

cross/dnscrypt-proxy/Makefile
cross/dnscrypt-proxy/PLIST
cross/dnscrypt-proxy/digests
spk/dnscrypt-proxy/Makefile
spk/dnscrypt-proxy/src/dnscrypt-proxy.sc
spk/dnscrypt-proxy/src/service-setup.sh
spk/dnscrypt-proxy/src/ui/application.cfg
spk/dnscrypt-proxy/src/ui/cgi.go
spk/dnscrypt-proxy/src/ui/help/enu/index.html
spk/dnscrypt-proxy/src/ui/help/enu/thanks.html
spk/dnscrypt-proxy/src/ui/layout.html
spk/dnscrypt-proxy/src/ui/style.css
spk/dnscrypt-proxy/src/ui/test.sh
spk/dnscrypt-proxy/src/ui/texts/enu/strings
spk/dnscrypt-proxy/src/update-blocklist.sh
spk/dnscrypt-proxy/src/wizard/install_uifile
spk/dnscrypt-proxy/src/wizard/install_uifile_fre

_Motivation:_  see title
_Linked issues:_  closes #3694 and https://github.com/publicarray/spksrc/issues/5

dnscrypt-proxy update and block list cron job

---

README.rst
cross/gnutls/Makefile
cross/nettle/Makefile

_Motivation:_  Fix to get build functional on Debian 10
_Linked issues:_  #3745

Debian10 fix

---

cross/libev/Makefile

_Motivation:_  Impossible to build libev cross package
_Linked issues:_  None seen so far
- ~~[ ] Build rule `all-supported` completed successfully~~
- ~~[ ] Package upgrade completed successfully~~
- ~~[ ] New installation of package completed successfully~~

[libev] Fixed base dist site URL

---

cross/libmediainfo/Makefile
cross/libmediainfo/digests
cross/mediainfo/Makefile
cross/mediainfo/digests
spk/mediainfo/Makefile

mediainfo: update to 19.09

---

cross/tvheadend/patches/ppc/isoc9x.patch

Fix created to compile and publish for ppc/qoriq

tvheadend: fix ppc patch compilation

---

Makefile
spk/flexget/src/wizard/install_uifile
spk/flexget/src/wizard/install_uifile_enu
spk/horde/src/wizard/install_uifile
spk/horde/src/wizard/install_uifile_enu
spk/htpcmanager/src/wizard/install_uifile
spk/htpcmanager/src/wizard/install_uifile_enu
spk/htpcmanager/src/wizard/install_uifile_fre
spk/subliminal/src/wizard/install_uifile
spk/subliminal/src/wizard/install_uifile_enu

_Motivation:_  Fix invalid json

Lint and fix json files

---

cross/chromaprint/Makefile
cross/chromaprint/digests
spk/chromaprint/Makefile

_Motivation:_  Update to ffmpeg 4.2.2

chromaprint: update to 1.5.0 and ffmpeg 4.2.2

---

cross/mediainfo/Makefile
cross/mediainfo/digests
spk/mediainfo/Makefile

mediainfo: update to 20.03

---

.github/workflows/build.yml

fix build status action

---

.github/actions/build.sh
.github/actions/build_status.sh

avoid to annotate unsupported builds as errors.

[github-action] Fix annotations

---

.github/actions/build.sh

[github action]: fix build noarch

---

cross/borgbackup/Makefile
cross/borgbackup/digests
spk/borgbackup/Makefile
spk/borgbackup/src/requirements.txt

_Motivation:_  Package update for Python 3.7
_Linked issues:_  #3334 #3644 #3934 #4102

borgbackup: update to 1.1.13 and borgmatic 1.5.9

---

spk/gateone/Makefile
spk/git/Makefile
spk/htpcmanager/Makefile
spk/icecast/Makefile
spk/maraschino/Makefile
spk/mercurial/Makefile
spk/nzbget/Makefile
spk/plexivity/Makefile
spk/sickbeard-custom/Makefile

Required to publish non-updated packages for geminilake

Increase package revision for publish into repository

---

spk/homeassistant/Makefile
spk/homeassistant/src/60-synocommunity.homeassistant.rules
spk/homeassistant/src/requirements.txt
spk/homeassistant/src/wizard/install_uifile
spk/homeassistant/src/wizard/install_uifile_fre
spk/homeassistant/src/wizard/upgrade_uifile
spk/homeassistant/src/wizard/upgrade_uifile_fre

_Motivation:_  Built for python 3.7.7
_Linked issues:_  #3944

homeassistant: update to 0.114.2

---

cross/sabnzbd/Makefile
cross/sabnzbd/digests
spk/sabnzbd/Makefile

Update SABnzbd to 3.0.2

---

spk/chromaprint/Makefile
spk/comskip/Makefile

_Motivation:_  Bump package version and edit changelog to mention update to `ffmpeg` 4.3.1
_Linked issues:_  #4211

chromaprint & comskip: Bump version & comment ffmpeg update 4.3.1

---

mk/spksrc.spk.mk

_Motivation:_  `$(PUBLISH)` variable is not being honored in last recipe call thus needs a different approach to properly handle publishing flag.

framework: fix make publish-all-* in spk.mk

---

spk/chromaprint/Makefile
spk/comskip/Makefile

_Motivation:_  Ffmpeg version bump for comskip and chromaprint for new package release

Ffmpeg version bump for comskip and chromaprint for new package release

---

spk/mono/Makefile

_Motivation:_  Increment Mono Package revision to push workaround for armv5

increment mono revision for armv5 workaround

---

Dockerfile

_Motivation:_  Add meson to default image in preparation for mk meson+ninja
_Linked issues:_  #4307

meson: Add meson to pip3 install

---

spk/homeassistant/Makefile
spk/homeassistant/src/requirements.txt
spk/homeassistant/src/service-setup.sh

_Motivation:_  Published version 0.118.5-10 fails to install xiaomi integrations
_Linked issues:_  closes #4339, closes #4324

[homeassistant] fix integrations

---

mk/spksrc.cross-meson-env.mk

followup of #4320
- fix arch specific configurations https://github.com/SynoCommunity/spksrc/pull/3836#issuecomment-752954711

fix meson build

---

.gitignore

_Motivation:_ update the gitignore file to singular toolchains
_Linked issues:_  #4320

Update .gitignore for singular toolchains

---

spk/plexpy-custom/Makefile

_Motivation:_  need to increment SPK_REV for publish
_Linked issues:_  follow-up of #4384

plexpy-custom: update SPK_REV

---

spk/adminer/Makefile

- incorporate changes to reflect the latest published release
- set current spk dependencies
- remove obsolete backslashes from description

Adminer: adjust dependencies

---

spk/hassio/src/service-setup.sh

_Motivation:_  The url being used in the pacakge is changed

Hassio version url has been changed

---

spk/jackett/src/service-setup.sh
spk/lidarr/src/service-setup.sh
spk/radarr/src/service-setup.sh

_Motivation:_  Fix ARMv5 mono packages
_Linked issues:_  add changes from #4266 to the remaining packages. Thanks @ccwillia  https://github.com/SynoCommunity/spksrc/issues/3443#issuecomment-771967783 should fix #4363 too.
I don't have any ARMv5 device so someone else may need to verify this.

Fix mono for 88f6281 and 88f6282

---

cross/python38/Makefile
cross/python38/digests
native/python38/Makefile
native/python38/digests
spk/python38/Makefile

_Motivation:_  Maintaining the 3.8 Python SPK
Corresponding release notes here (security fixes): https://www.python.org/downloads/release/python-388/

python38: 3.8.8 update

---

cross/fish/Makefile
spk/fish/Makefile

_Motivation:_  fish shell builds for qoriq arch too
_Linked issues:_  #4463

fish-shell: enable build for qoriq arch

---

cross/rhash/PLIST
diyspk/rhash/Makefile
spk/synocli-file/Makefile

_Motivation:_  Improve DSM7 support

rhash: SPK_LINKS -> SPK_COMMANDS

---

mk/spksrc.service.mk
mk/spksrc.spk.mk

fixes #4578 for packages without specific conf files

fix resource linker for dsm6

---

mk/spksrc.service.installer.dsm7

_Motivation:_  Avoid dsm6 -> dsm7 upgrade when upgrading dsm7 -> dsm7
_Linked issues:_ #4524

DSM7 fix package upgrade

---

spk/synocli-file/Makefile

_Motivation:_  publish synoclil-file to include fixed of #4478
_Linked issues:_  #4478

fix synocli-file

---

cross/jpegoptim/Makefile
cross/jpegoptim/PLIST
cross/jpegoptim/digests
diyspk/jpegoptim/Makefile

_Motivation:_  A small CLI tool to compress jpeg files.
_Linked issues:_  #4609 
inital commit as `do it yourself` package.

add jpegoptim

---

cross/mtr/Makefile
cross/mtr/PLIST
cross/mtr/digests
diyspk/mtr/Makefile
spk/synocli-net/Makefile

_Motivation:_  add My traceroute CLI tool
_Linked issues:_  closes #4640

add mtr (My traceroute) to synocli-net

---

spk/rabbitmq/Makefile

rabbitmq: add changelog

---

toolkit/syno-evansport-6.2.2/digests
toolkit/syno-evansport-6.2.3/digests
toolkit/syno-evansport-6.2.4/Makefile
toolkit/syno-evansport-6.2.4/digests
toolkit/syno-evansport-6.2/digests

_Motivation:_  Toolkit package was updated for 6.2.4

toolkit/syno-evansport-6.2.*: Fix digests

---

spk/borgbackup/Makefile
spk/borgbackup/src/requirements.txt

_Motivation:_  Minor updates before publishing (incl. packages for DSM7)
_Linked issues:_  closes #4709, #4663, closes #3334, closes #2809

borgbackup: update borgmatic and other dependencies

---

cross/jellyfin/Makefile
cross/jellyfin/digests
spk/jellyfin/Makefile

[updated with ./spkcli update jellyfin]
_Motivation:_  Explain here what the reason for the pull request is.

Jellyfin: update to get the latest security fixes

---

README.rst

_Motivation:_  Clarify the instructions for utilizing the Docker development setup.
_Linked issues:_  This work stems from the discussion in #4723.
(I still don't fully understand this checklist, so, leaving this blank.)

Clarify Docker instructions in the README.rst file.

---

spk/sslh/Makefile

_Motivation:_  Fix the creation of package user for DSM<7
_Linked issues:_  #4740

sslh: fix for DSM<7

---

cross/java-11-openjdk/Makefile

_Motivation:_  Fixes needed after #4803 is merged

java11: update no parallel make flags

---

.github/actions/build.sh

_Motivation:_  I forgot to clear the log file after a build.

CI: don't grab the log on success

---

cross/ps3netsrv/Makefile
mk/spksrc.common.mk

_Motivation:_  Post review from @hgy59 on two trivial commits actually raised two small items needed attention.
_Linked issues:_  This solves issues raised, namely https://github.com/SynoCommunity/spksrc/pull/4860#issuecomment-918810896 and https://github.com/SynoCommunity/spksrc/pull/4857#pullrequestreview-753477990

Parallel build follow-up

---

cross/tmux/patches/001-create-configure-for-cross-compile.patch
cross/xxhash/PLIST

_Motivation:_  Followup of #4956
_Linked issues:_  #4956
- add missing patch for tmux

synocli-net: finalize update

---

mk/spksrc.wheel.mk

fix whitespace in spksrc.wheel.mk

---

spk/synocli-net/Makefile

_Motivation:_  Required for publishing this package
_Linked issues:_  #5000

synocli-net: increment SPK_REV

---

spk/deluge/Makefile
spk/git/Makefile
spk/nzbget/Makefile
spk/python2/Makefile
spk/syncthing/Makefile

_Motivation:_  I haven't touched these packages in years, but people still contact me for updates. This way on the next release of the packages, this information is updated.

Remove Safihre as maintainer from packages he doesn't maintain

---

mk/spksrc.install-resources.mk

_Motivation:_  Needed while working on some .net packages 
_Linked issues:_  #4976, #5015

enable PLIST.auto for install-resources

---

spk/nodejs_v16/Makefile

fix nodejs v16 for all armv7 archs
- include libatomic from toolchain for armv7 archs
Fixes #5065

fix nodejs v16 for armv7 archs

---

mk/spksrc.spk.mk

#5061 dows not work as expected

revert #5061

---

spk/znc/Makefile

Package readiness to be published using Python 3.10 SPK_DEPENDS

znc: Bump version and adjust changelog

---

spk/synocli-file/Makefile

fix description of synocli-file

synocli-file: fix description

---

cross/nnn/patches/comcerto2k/001-avoid-file-offset-64-for-32-bit-archs.patch

synocli-file: fix nnn for comcerto2k-7.0

---

spk/sabnzbd/Makefile
spk/znc/Makefile

Republish packages with fixed dsm 7 installer (identified in #5119)
- installer is fixed with #5117

republish sabnzbd and znc to fix dsm7 installer

---

Dockerfile

Add rsync to base toolset
Fixes #5145

Dockerfile: Add rsync to base toolset

---

cross/adminer/Makefile
cross/adminer/digests
spk/adminer/Makefile
spk/adminer/src/dsm-control.sh
spk/adminer/src/service-setup.sh

Adminer: update to v4.8.1

---

spk/transmission/Makefile
spk/transmission/src/service-setup.sh
spk/transmission/src/wizard/7.0/upgrade_uifile
spk/transmission/src/wizard/upgrade_uifile

rebuild transmission with updated openssl and redeploy dedicated package for comcerto2k with DSM 7
Fixes #5111

transmission: fix for DS414j with DSM7 (#5111)

---

cross/openssl/Makefile
cross/openssl/digests

- fixes CVE-2022-0778
related to: #5161

update cross/openssl to v1.1.1n

---

spk/transmission/Makefile

transmission: fix changelog

---

mk/spksrc.common.mk

Save some extra time and logging.
Any objections @th0ma7 @publicarray ?

Disable pip version check during build

---

mk/spksrc.cross-cc.mk
mk/spksrc.spk.mk

When parallel building do not stop on failures but continue on next arch.
Fixes #5156

spk.mk: Fix all-supported and other parallel-build calls

---

Dockerfile
mk/spksrc.common.mk
mk/spksrc.wheel-env.mk
mk/spksrc.wheel.mk
spk/python310/Makefile
spk/python310/src/requirements-crossenv.txt

Small fixes to wheel building
1. non-critical shell error
2. additional messaging when skipping steps
3. simplify and standardize pure-python wheel copying
4. fix code issue with pure-python
5. fix pure-python build from Docker on github-action

Wheel small fixes

---

spk/flexget/Makefile
spk/flexget/src/requirements-crossenv.txt
spk/flexget/src/requirements-pure.txt
spk/flexget/src/wizard/install_uifile
spk/flexget/src/wizard/upgrade_uifile

Hopefully last step in migrating flexget to python 3.10.
Refers to #5043

flexget: Update to version 3.3.4 using python 3.10

---

spk/gitea/Makefile
spk/gitea/src/service-setup.sh

fix gitea shared folder for DSM 6
- fix gitea folder creation for DSM 6
- use variable for service port
Fixes #

gitea: create shared folder with DSM resource worker for DSM 6

---

cross/zlib/Makefile

Sorry about that, turns out ARMv7 fails to build otherwise.
This one is tested now.

Update zlib call

---

cross/zlib/Makefile

- use provided url for all available versions (an not only current version).
- this download location will not break the builds when a new zlib version is released

update zlib url (follow up of #5183)

---

cross/zlib/PLIST

update version number in PLIST file
Fixes #5183

zlib: update version number

---

cross/kiwix-tools/Makefile
cross/kiwix-tools/digests
cross/libkiwix/Makefile
cross/libkiwix/PLIST
cross/libkiwix/digests
cross/libmicrohttpd/Makefile
cross/libmicrohttpd/PLIST
cross/libmicrohttpd/digests
cross/libxapian/Makefile
cross/libxapian/PLIST
cross/libxapian/digests
cross/libzim/Makefile
cross/libzim/PLIST
cross/libzim/digests
cross/pugixml/Makefile
cross/pugixml/PLIST
cross/pugixml/digests
spk/kiwix/Makefile

- update kiwix-tools and dependencies
- add cross/libxapian

kiwix: udpate to v3.2.0

---

cross/boost/Makefile
cross/boost_1.68/Makefile
cross/boost_1.70/Makefile
cross/mkvtoolnix_22/patches/001-fix-aarch64-version-info.patch
spk/mkvtoolnix_22/Makefile

mkvtoolnix_22: fix aarch64 version info

---

spk/darkstat/Makefile

darkstat: increment spk revision

---

mk/spksrc.service.mk
mk/spksrc.spk.mk

Follow up of #5209 (f4ff352)
Fixes package creation for DSM 5.2 of #5224

Fix package creation for DSM < 6

---

mk/spksrc.spk.mk

spk.mk: Fix publishing of kernel-module packages (1-liner bug-fix)
Follow-up to #5095

spk.mk: Fix publishing of kernel-module packages

---

.github/workflows/docker.yml

updates initiated by dependabot

bump versions of docker workflow actions

---

cross/redis/Makefile
cross/redis/digests
spk/redis/Makefile

redis: security update

---

cross/ruby/Makefile
cross/ruby/PLIST
cross/ruby/digests
native/ruby/Makefile
native/ruby/digests
spk/ruby/Makefile

ruby: update to v3.1.2

---

spk/radarr/src/service-setup.sh
spk/radarr/src/wizard/install_uifile
spk/radarr/src/wizard/install_uifile_fre
spk/radarr/src/wizard/upgrade_uifile
spk/radarr/src/wizard/upgrade_uifile_fre

Fix this, before publishing #5273

Radarr: update service setup and permission info

---

spk/octoprint/Makefile
spk/octoprint/src/requirements-crossenv.txt
spk/octoprint/src/requirements-pure.txt

important security update for OctoPrint
Fixes #

octoprint: update to v1.8.1

---

Dockerfile
README.md

- add patchelf for build of dotnet-runtime package
- update meson for cross/gstreamer, #5298
Fixes  build of #5298

udpate docker image:

---

cross/redis/Makefile
cross/redis/digests
mk/spksrc.service.installer.dsm6
spk/redis/Makefile
spk/redis/src/redis.conf
spk/redis/src/sentinel.conf
spk/redis/src/service-setup.sh
spk/redis/src/wizard/upgrade_uifile.sh

update redis
this update includes a fix for QorIQ archs (include libatomics)
Fixes #

redis: update to v7.0.2

---

cross/bandwhich/Makefile
cross/bandwhich/PLIST
cross/bandwhich/digests
cross/bottom/Makefile
cross/bottom/PLIST
cross/bottom/digests
cross/procs/Makefile
cross/procs/PLIST
cross/procs/digests
diyspk/bandwhich/Makefile
diyspk/bottom/Makefile
diyspk/procs/Makefile
spk/synocli-monitor/Makefile

- add bandwhich v0.20.0
- add bottom v0.6.8
- add procs v0.12.3

synocli-monitor: add some tools written in rust

---

mk/spksrc.generate-digests.mk

fix `make digests`
- follow up to #5336 (removing back-ticks)

framework: fix make digests

---

cross/kiwix-tools/Makefile
cross/kiwix-tools/PLIST
cross/kiwix-tools/digests
cross/libkiwix/Makefile
cross/libkiwix/PLIST
cross/libkiwix/digests
cross/libzim/Makefile
cross/libzim/PLIST
cross/libzim/digests
cross/pugixml/Makefile
spk/kiwix/Makefile

kiwix: update to v3.3.0

---

cross/curl/Makefile
cross/curl/digests
cross/curl/patches/001-fix-easy_lock_h_sched_yield.patch
spk/rutorrent/Makefile

curl: update to v7.84.0

---

cross/lua/Makefile
cross/lua/PLIST
cross/lua/digests
spk/lua/Makefile

lua: update to v5.4.4

---

spk/borgbackup/Makefile
spk/borgbackup/src/requirements-crossenv.txt
spk/borgbackup/src/requirements-pure.txt

Add emborg to the borg package. emborg is a borg frontend similar to borgmatic. Personally, I find its configuration scheme a little easier to work with when making multiple backups with a similar set of base criteria.
https://emborg.readthedocs.io/en/latest/
Also updates borgmatic to v1.6.3
Also updates borg to v1.2.1
Closes #5322, Closes #5340
- [N/A] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

Add emborg 1.32.0

---

cross/acl/patches/ppc853x/001-acl_from_text.c_remove_pragma.patch

- cross/acl: patch source to support ppc853x

borgbackup: fix for OLD_PPC_ARCHS

---

native/go/Makefile
native/go/digests

golang: update go to v1.18.4

---

cross/gitea/Makefile
cross/gitea/digests
spk/gitea/Makefile

Keep gitea up to date - v1.16.9

Update Gitea to v1.16.9

---

mk/spksrc.spk.mk

- add firmware info only for DSM < 6.1 and > 3.0
- ensure DSM < 6.1 and > 3.0 do not contain os_min_ver and os_max_ver info
- enable creation of noarch packages for SRM
- fix OS_MIN_VER to overwrite os_min_ver info (for DSM >= 6.1 and SRM)

framework: adjust info file creation

---

cross/gitea/Makefile
cross/gitea/digests
spk/gitea/Makefile

Keep gitea up to date - v1.17.0

Update Gitea to v1.17.0

---

cross/jellyfin-web/Makefile
cross/jellyfin-web/digests
cross/jellyfin/Makefile
cross/jellyfin/digests
native/dotnet-sdk-6.0/Makefile
native/dotnet-sdk-6.0/digests
spk/jellyfin/Makefile

update jellyfin 10.8.5
update dotnet 6.0.401

Jellyfin 10.8.5

---

mk/spksrc.cross-rust.mk

Fix regular build post PR #5435
Fixes #5463

cross-rust.mk: Fix regular build post PR #5435

---

spk/lidarr/Makefile
spk/lidarr/src/service-setup.sh

- avoid modification of config.xml on package update
- fix for https://github.com/SynoCommunity/spksrc/pull/5511#issuecomment-1344042044

lidarr: fix package update

---

cross/cloudflared/Makefile
cross/cloudflared/digests
spk/cloudflared/Makefile

Update to 2022.11.1
Upstream changelog: https://github.com/cloudflare/cloudflared/blob/master/RELEASE_NOTES

cloudflared: update to 2022.11.1

---

Dockerfile

rustc: Update Dockerfile to include cargo, rustup and PATH env
Fixes ##5508

rustc: Update Dockerfile to include cargo, rustup and PATH env

---

Dockerfile
mk/spksrc.common.mk
mk/spksrc.cross-rust-env.mk
mk/spksrc.tc.mk
mk/spksrc.wheel-env.mk

rustc: New round of fixes to always setup the env correctly
Follow-up to #5508 and #5533

rustc: New round of fixes to always setup the env correctly

---

spk/nodejs_v16/Makefile

node.js: adjust changelog

---

cross/bottom/Makefile
cross/bottom/digests
mk/spksrc.cross-rust-env.mk
mk/spksrc.cross-rust.mk

The objective of this PR is to test rustc targets using an existing package.
Relates to #5284 in particular https://github.com/SynoCommunity/spksrc/pull/5284/files#r1117684182

bottom: Update from version 0.6.8 to 0.8.0

---

cross/cloudflared/Makefile
cross/cloudflared/digests
spk/cloudflared/Makefile

Update to 2023.3.1
- Running a tunnel without ingress rules defined in configuration file nor from the CLI flags will no longer provide a default ingress rule to localhost:8080 and instead will return HTTP response code 503 for all incoming HTTP requests.
- Windows 32 bit machines MSI now defaults to Program Files to install cloudflared. (See CVE-2023-1314). The cloudflared client itself is unaffected. This just changes how the installer works on 32 bit windows machines.
- Legacy tunnels were officially deprecated on December 1, 2022. Starting with this version, cloudflared no longer supports connecting legacy tunnels.
- h2mux tunnel connection protocol is no longer supported. Any tunnels still configured to use this protocol will alert and use http2 tunnel protocol instead. We recommend …

cloudflared: update to 2023.3.1

---

spk/octoprint/Makefile
spk/octoprint/src/config.yaml
spk/octoprint/src/requirements-crossenv.txt
spk/octoprint/src/requirements-pure.txt
spk/octoprint/src/service-setup.sh

Fixes some security issues with dependent python modules.

octoprint: update to v1.8.7

---

cross/transmission/Makefile
cross/transmission/digests
spk/transmission/Makefile

This PR is to update to the bugfix-only release of Transmission v4.0.3.
Fixes #5694

Transmission: Update to 4.0.3

---

cross/misc-util-linux/Makefile
cross/misc-util-linux/PLIST
cross/ncursesw/Makefile
cross/ncursesw/PLIST
spk/synocli-misc/Makefile

synocli-misc: add lsblk from util-linux (#5747)

---

native/go/Makefile
native/go/digests

cloudflared will be fixed by update to v2023.5.1

native/go: update to v1.20.4

---

mk/spksrc.spk.mk

- Bring back the log of the http response that was removed by "publish validation check (#5701)"

Framework: display the response of package publish

---

cross/libassuan/Makefile
cross/nettle/Makefile
cross/nettle/PLIST
cross/nettle/digests

add dedicated PR for nettle to limit affected packages in #5777

nettle: update from v3.8.1 to v3.9.1

---

cross/owncloud/Makefile
cross/owncloud/digests
spk/owncloud/Makefile

1. Update ownCloud to version 10.12.2
Fixes #

ownCloud: Update to version 10.12.2

---

cross/cloudflared/Makefile
spk/cloudflared/Makefile
spk/cloudflared/src/wizard/install_uifile

follow up to #5734
- remove DSM_UI_DIR to avoid creation of unused icon files
- escape () in package description

cloudflared: fix package

---

mk/spksrc.cross-dotnet.mk
mk/spksrc.cross-go.mk
native/go/Makefile
native/go/digests

go: update to v1.20.5

---

spk/synocli-kernel/Makefile

Minor version bump to add support for r1000 arch.
Fixes #

SynoCli Kernel Tools: Add support for r1000 arch

---

spk/deluge/Makefile

deluge: Version bump
Related to #5820

deluge: Version bump

---

native/go/Makefile
native/go/digests

go: update to v1.20.7

---

cross/alsa-lib/Makefile
cross/alsa-lib/digests
cross/alsa-utils/Makefile
cross/alsa-utils/PLIST
cross/alsa-utils/digests
cross/alsa-utils/patches/armv7-1.2/001-avoid-static-string-functions.patch
diyspk/alsa-utils/Makefile

extracted of #3866 to limit dependent packages

alsa: update alsa-lib and alsa-utils to v1.2.9

---

cross/transmission/Makefile
cross/transmission/digests
spk/transmission/Makefile

This PR is to update to the bugfix-only release of Transmission v4.0.4.
Fixes #

Transmission: Update to 4.0.4

---

spk/synocli-disk/Makefile

Minor version bump to add support for r1000 arch.
Fixes #

SynoCli Disk Tools: Add support for r1000 arch

---

.github/actions/build.sh
.github/actions/prepare.sh

This reverts commit 9b1646350ac534ffbaf42d7c3867ab59493c6877.

Revert "Attempt at fixing publishing whith dependent packages (#5874)"

---

mk/spksrc.main-depends.mk

- add targets to install and create plist
(cherry picked from commit 19b2a780bd7059128b257517135bea0c58bb90c0)
follow-up to #5881

fix spksrc.main-depends.mk

---

cross/owncloud/Makefile
cross/owncloud/digests
spk/owncloud/Makefile

1. Update ownCloud to version 10.13.1
Fixes #

ownCloud: Update to v10.13.1

---

cross/go2rtc/Makefile
cross/go2rtc/digests
spk/go2rtc/Makefile

go2rtc: update to version 1.8.2

---

cross/jellyfin-web/Makefile
cross/jellyfin-web/digests
cross/jellyfin/Makefile
cross/jellyfin/digests
native/dotnet-sdk-6.0/Makefile
native/dotnet-sdk-6.0/digests
spk/jellyfin/Makefile

1. Update jellyfin to 10.8.13
2. Update dotnet to 6.0.25
Fixes #

Jellyfin: Update to v10.8.13

---

spk/git/Makefile

fix creation of symlink for git-lfs (#5965)

---

native/cmake/Makefile
native/cmake/digests

native/cmake: Update from version 3.23.4 to latest (3.28.1) allowing to meets >= requirement for building rust toolchain.

native/cmake: Update from version 3.23.4 to latest (3.28.1)

---

mk/spksrc.cross-cc.mk

Reverts SynoCommunity/spksrc#5995

Revert "cross-cc.mk: Msg. to run make setup first when using all-supported"

---

spk/memcached/Makefile
spk/memcached/src/service-setup.sh

memcached: fix uninstall on DSM < 7

---

cross/sabnzbd/Makefile
cross/sabnzbd/digests
cross/sabnzbd/patches/001-disable_new_version_check.patch
spk/sabnzbd/Makefile
spk/sabnzbd/src/requirements-pure.txt

Update SABnzbd to 4.2.2

---

cross/libjodycode/digests

- it is ugly that the source archive of libjodycode changed without changing the content

synocli-file: fix digests of library for jdupes

---

cross/openssl3/Makefile
cross/openssl3/digests

OpenSSL: update to v3.1.5

---

spk/jellyfin/Makefile

modify jellyfin MAINTAINER = SynoCommunity
Fixes #

Update Makefile Modify Jellyfin MAINTAINER

---

.github/actions/build.sh
mk/spksrc.spk.mk

github-action: Change location of clean-up for packages to keep. Implementing @hgy59 suggestion from
https://github.com/SynoCommunity/spksrc/pull/6037#pullrequestreview-1936544336
Fixes #

github-action: Change location of clean-up for packages to keep

---

native/go/Makefile
native/go/digests

Just some security fixes on native/go

go: update to v1.21.8

---

cross/filebrowser/Makefile
cross/filebrowser/digests
spk/filebrowser/Makefile

filebrowser: update to v2.28.0

---

.github/PULL_REQUEST_TEMPLATE.md

Fix minor typo

---

mk/spksrc.cross-rust-env.mk
mk/spksrc.tc-rust.mk
mk/spksrc.tc.mk
spk/python311/Makefile

armv5 rust version frozen for no-atomic support
Fixes #

armv5 rust version frozen for no-atomic support

---

cross/openssl3/Makefile
cross/openssl3/digests

just another library update that triggers the build of a lot of packages...
Fixes #

openssl3: update to v3.1.6

---

.github/actions/build.sh

Noarch publish fix
Fixes https://github.com/SynoCommunity/spksrc/pull/6132#issuecomment-2156911367

Noarch publish fix

---

cross/strace/Makefile
cross/strace/patches/001-add-option-to-disable-kernel_v4l2_have_time32.patch
spk/synocli-devel/Makefile

synocli-devel: fix build of gdb for OLD_PPC_ARCHS

---

cross/gitea/Makefile
cross/gitea/digests
spk/gitea/Makefile

Update Gitea to v1.22.0

---

cross/cloudflared/Makefile
cross/cloudflared/digests
spk/cloudflared/Makefile
spk/cloudflared/src/config.yml
spk/cloudflared/src/service-setup.sh
spk/cloudflared/src/wizard/install_uifile

1. Update to 2024.8.2
2. Switch from passing the token to using a config file
3. Add advanced options to the installation wizard (Resolves #6184)
<details>
<summary>New options screenshot</summary>
</details>
2024.8.2
- 2024-08-05 TUN-8583: change final directory of artifacts
- 2024-08-05 TUN-8585: Avoid creating GH client when dry-run is true
2024.7.3
- 2024-07-31 TUN-8546: Fix final artifacts paths
2024.7.2
- 2024-07-17 TUN-8546: rework MacOS build script
2024.7.1
- 2024-07-16 TUN-8543: use -p flag to create intermediate directories
2024.7.0
- 2024-07-05 TUN-8520: add macos arm64 build
- 2024-07-05 TUN-8523: refactor makefile and cfsetup
- 2024-07-02 TUN-8504: Use pre-installed python version instead of downloading it on Windows builds
- 2024-06-26 TUN-8489: Add default noop logger for …

cloudflared: update to 2024.8.2

---

cross/node-exporter/Makefile
cross/node-exporter/digests
spk/node-exporter/Makefile

Update node-exporter from v1.8.1 to v1.8.2

node-exporter: Update node-exporter to 1.8.2

---

cross/sabnzbd/Makefile
cross/sabnzbd/digests
spk/sabnzbd/Makefile
spk/sabnzbd/src/requirements-crossenv.txt
spk/sabnzbd/src/requirements-pure.txt

Update SABnzbd to 4.3.3
Fixes: #6223

Update SABnzbd to 4.3.3

---

cross/rutorrent/Makefile
cross/rutorrent/digests
spk/rutorrent/Makefile

rutorrent: Update from version 4.3.6 to 4.3.7
Relates to: https://github.com/SynoCommunity/spksrc/pull/6215

rutorrent: Update from version 4.3.6 to 4.3.7

---

cross/jellyfin-web/Makefile
cross/jellyfin-web/digests
cross/jellyfin/Makefile
cross/jellyfin/digests
spk/jellyfin/Makefile

Jellyfin 10.9.11

---

spk/cops/Makefile
spk/cops/src/wizard_templates/upgrade_uifile.sh
spk/cops/src/wizard_templates/upgrade_uifile.yml
spk/cops/src/wizard_templates/upgrade_uifile_fre.yml

This is a follow-on from #6230 and includes minor fixes to the change log and upgrade wizard.
Fixes #

COPS: Revision for v3.2.2

---

cross/openssl3/Makefile
cross/openssl3/digests

- fixes CVE-2024-6119
- fixes CVE-2024-5535

openssl: update to v3.1.7

---

cross/gitea/Makefile
cross/gitea/digests
spk/gitea/Makefile

Update gitea to 1.22.3
Fixes #

update gitea to 1.22.3

---

spk/owncloud/Makefile
spk/owncloud/src/wizard_templates/install_uifile.sh

This follow-up to #6225 addresses an issue with capturing the MySQL 'root' password in the installation wizard.
Fixes #6278

ownCloud: Revision for v10.15.0

---

cross/bicbucstriim/Makefile
cross/bicbucstriim/digests
spk/bicbucstriim/Makefile

This PR includes the update of BicBucStriim to v3.5.2.
Fixes #6289

BicBucStriim: Update to v3.5.2

---

cross/moreutils/Makefile
cross/moreutils/PLIST
spk/synocli-misc/Makefile

synocli-misc: add ts of moreutils

---

cross/cloudflared/Makefile
cross/cloudflared/digests
spk/cloudflared/Makefile

Changelog: https://raw.githubusercontent.com/cloudflare/cloudflared/master/RELEASE_NOTES

Update cloudflared to 2024.10.1

---

cross/libwebsockets/Makefile
cross/libwebsockets/digests
cross/mosquitto/Makefile
cross/mosquitto/PLIST
cross/mosquitto/digests
spk/mosquitto/Makefile

Changelogs since last release:
- https://mosquitto.org/blog/2024/10/version-2-0-20-released/
- https://mosquitto.org/blog/2024/10/version-2-0-19-released/
Fixes #

Update mosquitto to 2.0.20

---

cross/gitea/Makefile
cross/gitea/digests
spk/gitea/Makefile

Gitea: Update to v1.22.4

---

native/go/Makefile
native/go/digests

native/go: update to v1.23.4

---

cross/gitea/Makefile
cross/gitea/digests
spk/gitea/Makefile

Gitea: Update to v1.22.6

---

native/dotnet-sdk-3.1/Makefile
native/dotnet-sdk-6.0/Makefile
native/dotnet-sdk-8.0/Makefile

Related: https://github.com/dotnet/core/issues/9671

Update dotnetcli domain

---

spk/borgbackup/Makefile
spk/borgbackup/src/requirements-crossenv.txt
spk/borgbackup/src/requirements-pure.txt

- fixes #6370
- update package description (add emborg and borgmatic)
Fixes #6370

borg: update borgmatic to v1.9.5

---

cross/lua/Makefile
cross/lua/PLIST
cross/lua/digests
spk/lua/Makefile

lua: update from v5.4.4 to v5.4.7

---

cross/gitea/Makefile
cross/gitea/digests
spk/gitea/Makefile

Gitea: Update to v1.23.1

---

spk/vim/Makefile

vim: fix link to vim9

---

native/nodejs/Makefile
native/nodejs/digests

This PR includes the following changes:
1. Update to Node.js v22.13.1
Fixes #

native/nodejs: update to v22.13.1

---

cross/jellyfin-web/Makefile
cross/jellyfin-web/digests
cross/jellyfin/Makefile
cross/jellyfin/digests
spk/jellyfin/Makefile

1. Update jellyfin to 10.10.4
Fixes #

Jellyfin: Update to v10.10.4

---

native/nodejs/Makefile
native/nodejs/digests

This PR includes the following changes:
1. Update to Node.js v22.14.0
Fixes #

native/nodejs: update to v22.14.0

---

cross/navidrome/Makefile
cross/navidrome/digests
spk/navidrome/Makefile

Security Update, requested in discord.
Fixes #

navidrom: update to v0.54.5

---

cross/gitea/Makefile
cross/gitea/digests
spk/gitea/Makefile

Gitea: Update to v1.23.4

---

cross/owncloud/Makefile
cross/owncloud/digests
spk/owncloud/Makefile

1. Update ownCloud to version 10.15.2
2. Created [wiki](https://github.com/SynoCommunity/spksrc/wiki/FAQ-ownCloud) page for ownCloud
Fixes #

ownCloud: Update to v10.15.2

---

native/go/Makefile
native/go/digests

native/go update to v1.24.1

---

spk/beets/Makefile
spk/beets/src/requirements-crossenv.txt
spk/beets/src/requirements-pure.txt

1. Upgrade beets to 2.2.0.
2. Update all wheels.
Fixes #

Beets: Update to v2.2.0

---

spk/borgbackup/Makefile
spk/borgbackup/src/requirements-crossenv.txt
spk/borgbackup/src/requirements-pure.txt

1. Update borgmatic to v1.9.14
Fixes #

Borg: Update borgmatic to v1.9.14

---

spk/icecast/Makefile

icecast: republish with downgraded libxml2

---

cross/cloudflared/Makefile
cross/cloudflared/digests
spk/cloudflared/Makefile

cloudflared: update to v2025.2.1

---

spk/sickchill/Makefile
spk/sickchill/src/requirements-crossenv-greenlet-v3-gcc4.txt
spk/sickchill/src/requirements-crossenv-greenlet-v3.txt
spk/sickchill/src/requirements-crossenv.txt
spk/sickchill/src/requirements-pure.txt

1. Update SickChill to v2024.3.1
Fixes #

SickChill: Update to v2024.3.1

---

spk/sickchill/Makefile
spk/sickchill/src/requirements-crossenv.txt
spk/sickchill/src/requirements-pure.txt
spk/sickchill/src/service-setup.sh

1. Migrate to Python 3.12
Fixes #

SickChill: Migrate to Python 3.12

---

spk/synokernel-cdrom/Makefile
spk/synokernel-usbserial/Makefile

revert unintended changes of #6559

---

native/nodejs/Makefile
native/nodejs/digests

This PR includes the following changes:
1. Update to Node.js v22.15.0
Fixes #

native/nodejs: update to v22.15.0

---

.github/actions/prepare.sh
native/go/Makefile
native/go/digests

- additionally fixes the dependency evaluation
Fixes #

native/go: update to v1.24.3

---

cross/roundcube/Makefile
cross/roundcube/digests
spk/roundcube/Makefile
spk/roundcube/src/service-setup.sh
spk/roundcube/src/wizard/install_uifile.sh
spk/roundcube/src/wizard/uninstall_uifile.sh

1. Upgrade Roundcube Webmail to version 1.6.10
2. Update MariaDB references
Fixes #

Roundcube Webmail: Update to v1.6.10

---

spk/flexget/Makefile
spk/flexget/src/requirements-crossenv.txt
spk/flexget/src/requirements-pure.txt

1. Update FlexGet to version 3.16.3
Fixes #6586

FlexGet: Update to v3.16.3

---

native/go/Makefile
native/go/digests

native/go: update to v1.24.4

---

spk/salt-master/Makefile
spk/salt-master/src/app/master
spk/salt-master/src/requirements-crossenv.txt
spk/salt-master/src/requirements-pure.txt
spk/salt-master/src/service-setup.sh
spk/salt-minion/Makefile
spk/salt-minion/src/requirements-crossenv.txt
spk/salt-minion/src/requirements-pure.txt
spk/salt-minion/src/service-setup.sh

1. Update of salt (master and minion) to version 3007.3
2. Corrects relative path to custom modules (DSM 7)
Fixes #6605

salt: Update to 3007.3

---

cross/owncloud/Makefile
cross/owncloud/digests
spk/owncloud/Makefile

1. Update ownCloud to version 10.15.3
Fixes #

ownCloud: Update to v10.15.3

---

cross/znc/Makefile

Use Synocommunity sources to download as the original site does not work
Fixes #

znc: use alternate download

---

spk/borgbackup/Makefile
spk/borgbackup/src/requirements-crossenv.txt
spk/borgbackup/src/requirements-pure.txt

1. Update borgmatic to v2.0.7
2. Update emborg to v1.42
Fixes #6711

Borg: Update borgmatic to v2.0.7 and emborg to v1.42

---

cross/syncstorage-rs/Makefile
cross/syncstorage-rs/digests
spk/ffsync/Makefile
spk/ffsync/src/requirements-crossenv.txt
spk/ffsync/src/requirements-pure.txt

1. Update syncstorage-rs to v0.20.1
Fixes #

ffsync: Update syncstorage-rs to v0.20.1
