SynoCommunity/spksrc

spk/sonarr/Makefile, spk/sonarr/src/app/config
icon file name in ```spk/sonarr/src/app/config``` needed to match the ```spk_name``` to show up properly in launch menu
=> Fix Sonarr launch menu icon

spk/sonarr/Makefile, spk/sonarr/src/dsm-control.sh
Changed so that mono runs in debug mode to assist Sonarr devs when troubleshooting issues (adds line numbers to logging.)
=> Sonarr runs mono with debug flag

spk/octoprint/Makefile
Minor issue with missing app config file preventing the App icon from appearing in the DSM menu, as reported in #1480.
Didn't update the changelog or version as I don't believe a release has been built yet.
=> #1480: Fixed missing app config file.

cross/ffmpeg/Makefile, cross/ffmpeg/digests, cross/ffmpeg/patches/Makefile.patch, cross/ffmpeg/patches/common.mak.patch, cross/ffmpeg/patches/configure.patch, cross/x264/Makefile
ffmpeg
- Update to 2.6
- Fix compile issue with armada* arches
x264
- Update to latest
ref #1446
=> Update ffmpeg, fix compile issues

spk/debian-chroot/Makefile, spk/debian-chroot/src/installer.sh, spk/deluge/Makefile, spk/deluge/src/installer.sh, spk/gateone/Makefile, spk/gateone/src/installer.sh, spk/haproxy/Makefile, spk/haproxy/src/installer.sh, spk/subliminal/Makefile, spk/subliminal/src/installer.sh
Converted the remaining pybundles to wheel:
- Debian Chroot
- Deluge
- GateOne
- HAProxy
- Subliminal (+update Subliminal to 0.7.5 and prepare for new release)
=> Convert remaining pybundles to wheel

cross/openssl-0.x/Makefile, cross/openssl-0.x/digests, cross/openssl/Makefile, cross/openssl/digests
Fix these vulnerabilities  for openssl 1.0.1 and 0.9.8 :
Segmentation fault in ASN1_TYPE_cmp (CVE-2015-0286)
ASN.1 structure reuse memory corruption (CVE-2015-0287)
PKCS7 NULL pointer dereferences (CVE-2015-0289)
DoS via reachable assert in SSLv2 servers (CVE-2015-0293)
Use After Free following d2i_ECPrivatekey error (CVE-2015-0209)
X509_to_X509_REQ NULL pointer deref (CVE-2015-0288)
Fix these vulnerabilities  for openssl 0.9.8 :
Reclassified: RSA silently downgrades to EXPORT_RSA Client (CVE-2015-0204)
=> Security Update openssl to version 1.0.1m and 0.9.8zf

cross/mono/Makefile, spk/mono/Makefile
The essential mono lib files do not make it into the package if these lines are removed from ```spk/mono/Makefile``` (as done in most recent commit.) To fix this I removed them from cross instead. This solves the issue
=> Mono: Fix- Redundant lines should have been removed from cross not spk

Dockerfile, mk/spksrc.common.mk
Fixes #1658, allowing pure-python wheels to be downloaded/built for Python3 use.
=> Wheels on py3 with docker

Makefile, mk/spksrc.common.mk, mk/spksrc.cross-cc.mk, mk/spksrc.spk.mk
- Move toolchain definitions from spk.mk and cross-cc.mk to common.mk
- Rename `SUPPORTED_TCS/ARCHS` to `AVAILABLE_TCS/ARCHS`
- Add main rules: `all-supported` and `all-legacy`
- Add REQ_KERNEL support to `all-supported` and `all-archs-latest` rules.
Ref #1366
=> Rule updates

spk/debian-chroot/src/app/application/direct.py
The original PR (#1381) was auto closed by GH. All credits to @HakShak.
=> FIX: Debian chroot fails to start up slow scripts

mk/spksrc.spk.mk
This fixes two syntax errors during generation of the INFO file of a package.
Also, I noticed a makefile recipe line that did not start with a TAB.
=> Fix 2x superfluous ) and a missing TAB.

cross/haproxy/Makefile, cross/haproxy/digests, spk/haproxy/Makefile
Fixes #1704
Fixes #1730 
Fixes #1782
Updates haproxy to latest stable version (from 1.5.11 to 1.5.14)
=> Update haproxy, support gzip, fix <1024 ports

spk/debian-chroot/Makefile, spk/debian-chroot/src/app/application/direct.py, spk/debian-chroot/src/app/help/enu/index.html, spk/debian-chroot/src/app/help/fre/index.html, spk/debian-chroot/src/app/help/fre/services.html, spk/debian-chroot/src/preferences, spk/debian-chroot/src/sources.list
- Update version to 8.0-1
- Update base distro to Jessie
- Add commented-out testing entries in apt.sources, and comment out unstable
and experimental. Apt-pinning is never 100% and should not be on by default.
- Clean preferences of references to obsolete third-party repos
=> Update Debian-Chroot to Jessie

cross/gateone/Makefile, spk/gateone/Makefile
This patch will resolve some issues related to special key handling that were resolved in `11ce067` and `56a0409`. There are also some less critical browser compatibility fixes in this latest revision. 
Since gateone development has slowed down lately (due to improved stability) and no new changes have been committed since November 22nd, 2015 it is a good idea to push an update to the syno community to bring these changes in for other synology users.
=> Gateone revision update to 1d0e803

Dockerfile, toolchains/syno-88f6281-5.2/Makefile, toolchains/syno-armada370-5.2/Makefile, toolchains/syno-armada375-5.2/Makefile, toolchains/syno-armadaxp-5.2/Makefile, toolchains/syno-avoton-5.2/Makefile, toolchains/syno-braswell-5.2/Makefile, toolchains/syno-bromolow-5.2/Makefile, toolchains/syno-cedarview-5.2/Makefile, toolchains/syno-comcerto2k-5.2/Makefile, toolchains/syno-evansport-5.2/Makefile, toolchains/syno-monaco-5.2/Makefile, toolchains/syno-x64-5.2/Makefile, toolchains/syno-x86-5.2/Makefile
- Changes the Dockerfile to be based on a 64bit version of Debian.
- In most cases, the toolchains also need adjustments to ensure the correct libc is used (not all packages need it, but the Python SPK does, for example) This PR includes those changes for the 5.2 toolchains. 
Presumably older toolchains can be made to work with similar changes.
I have not tested the resulting packages, imo if compilation works, we're on the right track.
Todo separately:
- Edit the README to fix the VM instructions
- Fix older toolchains
- Fix (cross) packages that are broken on 64b. Go/Syncthing is one, there could be others, can't recall.
=> Migrate to 64bit build env

cross/transmission/Makefile, cross/transmission/PLIST, cross/transmission/digests, cross/transmission/patches/no-debug.patch, spk/transmission/Makefile
Updated Transmission to 2.92
In addition to standard version number changes:
1. Had to update the patch file (Is this still needed?) to reflect line changes
2. Remove transmission-cli from the PLIST file - See 2.92 change log: _"[Don't build transmission-cli by default (it's long deprecated)](https://trac.transmissionbt.com/wiki/Changes)"_
Test compiled on Avoton and qoriq and compiled fine.  Test installed on a DS1515+ and ran fine.
=> Updated Transmission to 2.92

cross/sabnzbd-testing/Makefile, cross/sabnzbd-testing/digests, spk/sabnzbd-testing/Makefile
Build-ed with all-supported.
Test upgraded from current version in channel to this without issues
Should beta be set to 0 or 1, since this is the beta channel?
=> Updated sabnzbd-testing to version 1.0.0

cross/git/patches/git-remove-xdl_fast_hash-check.patch, spk/git/Makefile
Quick Fix for https://github.com/SynoCommunity/spksrc/issues/2202
Still not ideal as we are losing functionality for X64 hosts as I'm just patching this out for all build types.
My limitation of Make and configs show.  I tried calling TC_TARGET (to try and and at least do the if statement for X64 arches) but it was a blank variable in git/config.mak.uname (the culprit).  ARCH works but $(x64_ARCHES) was not returning anything.  
I'm open for ideas - I'm trying to replace `ifeq ($(uname_M),x86_64)` (which is always true because uname_M is based on the build environment) with something that will only be true for x64 host builds (e.g., ARCH of type x64, avoton etc.)
=> Fix bug with certain arches (e.g., qoriq) and xdl_fast_hash

.github/ISSUE_TEMPLATE.md, .github/PACKAGE_REQUEST_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Via https://github.com/SynoCommunity/spksrc/issues/2299.
We can move CONTRIBUTING.md to the same dir, and we can adjust its contents to directly point to the templates instead of the link I added in there a while back.
=> Add issue and package request templates

cross/syncthing/Makefile, cross/syncthing/digests, spk/syncthing/Makefile
_Motivation:_ update syncthing to 13.4 and cleanup.
_Linked issues:_ https://github.com/SynoCommunity/spksrc/issues/2343
I've changed syncthing to use current work-dir as GOPATH which seemed to work pretty well... that sould make sure that we don't get conflicts with other go related tools as every package uses the work dir as GOPATH and links/downloads go source there
Tested installation/upgrade only on cedarview arch!
EDIT: @Dr-Bean for some reason i had to put `cross/busybox` after `cross/$(SPK_NAME)` as it seems that otherwise my custom `$(EXTRACT_PATH)` in `cross/syncthing` was overwritten by the default
=> update syncthing to 0.13.4

native/python/Makefile, native/python3/Makefile
_Motivation:_ These flags are automatically defined
define _LARGEFILE_SOURCE 1
define _FILE_OFFSET_BITS 64
=> Remove useless flags on native python

cross/librsync/4gb.patch
librsync 0.9.7 has a known bug with transfering files > 4GB that has been [fixed upstream](http://sourceforge.net/p/librsync/patches/8/) and [in Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=355178) a few years ago, but there hasn't been a new upstream release.
This patch was applied in Optware/Optware-ng in October 2014 (Optware/Optware-ng@0f4e543b525127056d5a73a6b6b659664c27c7ea).
I couldn't actually get this to build this morning (Docker issues), but it looks like the patch should be applied.
=> Fix librsync 4GB bug

cross/transmission/Makefile
The old transmission source URL is no longer valid and they are now using GitHub - updated to reflect this.
No other changes, packages will be unaffected, however building them will no longer fail.
=> Updated transmission source URL (as old appears to be down)

cross/libpng/Makefile, mk/spksrc.spk.mk
Updated to not verify the remote repository API SSL as api.synocomminity.com is currently expired
=> Removed SSL Repo Verification

cross/libtiff/Makefile
The originating LibTIFF sites is no longer available, therefore I've had to update the source code download location
=> Updated LibTIFF locations

spk/sabnzbd/Makefile
Updated to show new logo, as the version had been moved to 1.x but the logo hadn't
=> Updated to new logo

cross/tessdata-eng/Makefile
tesseract-ocr has moved o github.
This project has moved to a new location on the internet. The tessdata files can be downloaded from Sourceforge
=> Fixed tessadata download url. 

README.rst
See #2503 I believe this was deleted accidentally, as now there's no reference at all how to use spksrc to build any of the packages in any document of this repository.
=> Put the Usage section back into README

cross/openssl/Makefile, cross/openssl/digests
OpenSSL version with 1.0.2i is not avaliable for download. Replacing with 1.0.2j
=> Update openssl to 1.0.2j

cross/jackett/Makefile, cross/jackett/digests, spk/jackett/Makefile
_Motivation: Update version to a working version to users can access torrentday
_Linked issues: https://github.com/SynoCommunity/spksrc/issues/2559
=> Updated Jackett to new version to stop breaking change in Jackett

cross/pycurl/Makefile, cross/pycurl/digests
_Motivation:_ Pycurl's current version is no longer hosted at the url. The new url has been added.
_Linked issues:_ SynoCommunity/spksrc#2569
- [ok] Package upgrade completed successfully
- [ok] New installation of package completed successfully
=> Update pycurl download url and hashes

spk/sabnzbd-testing/Makefile
Updated to ensure that the new SABnzbd beta and RC versions don't complain about a lower version of Python thus supporting better SSL functionality
=> Updated SABnzbd to rely on at least Python 2.7.9

spk/sabnzbd/Makefile
Updated to ensure that the python minimum requirement won't be missed, ensuring that the new SSL functionality in the 1.2.x versions won't complain
=> Updated to require a minimum python 2.7.9 in preparation for 1.2.x

cross/zlib/Makefile, cross/zlib/PLIST, cross/zlib/digests
Fixes #2607
_Motivation:_ zlib archive for 1.2.10 is no longer available
=> Upgrade zlib to 1.2.11

cross/syncthing/Makefile, cross/syncthing/digests, native/go/Makefile, spk/syncthing/Makefile, spk/syncthing/src/config.xml, spk/syncthing/src/dsm-control.sh, spk/syncthing/src/options.conf
_Motivation:_ My aim was to share integration syncthing-inotify to the package, as I didn't like any other startup options. By the way, I also updated Syncthing and Go to the latest version, just to keep track recent changes in them.
_Linked issues:_ #2142 
- [OK] Build rule `all-supported` completed successfully
- [OK] Package upgrade completed successfully (tested at 88f6281, ds111)
- [OK] New installation of package completed successfully (tested at 88f6281, ds111)
=> Update: Syncthing to 0.14.21, Go (dependence) to 1.7.4

cross/syncthing/Makefile, cross/syncthing/digests, spk/syncthing/Makefile, spk/syncthing/src/config.xml
_Motivation:_ Update syncthing to 0.14.23 mainly because a) 0.14.21 has bug with restart after update; b) set release channel to 'stable' in default config.
_Linked issues:_ *no*
=> Update Syncthing to 0.14.23

cross/syncthing-inotify/Makefile, cross/syncthing-inotify/digests, spk/syncthing-inotify/Makefile
_Motivation:_ This is an important update because syncthing 0.14.22+ will no longer work with syncthing-inotify 0.8.4 (see https://github.com/syncthing/syncthing-inotify/issues/154)
_Linked issues:_ no
=> Update Syncthing-Inotify to 0.8.5

cross/libtorrent/Makefile, cross/libtorrent/digests
_Motivation:_ Updated to latest working version of librtorrent
_Linked issues:_ As requested in https://github.com/SynoCommunity/spksrc/issues/2719
=> Updated librtorrent to 1.0.11

cross/par2cmdline/Makefile, spk/sabnzbd-testing/Makefile, spk/sabnzbd/Makefile
_Motivation:_ Attempting to fix broken par2cmdline
_Linked issues:_ https://github.com/SynoCommunity/spksrc/issues/2735
=> Updated to restore par2cmdline build parameters

cross/par2cmdline/Makefile, spk/sabnzbd-testing/Makefile, spk/sabnzbd/Makefile
_Motivation:_ Statically linked par2cmdline so that multicore support is available
_Linked issues:_ https://github.com/SynoCommunity/spksrc/issues/2735
There is a larger memory overhead for this, so for low memory or single core systems, we can look to disable per architecture (I'm guessing mainly ARM devices)
=> Updated to push latest statically compiled par2cmdline

cross/openssl/Makefile, cross/openssl/digests
_Motivation:_ Update openssl to the latest version. Reasoning: I wanted to start a new package, but since it depends (indirectly) on openssl, and the version in the package is no longer available (except in the old/ folder), I updated this one.
_Linked issues:_ N/A
I'm not entirely certain how I can properly test this - there seems to be no package built, or I'm utterly looking in the wrong spot.
=> Update openssl to 1.0.2l

cross/syncthing/Makefile, cross/syncthing/digests, native/go/Makefile, spk/syncthing/Makefile
I've updated Syncthing to the latest stable - 0.40.30, and also pulled in the latest go release (1.8.3), so we are a bit more uptodate again on that field.
Tested on my DS.
=> Updates to syncthing / go

spk/tvheadend/src/conf/PKG_CONX
_Motivation:_ Running TVheadend concurrently with a TVheadend-testing package can create problems. They might want to use the same ports or lock the same tuners. This might(!) also solve package the presisting publication issues on the Synocommunity build platform (cannot test).
=> [TVH] Prevent concurrent installation with tvheadend-testing

cross/owncloud/Makefile, cross/owncloud/digests, spk/owncloud/Makefile
_Motivation:_ End-of-Life for 8.1 version. Prepare to upgrade to 9.1
_Linked issues:_ #2710
Works on DSM 6.0.2 only IF:
- packages Web Station, Apache 2.2 and PHP 5.6 have to be installed first
- PHP extensions must be enabled: https://doc.owncloud.org/server/8.1/admin_manual/installation/source_installation.html#prerequisites-label
- PHP customized `open_basedir` must be appended with `:/dev/urandom:/volume1/owncloud`
=> ownCloud minor upgrade to 8.1.12

mk/spksrc.common.mk, toolchains/syno-apollolake-6.1/Makefile, toolchains/syno-apollolake-6.1/digests, toolchains/syno-denverton-6.1/Makefile, toolchains/syno-denverton-6.1/digests, toolchains/syno-x64-6.1/Makefile
_Motivation:_ Adds toolchain support for NASs with apollolake and denverton architecture
_Linked issues:_ #2939 (apollolake) and on request of @ymartin59 (denverton).
=> [DSM6] Add support for apollolake and denverton toolchains (6.1)

cross/openssl/Makefile
The current download location is no longer valid which breaks build.
=> Correct openssl download location

toolchains/syno-x64-5.2/Makefile
Target: apollolake broadwell denverton grantley
Even if these never run DSM 5, this change allows to deliver
DSM 5+6 compatible binaries in a single x64 package.
=> Include recent architectures to x64 5.2 toolchain

mk/spksrc.service.installer, mk/spksrc.service.mk, mk/spksrc.service.start-stop-status
DSM 6 privilege user is prefixed by sc-
DSM 5 synouser account is prefixed by svc-
Each package is responsible to clean busybox account
_Linked issues:_ #2904
=> Rework service account creation to avoid collision

mk/spksrc.service.installer
2 bugfixes and the option to use `set_syno_permissions` to correct permissions specific to package.
Tested with `spk/sabnzbd` and works as expected.
Would suggest not to squash into single commit to preserve easier commit-history reading.
=> Changes to Generic service

cross/fribidi/Makefile, cross/openssl/Makefile, cross/openssl/digests, cross/x264/Makefile
When experimenting with travis-CI on my private `spksrc` repo, I encountered several compile issues due to outdated cross-packages. This PR addresses those issues. 
- fribidi: Download location for sources no longer available. Replaced by alternative source (same package).
- openssl: No issue actually, but realized that we are running two releases behind. Updated to 1.0.2n.
- x264: The old download location still worked, but required the `--no-check-certificate` option for `wget` to work. Adapting the download location to the (new) official source URL fixes the issue.
I conducted runtime-tests but only on individual packages for individual platforms. Based on the nature of the changes I would not expect any kind of issues though...
=> Various dependency fixes (fribidi, openssl, x264)

cross/libconfig/Makefile, cross/libconfig/PLIST, cross/libconfig/digests
Update to libconfig 1.7.1 and also update homepage of libconfig project.
Motivation: compilation error for umurmur due to libconfig links broken.
=> Update to libconfig 1.7.1

mk/spksrc.common.mk
As described in #3080 the `hi3535` arch couldn't compile Python because of a problem with `libgpg-error`. 
Turns out all that was needed was to add it to the ARMv7 arches. Now Python builds for `hi3535` [without a problem](https://travis-ci.org/Safihre/spksrc/builds/326366000).
_Not a Python-specific issue, so separate PR._
=> Add hi3535 to ARMv7 archs

cross/pcre/Makefile
enable unicode support in regex library pcre
related packages: mc, sshfs, irssi, bitlbee, museek-plus
_Motivation:_ 
Midnight Commander is the first package I created for my DS918+. Installation worked fine, but in special folders an error appeared about pcre not compiled with unicode support.
Did not find documentation how to configure parameters for dependent module of a single spk, so update the makefile in cross/pcre. Therefore all related packages get unicode support for pcre.
=> enable unicode support for Midnight Commander et al. (PCRE)

mk/spksrc.service.installer
_Motivation:_ While working on adapting the Tvheadend package for generic service use, I have encountered two issues with automatic permission setting for shared directories within `mk/spksrc.service.installer`:
1. The paths of shared directories containing symbolic links are not resolved.
2. If the path of a shared directory does not reside in a `/volume[X]` folder, the permission setting function can recurse into system directories, which is certainly not wanted. 
This PR addresses those issues.
- Tested via automatic permission setting on directories with and without symbolic links, within and outside of `/volume[X]` directories.
=> Improve permission setting for shared folders in generic service scripts

mk/spksrc.service.installer
_Motivation:_ Lost an important fixup commit when rebasing for #3084. Without it, infinite loops can occur.  
_Linked issues:_ #3084
=> Fix permission setting in spksrc.service.installer

cross/sslh/Makefile
URL changed from "http://www.rutschle.net/tech/sslh-v1.17.tar.gz" to "http://www.rutschle.net/tech/sslh/sslh-v1.17.tar.gz"
_Motivation:_ While trying to compile sslh for arch-apollolake-6.1, I found the URL to the package had changed.
To successfully compile the package I also needed to update the dockerfile to use debian:stretch rather than debian:jessie and added texinfo package (makefile 1.15 and makeconfig were required); these are not included in the pull request.
=> Update sslh pkg download URL

mk/spksrc.common.mk, toolchains/syno-broadwellnk-6.2/Makefile, toolchains/syno-broadwellnk-6.2/digests, toolchains/syno-x64-5.2/Makefile, toolchains/syno-x64-6.1/Makefile
this is the toolchain of broadwellnk for the new DS3018x and FS1018 that support DSM 6.2 only.
even the DSM 6.2 is still beta, the toolchain on sourceforge.net is not named beta
_Motivation:_ DS3018x, FS1018 support DSM 6.2 only.
_Linked issues:_ #3041
- [n/a] Package upgrade completed successfully
=> toolchain of broadwellnk arch

kernel/syno-kvmx64-6.1/Makefile, kernel/syno-kvmx64-6.1/digests, mk/spksrc.common.mk, toolchains/syno-kvmx64-6.1/Makefile, toolchains/syno-kvmx64-6.1/digests, toolchains/syno-x64-6.1/Makefile
_Motivation:_ Synology Virtual DSM is not yet supported by SynoCommunity
_Linked issues:_ #3142
As commented in #3142, synology names the arch of Virtual DSM kvmx64 (fixed in mk/spksrc.common.mk)
Maybe the synology DSM package manager is not yet ready for this...
- [n/a] Package upgrade completed successfully
TODO:
- Test kvmx64 arch with DSM package manager
=> add kvmx64 arch (DSM 6.1 toolchain and kernel)

cross/alsa-lib/Makefile, cross/alsa-lib/patches/001-no-tls-pfx.patch, cross/bison/Makefile, cross/erlang/Makefile, cross/gmp/Makefile, cross/gnutls/Makefile, cross/libxml2/Makefile, cross/lxml/Makefile, cross/nettle/Makefile, cross/rtorrent/Makefile, cross/syncthing-inotify/Makefile, cross/syncthing/Makefile, mk/spksrc.common.mk, spk/ffsync/Makefile, spk/lirc/Makefile
The `88f5281` arch was depcreated a while ago, now all reference to it can be removed.
Also replaced some arch-specific selections to the definitions from `*_ARCHS`.
@ymartin59: I was added to the SynoCommunity group by @Diaoul (to my surprise). Will try to contain my desires to just commit-commit-commit and use the PR's to get double checks! I might close some issues, since I really like cleaning 🥇
=> Remove references to deprecated arch 88f5281

mk/spksrc.service.installer
Support functions needed to:
- Correct permissions on folders during upgrade in Linux mode.
- For transfer for download-related packages from 'sc-media' to 'sc-download'
@ymartin59 This separate PR to keep package PR's clean. But all my other PR's kind of depend on it.
After this is merged, I can rebase #3092 #3153 #3053 on `master` after that so they are package-only.
=> Add set_unix_permissions and syno_user_add_to_legacy_group

spk/radarr/src/service-setup.sh, spk/radarr/src/wizard/install_uifile, spk/radarr/src/wizard/install_uifile_fre, spk/radarr/src/wizard/upgrade_uifile, spk/radarr/src/wizard/upgrade_uifile_fre, spk/sonarr/src/service-setup.sh, spk/sonarr/src/wizard/install_uifile, spk/sonarr/src/wizard/install_uifile_fre, spk/sonarr/src/wizard/upgrade_uifile, spk/sonarr/src/wizard/upgrade_uifile_fre
Needs #3161, separated for clarity.
Uses the functions and changes there to make Sonarr/Radarr work on DSM6 but also 5.
=> Sonarr and Radarr fixes

mk/spksrc.service.installer
Doing the extensive testing of the new packages I found another problem:
For some reason on DSM5.2 running and using the old-style-package results in a mix of Linux permissions ~~(due to being run as a non-Synology-user maybe?)~~ (see below) and the dropping of ACL permissions:
```
DSM52> synoacltool -get "/volume1/sabtest5"
(synoacltool.c, 350)It's Linux mode
DSM52> ls -al /volume1
drwxrwx---    4 root     users         4096 Feb 23 10:42 sabtest5
```
As mentioned before, using `synoacltool` on folders that used to have Linux permissions causes them to get `000` permissions.
So when we run `set_syno_permissions` on `/volume1/sabtest5/incomplete` (extracted from SABnzbd's config) during the new-style update , this happens:
```
DSM52> synoacltool -get "/volume1/sabtest5"
ACL version: 1 …
```
=> Add permissions for "administrators" group to Linux-permissions folders

mk/spksrc.service.installer
Same as described before in #3165, old packages that forced Linux-permissions on the share will not be accessible from File Station after `synoacltool`.  
Although it won't disappear in this case and users can easily fix it, it's better if we handle it during upgrade:
=> Main share also needs administrators-permissions

mk/spksrc.service.start-stop-daemon, mk/spksrc.service.start-stop-status, spk/couchpotatoserver-custom/src/service-setup.sh, spk/couchpotatoserver/src/service-setup.sh, spk/sabnzbd/src/service-setup.sh, spk/sickrage/src/service-setup.sh, spk/transmission/src/service-setup.sh
Due to #3138 I noticed not all packages have correct `LOG_FILE` set and as such users can't get the log from Package Center.
@ymartin59 This includes Transmission, maybe this can go in before you publish?
=> Correct logging redirection

toolchains/syno-x64-6.1/Makefile
_Motivation:_ dockex64 arch is compatible to syno-x64
_Linked issues:_ #2872
as supposed by @ymartin59 dockex64 arch is compatible to syno-x64
after testing with mc (based on /cross/mc) I saw that the toolchains of syno-x64 and syno-dockerx64 are almost binary the same - only 3 header files (.h) are different and one of them is autogenerated kernel configuration.
=> add dockerx64 to generic toolchain

cross/openssl/Makefile
_Motivation:_ fix OPENSSL_ARCH for apollolake and other archs
_Linked issues:_ A lot of packages use openssl
- Add the available arch macros to Makefile.
- Fix for different intel archs (apollolake, broadwell, dockerx64, ...) to use `linux-x86_64` (was `linux-generic32`) 
- Fix for ARM8 arch (rtd1296)
- Use `linux-x32` for x86 arch (was `linux-generic32`) 
Published packages for all kind of x64 archs use the general x64 arch, and therefore are not affected.
There are still some older archs using `linux-generic32` that are handled as before, to not break existing builds.
=> fix openssl arches

mk/spksrc.service.installer, mk/spksrc.service.start-stop-status, spk/radarr/Makefile, spk/radarr/src/service-setup.sh, spk/sonarr/Makefile, spk/sonarr/src/service-setup.sh, spk/transmission/Makefile, spk/transmission/src/service-setup.sh
Grant GROUP (sc-download) permission to browse subfolder in Share Folder
Conditionally enlist service user into "users" group to access contents
_Linked issues:_  #3192 #3215 #3212 #3185
=> Fix various permission issues

cross/openssl/Makefile
_Motivation:_ #3218 introduced a regression for the `evansport` platform, breaking compilation 
_Linked issues:_ N/A
=> [Openssl] Fix evansport regression

spk/nzbget/Makefile
=> nzbget publish again because of corrupted package

mk/spksrc.common.mk, toolchains/syno-ipq806x-1.1/Makefile, toolchains/syno-ipq806x-1.1/digests
_Motivation:_ Make it easier to get started and build for the RT2600ac Router (ipq806x).
_Related issues:_ #2951
Not sure if this is wanted due to it being listed as [No longer recieving packages updates](https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model#models-no-longer-recieving-packages-updates). But I thought a pull request at least gives visibility and can help people if they want to do it themselves.
=> Add ipq806x architecture for SRM 1.1

mk/spksrc.service.mk, mk/spksrc.service.start-stop-status, mk/spksrc.spk.mk
_Motivation:_ These changes where needed to run general service packages on a RT2600ac 
It also allows package descriptions to contain characters that would otherwise be interpreted eg. `(` and `)`.
=> Fixes for SRM 1.1 and package description

cross/sabnzbd/Makefile, cross/sabnzbd/digests, spk/sabnzbd/Makefile, spk/sabnzbd/src/requirements.txt, spk/sabnzbd/src/wizard/install_uifile, spk/sabnzbd/src/wizard/install_uifile_fre, spk/sabnzbd/src/wizard/upgrade_uifile, spk/sabnzbd/src/wizard/upgrade_uifile_fre
I contributed to this repo in order to get my project SABnzbd available for DSM6. But even though it was the first package I converted to Generic service approach, it's _still_ not published many months later.
Because SABnzbd is still not published while NZBGet, Sonarr/Radarr and Transmission were published, I have lost motivation in the past few weeks to contribute to this project.
I have not asked for it in a few months.. so I hope now you will finally publish my project @ymartin59.
=> Update SABnzbd to 2.3.3

mk/spksrc.wheel.mk, spk/python/Makefile
Add WHEELS_CFLAGS and WHEELS_LDFLAGS to pass additional cross-compilation options to "pip wheel"
_Motivation:_ Update and fix cryptography wheel
_Linked issues:_ #3246 #3201
=> python 2.7: fix cryptography wheel for ARM

mk/spksrc.service.mk, mk/spksrc.spk.mk
Allow to use same description in both INFO and app/config
with escape requirements whatever language is.
Break build with JSON syntax checking
Resolves #3339
=> framework: fix description specific characters handling

mk/spksrc.spk.mk
Base of SDK Developer Guide updates.
Resolves #2966
Idea is to generate DSM 5.2 package also compliant for DSM 6.x, including both `firmware` and `os_min_ver`, when building with 5.2 toolchain
=> Improve package INFO generation

cross/bzip2/Makefile, cross/bzip2/digests
Domain bzip.org is no longer registered
Resolves #3425
=> bzip2: use debian repository as download source

cross/acl/Makefile, cross/acl/patches/builddefs-include.patch, cross/acl/patches/install-softlinks-full-path-always.patch, cross/acl/patches/old-libtool-workaround.patch, cross/libgpg-error/Makefile, cross/libxslt/Makefile, cross/pycrypto/Makefile, cross/python3/Makefile, cross/python3/PLIST, cross/python3/digests, cross/python3/patches/001-mimetypes.patch, cross/python3/patches/002-xcompile.patch, cross/python3/patches/003-rpath.patch, cross/python3/patches/004-xcompile-paths.patch, native/python3/Makefile, native/python3/digests, spk/python3/Makefile
_Motivation:_ I'm a fan of Home Assistant which needs 3.5.3 or later, and it's a real dependency, not just a "we don't know whether it'll work with 3.5.2".
The intention is to move through to 3.7.0 once this lands so that the logic here and the logic to move to 3.7.0 are separate.  The upgrade to 3.7.0 should be fairly straightforward after this diff.
_Linked issues:_ Scratching my own itch, I've seen this mentioned in chats.  I saw #3379 filed a few days ago by @ymartin59 
- openssl does not seem to support all ARM:
arm_arch.h:46:6: error: #error "unsupported ARM architecture"
- (cd spk/python3 && make all-supported) ongoing (keep running out of space)
I've been granted permission by my employer to contribute to spksrc without risk …
=> Make Python3 build again; bump to 3.5.5

spk/rdiff-backup/src/requirements.txt
_Motivation:_ Fix package rdiff-backup
The rdiff-backup package has a incorrect requirement that breaks the package build process
This PR removes that requirement
=> Remove wrong requirement in rdiff-backup package

spk/deluge/Makefile
_Motivation:_ I want to be able to run Deluge on my DS413 (qoriq)
I'm not sure what the issue was back in 4a9d7846001ca724aad5106391da0344f868c9a3, but it seems to have been resolved. Deluge compiles just fine and and works correctly at least on qoriq, the only platform I have available for testing.
=> Bring back PPC_ARCHES for Deluge

cross/gmp/Makefile, cross/libgpg-error/Makefile, cross/nettle/Makefile
_Motivation:_ Fix GnuPG package cross-compile on ARM architectures
The Makefile in three GnuPG dependencies didn't define the correct **host** and **target** to cross-compile on several ARM architectures (and maybe non-ARM also)
The affected libraries where: gmp, libgpg-error and nettle
This PR fixes the Makefiles to allow cross-compile on (hopefully) all archs
=> Fix GnuPG cross-compile on rtd1296 and other ARM architectures

mk/spksrc.service.mk
_Motivation:_ even with generic service usage, DSM_UI_DIR = app is still required for menu item and icons.Default value is now set at right place.
=> framework: fix DSM_UI_DIR defaults to app

cross/syncthing/Makefile, spk/syncthing/Makefile
=> syncthing: no support for qoriq/ppc32

spk/itools/Makefile, spk/itools/src/39-libimobiledevice.rules, spk/itools/src/common.py, spk/itools/src/mounting.py, spk/itools/src/on-inserted.sh, spk/itools/src/on-removed.sh, spk/itools/src/service-setup.sh, spk/itools/src/umounting.py
Hello
I have finished including those scripts into itools package.
I also modified the version and rename it to be "iOS Access".
Please help me on reviewing this pull request. Thanks!
(Since it have different names now, there are no upgrade cases. As a result, it will stop the previous package, and the new package works fine.)
Here are udev rules and scripts to detect the hotplug events of
iOS devices and run python scripts to mount/umount into/from
FileStation.
Signed-off-by: BingJing Chang <bxxxjxxg@gmail.com>
=> itools: udev rules and mount/umount scripts

cross/mercurial/Makefile, cross/mercurial/digests, spk/mercurial/Makefile
_Motivation:_ Update Mercurial to 4.8.1.
_Linked issues:_ none
I'm not sure what the `all-supported` rule is? (`make all-supported` isn't a valid target). But I did build the package for `avoton-6.1` and upgraded it on my NAS, then uninstalled it and re-installed it from scratch.
=> mercurial: update to 4.8.1

spk/syno-magnet/Makefile, spk/syno-magnet/PLIST
The package name has been changed so we need to update the web app url. Override the 'config' coming from the app with the proper location.
_Motivation:_ The package name changed in  https://github.com/SynoCommunity/spksrc/commit/4eacfb652c96339a992af705d43677b9bf7bc9a7 which caused the url to change. The app assumes a different URL so the PR overrides the app assumption with the correct location.
=> syno-magnet: Update package location because of renamed package name

Makefile
_Motivation:_ 
In looking at build instructions, it makes me think that there must be a more trivial set of instructions.
Instead of:
```
$ make setup
$ cd spk/python3
$ make arch-XXXX
$ exit
```
The resulting command is:
`sudo docker run -it --rm -v $(pwd):/spksrc -w /spksrc  synocommunity/spksrc  make  python3-avoton-6.1`
Can make home-assistant/home-assistant.io#7861 more trivial
=> One shot spk arch convenience func

spk/tmux/Makefile
_Motivation:_ Fixed package version number of tmux, tmux version is already 2.8
_Linked issues:_ #3574
=> fixed version number of tmux package

mk/spksrc.install.mk
_Motivation:_ have proper information in pkgconfig to allow cross-package dependencies and library runtime loading
Reference: https://www.gnu.org/prep/standards/html_node/DESTDIR.html
=> framework: fix make install for pkgconfig files

mk/spksrc.install.mk
Reverts SynoCommunity/spksrc#3589, as agreed by @ymartin59.
Leads to regressions, e.g. with `cross/ncurses`, which require further examinations.
=> Revert "framework: fix make install for pkgconfig files"

mk/spksrc.cross-cc.mk
_Motivation:_ Allow each cross/x Makefile to provide a local PLIST_TRANSFORM to filter PLIST content depending on compilation conditions, typically current architecture
_Linked issues:_ #3575
=> framework: add PLIST_TRANSFORM for cross Makefile

cross/bzip2/Makefile, cross/ddrescue/Makefile, cross/fdupes/Makefile, cross/fuse/Makefile, cross/gnupg/Makefile, cross/he853/Makefile, cross/libxml2/Makefile, cross/libxslt/Makefile, cross/lirc-0.8.7/Makefile, cross/lirc-0.9.0/Makefile, cross/lz4/Makefile, cross/ncurses/Makefile, cross/ncursesw/Makefile, cross/openssh/Makefile, cross/openssl/Makefile, cross/python3/Makefile, cross/redis/Makefile, cross/shairport-sync/Makefile, cross/umurmur/Makefile, cross/unrar/Makefile, mk/spksrc.install.mk
Following DESTDIR make install addition, most path are as expected.
Add rpath-link for compilation against dependant package binaries.
_Motivation:_ allow compilation and runtime linkage across different SPK packages
_Linked issues:_ #3587
=> framework: fix pkgconfig rpath and rpath-link

cross/tvheadend/Makefile, cross/tvheadend/digests, cross/tvheadend/patches/ppc/hts_strtab-undo-inlining-of-functions.patch, cross/uriparser/Makefile, cross/uriparser/PLIST, cross/uriparser/digests, cross/util-linux/Makefile, spk/tvheadend/Makefile, spk/tvheadend/src/service-setup.sh
- Update Tvheadend to 4.2.8 (latest maintenance release)
- Fixes software transcoding with h264 (broken in 4.2.7 maintenance release)
- Fixes upstream regression for `ppc` platforms
- Enables HDR10+ support for `ffmpeg` spawn profile for NASs with `x64` architecture 
- Remove beta flag of TVH package 
- https://tvheadend.org/boards/5/topics/27780?r=35267#message-35267
- PR #3530
=> Update Tvheadend to 4.2.8 and remove beta flag of package

cross/borgbackup/Makefile, cross/borgbackup/digests, spk/borgbackup/Makefile, spk/borgbackup/src/requirements.txt
borgmatic: update to 1.2.15
_Motivation:_ support for Python 3.6
_Linked issues:_ depends on #3562
=> borgbackup: update to 1.1.9 for python 3.6

mk/spksrc.common.mk, mk/spksrc.directories.mk, mk/spksrc.spk.mk, mk/spksrc.wheel.mk
_Motivation:_ 
Building large targets such as `all-supported` takes a long long time.  One thing that bugs me is when things are unnecessarily done: like re-downloading the same wheel via PIP for each and every build.  That doesn't seem like the right thing.
Now, this won't cleave the build time in half (unless you're building is slow shared wifi like coffee shops), but avoiding some downloads will speed things up, reduce unexpected download costs, and let us do builds in coffee shops.
_Linked issues:_ none
Checklist does not apply, but I've checked them off to ensure a "3 of 3" marker on the PR.  There's no specific package to build; rather, success is recognizing that cache is populated when clean and used on subsequent builds of similar content.
Tested with a `make -C spk/python …
=> Accelerate build: ensure upstream pip/wheel downloads are cached

Dockerfile
_Motivation:_ Get recent Meson to build recent fuse for sshfs (synocli-net)
Docker image is far lighter that previous one on Jessie because I discarded most documentation tooling (mainly latex) with `--no-install-recommends`
=> framework: new docker image based on Debian Stretch

cross/gmp/Makefile
Closes #3625
_Motivation:_ GMP framework configure "prefix" option is lost somewhere in the process...
_Linked issues:_ #3625 #3623 #3462
=> ffmpeg: fix GMP install prefix

mk/spksrc.directories.mk, mk/spksrc.tc.mk
DISTRIB_DIR and DISTRIB_FILE are input parameters for spksrc.download.mk
To avoid mistake, "distrib" folder is now identified as BASE_DISTRIB_DIR
_Motivation:_ Fix toolchain operations (download, digests, extract, patch)
=> framework: fix DISTRIB_DIR recursive definition

mk/spksrc.icon.mk, mk/spksrc.spk.mk, spk/squidguard/Makefile, spk/wallabag/Makefile
_Motivation:_ Each time a package is built, it is binary different.
I figured out, that the only difference in the packages is the content of the icons generated with convert.
The icons differ in metadata only (creation datetime).
With the option -strip the metadata is removed from the images. Unfortunately this works with newer versions of convert only.
The current spksrc Docker image based on jessie comes with convert based on imagemagick 6.8.9-9 and this version does not strip.
With an updated Docker image based on stretch and with convert based on imagemagick 6.9.7 icons are stripped as expected.
=> improve icon generation

cross/ffmpeg/Makefile
Disable asm since qoriq (e500v2) has no AltiVec support.
=> Fix support for qoriq cpu (DS413, DS213+)

cross/sabnzbd/Makefile, cross/sabnzbd/digests, cross/unrar/Makefile, cross/unrar/digests, cross/unrar/patches/001-remove-defaul-env-flags.patch, spk/sabnzbd/Makefile
Closes #3667
Also updated `unrar`, other packages that depend on `cross/unrar` can benefit from that in the next update of those packages. Update of `unrar` doesn't seem to be essential enough to warrant re-release just for it.
=> Update SABnzbd 2.3.8 and unrar to 5.7

cross/imagemagick/Makefile, cross/imagemagick/digests, spk/imagemagick/Makefile
_Motivation:_ Imagemagick failed to build as the package is no longer available on http://www.imagemagick.org/download/releases/
The alternative is to fetch the source code from github: https://github.com/ImageMagick/ImageMagick/releases/tag/7.0.7-30
I know there's more recent builds but they don't keep the source of the recent builds on their release page.
=> Bump imagemagick to stable version

Makefile, mk/spksrc.common.mk, mk/spksrc.compile.mk, mk/spksrc.cross-env.mk, mk/spksrc.directories.mk
_Motivation:_ when building package for a single architecture, top level `-jX` option is useless
_Linked issues:_ #49
=> Add support for parallel make compilation

mk/spksrc.spk.mk
_Motivation:_  Fixes uninstall of owncloud version 8.1.1-7 (Incorrect MySQL root password)
Working on an update of ownCloud I came accross this issue of missing uninstall wizard.
- Fix name of uninstall_uifile
- Without this fix all packages are missing the uninstall wizard
- Bug was introduced by commit 3dcf358 of #3302
- Fixes #3336
- Older issues of "Incorrect MySQL root password" are not related, since this bug was introduced in May 2018.
=> Fix packaging of uninstall wizard file

README.rst
_Motivation:_  Latest commit to alpha-reorder included a typo where apt install command is actually missing
_Linked issues:_  Conflict part of #3751 brought this to my attention
=> Fix typo for missing apt update command

cross/syncthing/Makefile, cross/syncthing/digests, spk/syncthing/Makefile
_Motivation:_  Upstream has some partly backwards-incompatible changes, so it's better when users see an up-to-date version for the SPK as well. It auto-updates anyway right after installation, but publishing a recent version would save on migrations being done.
_Linked issues:_  fixes #3761
=> syncthing: Incorporate upstream release v1.2.2.

cross/rsync/Makefile, cross/rsync/PLIST, cross/rsync/digests, spk/synocli-net/Makefile, spk/synocli-net/src/service-setup.sh
_Motivation:_ Synologys built-in rsync is old and have features that prohibits receiving data over ssh.
=> Added rsync version 3.1.3 to synocli-net

spk/redis/Makefile
_Motivation:_  Clean busybox dependency for Redis server and fix maintainer name
Tested successfully on braswell architecture
=> Remove busybox dependency for Redis

cross/rmlint/Makefile, spk/synocli-file/Makefile
Fix the build of synocli-file for arch-ppc853x-5.2 that is built with `all-supported`
- avoid build and dependency of `cross/rmlint`  for ppc arches except qoirq.
=> synocli-file: remove rmlint for ppc853x

mk/spksrc.service.create_links
@ymartin59 I am sorry for this.
A small syntax error broke the symlink creation
=> fix symlink creation

cross/tvheadend/Makefile, spk/tvheadend/Makefile
_Motivation:_  Fix for ARMv5 arch `88f6281` build failure as found by @ymartin59 while investigating issue #3863.
_Linked issues:_  None
=> tvheadend 4.3: ARMv5 arch 88f6281 build fix

mk/spksrc.patch.mk
_Motivation:_  Allow arch specific patches to be applied automatically.
_Linked issues:_  Relates to multi-patches on ffmpeg where some of them are arch specific
@hgy59 : To be sure about existing packages I propose to test the following:
=> Allow arch-specific level patch to mk build

cross/setuptools/Makefile, cross/setuptools/digests, cross/wheel/Makefile, mk/spksrc.python-module.mk
_Motivation:_  current Python3 package does not run
_Linked issues:_  [Error reported here ](https://github.com/SynoCommunity/spksrc/pull/3906#issuecomment-593587061)
The error was introduced with commit 2d23bd2ed3dc5386fbc6bbd18d88f4003707577d 
- Unfortunalty the shebang adjustment in the installed python files depended on the file type in the PLIST file.
- The error was introduced by changing file types in PLIST from `bin` to `rsc` (to avoid logging of stripping errors, I suppose).
- This type is used to decide whether an installed file can be stripped. It was bad design to look only for `bin` types in PLIST to adjust the python shebang when package is a python-module.
- Now independent of PLIST, all installed files of type "Python script" get the shebang adjustment.
- Now every patched …
=> Fix build of python module files

mk/spksrc.service.call_func, spk/beets/Makefile, spk/beets/src/requirements.txt, spk/beets/src/service-setup.sh
_Motivation:_  Beets is a pure python package that supports python3
_Linked issues:_  #3743, bypass #3897, #3901, #2572
- Unfortunatly #3897 was pushed from a `master` branch, so I created my own.
- As discussed in #2572 this is still a command line tool. So there is no service `beet web` nor user created.
- The output of `beet help` is no longer added to the installation log, expecting there is no configuration for the `root` user.
- We should migrate all _pure python_ packages to python3 where supported (#3633)
=> Update beets to v1.4.9 and migrate to Python3

cross/openssl/Makefile
Old OpenSSL versions have been moved to a separate download path.
This patch fixes the compilation of packages depending on OpenSSL (like Python3) that were failing to download the source due to a wrong download URL.
```
$ wget -O /dev/null https://www.openssl.org/source/openssl-1.0.2n.tar.gz
--2020-04-04 11:04:52--  https://www.openssl.org/source/openssl-1.0.2n.tar.gz
Resolving www.openssl.org (www.openssl.org)... 2a02:26f0:f3:585::c1e, 2a02:26f0:f3:598::c1e, 104.83.84.113
Connecting to www.openssl.org (www.openssl.org)|2a02:26f0:f3:585::c1e|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-04-04 11:04:52 ERROR 404: Not Found.
$ wget -O /dev/null https://www.openssl.org/source/old/1.0.2/openssl-1.0.2n.tar.gz
--2020-04-04 11:05:00-- …
```
=> Correct OpenSSL download URL path

spk/python3/src/requirements.txt
_Motivation:_  `virtualenv` in `python3` is not working due to missing dependencies
* Needed for #3916, probably other python3 packages too such as `borgbackup`
=> fix: python3 virtualenv dependencies

spk/jackett/src/service-setup.sh, spk/lidarr/src/service-setup.sh, spk/radarr/src/service-setup.sh, spk/sonarr/src/service-setup.sh
Invalid relative references if application package is not installed
on same DSM volume than mono package.
Closes #3947
=> mono: replace relative references in applications

mk/spksrc.common.mk, mk/spksrc.spk.mk, toolchains/syno-purley-6.2.2/Makefile, toolchains/syno-purley-6.2.2/digests, toolchains/syno-x64-6.1/Makefile
_Motivation:_  The intel purley arch is not supported yet (introduced by model FS6400)
_Linked issues:_  #3949
- add purley to generic x64 archs
- reorder ARCHS_DUPES similar to x64 TC_ARCH
- add firmware to INFO too, when TC_OS_MIN_VER is specified
=> Add initial purley TC 6.2.2

cross/immutables/Makefile, cross/immutables/PLIST, cross/immutables/digests, spk/python3/Makefile, spk/python3/src/requirements.txt
Hi,
Not sure I'll be able to convince you that this is a good idea but it's worth a shot. Here I go.
I install [Flexget ](https://flexget.com/) on my Synology using a Python virtual environment. Unfortunately for me, recent versions of Flexget require [`immutables`](https://github.com/MagicStack/immutables) (via `contextvars`) which has C extensions. As I don't have any toolchain installed on the Synology and there are no precompiled wheels for `aaarch64` when it's time to install this dependency via `pip install` everything fails for obvious reasons.
Having this library distributed by Python3 would make my life much easier. Creating a symlink from the Python virtual environment to `@appstore/python3/lib/python3.6/site-packages/immutables` is enough to make `pip` happy and get the latest …
=> Compile and distribute immutables along with Python3

cross/dnscrypt-proxy/Makefile, cross/dnscrypt-proxy/digests, spk/dnscrypt-proxy/Makefile, spk/dnscrypt-proxy/src/service-setup.sh
_Motivation:_  I had someone on twitter contact me that the package did not work as intended on DSM and the DHCP setup as described in the wiki.
There was a unwanted space character in the string comparison and therefore did not execute  the correct instructions for the DSM.
=> dnscrypt-proxy hotfix for dsm and package update

.github/actions/build-push-pr.sh, .github/actions/build-tag.sh, .github/workflows/build.yml, .github/workflows/lint.yml
Automate Lint & Build on push to catch errors quickly. Other advantage is that people that fork the repo can easily create their own builds.
Thanks to @hgy59 for the dependency tree script: https://github.com/SynoCommunity/spksrc/pull/3854#issuecomment-573813380
=> Add Github Actions

mk/spksrc.common.mk, toolchains/syno-x64-6.1/Makefile
_Motivation:_  Add generic x64 support for intel geminilake arch
_Linked issues:_  #3999
- only generic x64 packages are supported until Synology provides the toolchains for geminilake archs.
=> Arch geminilake

.github/actions/build-push-pr.sh, .github/workflows/build.yml
By default actions/checkout only retrieves the latest commit. To calculate the diff we need the previous commit. I failed to catch this problem earlier.
_Linked issues:_  #3982
Here is a run with ffmpeg: https://github.com/publicarray/spksrc/actions/runs/119815811
=> Fix gh actions

.github/workflows/build.yml
Pull Requests use a github.sha set in the future
This time I've run tests on github.com https://github.com/publicarray/spksrc/pull/13
https://github.com/publicarray/spksrc/actions/runs/127595298
=> Framework: Github Actions - fix Pull Request runs

.github/actions/build-push-pr.sh, .github/actions/build_status.sh, .github/workflows/build.yml, Makefile
_Motivation:_  As we skip build errors in github actions, there is no error shown on build errors.
_Linked issues:_  #4018
- separate build of noarch and arch specific packages
- add Build Status job to report and fail on build errors
=> improve github actions

.github/actions/build_status.sh
_Motivation:_  When errors are being spotted the contents of the error file is not printed out
=> [github actions] Update build_status.sh to print out the proper error output file contents

cross/ntopng/Makefile, spk/ntopng/Makefile
_Motivation:_  Building `ntopng` only works from `/spksrc` root dir.  This fix addresses this.
_Linked issues:_  #4028
- Previous builds doesn't show support for PPC arches except `qoriq` - now forced as such.
- Makefile default `REQUIRED_DSM = 6.1` resulting in `armv7-1.2` to no be built
=> ntopng: build fix when using non /spksrc root dir

.github/actions/build-push-pr.sh, .github/actions/build_status.sh, .github/workflows/build.yml, mk/spksrc.common.mk, mk/spksrc.cross-cc.mk, mk/spksrc.cross-go.mk, mk/spksrc.install-resources.mk, mk/spksrc.native-cc.mk, mk/spksrc.pre-check.mk, mk/spksrc.spk.mk, spk/ntopng/Makefile
_Motivation:_  This is another step to improve github actions
_Linked issues:_  #4018
Remarks:
We ignore build errors in github build action to build all affected packages.
With the build status job, we force an error for effective build errors during the build job.
This PR introduces a file that contains the errors due to unsupported arch or unsupported TC Version.
Such errors are skipped now. i.e. are not handled as error in the build status job.
=> handle unsupported builds in github build action

cross/libbluray/Makefile, spk/tvheadend/Makefile
_Motivations:_  
Thnx to github action I was able to notice:
1. `ppc853x-5.2` build failure since latest `libbluray` version 1.2.0 update.  To fix requires `-D_GNU_SOURCE` C flag.
2. Also `tvheadend` never built against `ppc853x`.  Now marked as unsupported to limit false-positives on github-actions.
_Linked issues:_  #3965, #3998
=> ppc853x: libbluray fix and tvheadend marked as unsupported

.github/actions/build-push-pr.sh, .github/actions/build_status.sh, .github/workflows/build.yml
- avoid duplicate build artifacts (remove artifacts with arch name)
- limit artifact upload to builds without any error
=> limit space of github build artifacts

cross/sqlite/Makefile
_Motivation:_  Trying to access `www.sqlite.org` through http no longer works
_Linked issues:_  closes #4047
- ~~[ ] Build rule `all-supported` completed successfully~~
- ~~[ ] Package upgrade completed successfully~~
- ~~[ ] New installation of package completed successfully~~
=> cross/sqlite: http is no longer available

.github/actions/build_status.sh, .github/workflows/build.yml
_Motivation:_  Avoid the need of rebase to master to get only changed files on branch
- use diff with three dots to limit changed files to branch
=> [github-action] limit changed files for pull requests

mk/spksrc.cross-cmake-env.mk, mk/spksrc.cross-go-env.mk, spk/debian-chroot/Makefile, spk/gentoo-chroot/Makefile, spk/lirc/Makefile, spk/ntopng/Makefile
_Motivation:_  Avoid missing recognition of unsupported archs in github actions
- avoid make errors for unsupported archs
- remove make warning introduced with cmake rules #3998
=> improve recognition of unsupported archs

cross/libsodium/Makefile, mk/spksrc.download.mk
_Motivation:_  github build actions fail often to download sources
_Linked Issues:_ fixes build of #4066 
1. As SSL protocols <= TLSv1.1 are not supported by most sites nowadays and wget defaults to TLSv1.0 we need to force the use of TLSv1.2 for source downloads ([see reference](https://www.gnu.org/software/wget/manual/html_node/HTTPS-_0028SSL_002fTLS_0029-Options.html)).
This option is ignored for downloads with http protocol. Anyway a lot of download sites support https and should be updated in cross and native Makefiles.
2. The option to define `DOWNLOAD_ARGS` is removed, as it was used only to disable certificate check in cross/libsodium/Makefile with `DOWNLOAD_ARGS = --no-check-certificate`, and this is fixed with TLS 1.2.
=> force tls 1.2 for downloads with wget

mk/spksrc.cross-cmake-env.mk
_Motivation:_  Revert experimental cmake options introduced with #4066
_Linked issues:_  fixes #4091
=> fix cmake args for arm archs

spk/beets/Makefile
_Motivation:_  Following python3 update an intermediate version would need to be published for beets package
_Linked issues:_  Fixes partially #3944
=> beets: python3 upgrade followups

cross/ffmpeg/Makefile, cross/libbluray/Makefile, spk/ffmpeg/Makefile
_Motivation:_  Due to a misplaced `endif` it caused a few librairies to not be built as expected causing a `ffmpeg` failure.  This should really be a trivial fix.
_Linked issues:_  #4125
=> ffmpeg: Fix a build issue with libshine caused by endif

cross/borgbackup/patches/001-remove-useless-endianness-logic.patch
_Motivation:_  Fixing detection of endianness for cross compiled python in case of big endian architecture
_Linked issues:_  #3944 
This actually addresses two concerns:
* the `sys.byteorder` attribute seemed to be invalid (it turns out that this information is actually not valid, even when using `crossenv` since that attribute is actually hardcoded in the python executable itself)
* borgbackup was actually trying to do something clever depending on that attribute to pass flags which were actually already appropriately defined and provided by python headers
=> python3: fixed endianness detection for ppc853x architecture

cross/chromaprint/PLIST, spk/chromaprint/Makefile
_Motivation:_  Forgot to include the libraries into `PLIST` when switching to shared lib build.
_Linked issues:_  #4136
=> chromaprint: Fix using shared libraries

cross/python3/Makefile, spk/python3/Makefile
_Motivation:_  `curses` module was no longer shipped within Python 3's spk.
_Linked issues:_  Fixes #4152 
Algorithm used by python3's build process is to first look for `ncursesw` library which is, unfortunately, installed in build environment (at least on Docker). The issue, here, was that we were actually using the cross compiled version of `ncurses` which didn't include the expected functions. Hence the extension build failure.
=> python3: update to use ncursesw instead of ncurses

cross/libtorrent/Makefile, cross/libtorrent/PLIST, cross/libtorrent/digests, spk/deluge/Makefile
libtorrent now requires Boost chrono and random libraries
_Motivation:_  Requirement for deluge 2.03 deamon startup
_Linked issues:_  Fixes #4106
=> deluge: update libtorrent requirement to 1.1.14

native/go/Makefile, native/go/digests
_Motivation:_  Update go toolchain to latest release.
Includes a security bugfix in go1.14.8 and go1.15.1: security fixes for CVE-2020-24553 to the net/http/cgi and net/http/fcgi packages.
See https://github.com/golang/go/issues/41165 for details
=> go: updated to 1.15.2 (security update)

cross/nmap/Makefile
_Motivation:_  `cross/nmap` was no longer compiling
- ~~[ ] Build rule `all-supported` completed successfully~~
- ~~[ ] Package upgrade completed successfully~~
- ~~[ ] New installation of package completed successfully~~
=> cross/nmap: fix build

mk/spksrc.download.mk
_Motivation:_  One-liner fix to `spksrc.download.mk` for parallel build through `make -jX all-supported`
_Details:_ 
Using break stops the for loop but sends signal 1 which gets
interpreted by the Makefile as an error and stops.  Signal
needs to be 0 thus either using `echo > /dev/null` or better
using `continue` which simply complete the for loop with no
sleep.
=> spksrc.download.mk: Don't break, continue

mk/spksrc.download.mk
_Motivation:_  For loop should test for directory (`-d`) and lock file shouldn't be deleted for subsequent download using `flock`.
=> download.mk: Fix no.2 - test for directory and do not remove lock

spk/ffmpeg/Makefile
_Motivation:_  Version online is 4.2.4-34 and forgot to bump to `-35` the 4.3.1 version.  This causes a conflict online and refuse to publish updated packages.  Bumping the version accordingly.
=> ffmpeg: Forgot to bump spk package version - conflicting online

native/libmysqlclient/Makefile
_Motivation:_  `libmysqlclient` native fails to download the package.  Re-aligned the code against `cross/libmysqlclient` for file download and package naming.
_Linked issues:_  #4211 related to releasing `ntopng` updated package
=> native/libmysqlclient: Fix download URL to align against cross/*

spk/salt-minion/Makefile
_Motivation:_  salt-minion build on older arm5 and ppc arches is failing CI
_Linked issues:_  https://github.com/SynoCommunity/spksrc/pull/4153
=> salt-minion: declare arm5 ppc arch unsupported

spk/sabnzbd/src/requirements.txt
@ymartin59 I fixed it. I used `feedparser==6.0.0` when testing, but turns out it broke in `6.0.1` which I added quickly before creating PR, assuming nothing major changed..
=> Add sgmllib3k dependency for SABnzbd 3.1.0 feedparser

cross/autossh/Makefile, cross/he853/Makefile, cross/openssh/Makefile, cross/openssh/PLIST, cross/openssh/digests, cross/tcl/Makefile, diyspk/autossh/Makefile, spk/synocli-net/Makefile, spk/tcl/Makefile
_Motivation:_  Fix dependency issues reported in #4221
_Linked issues:_  #4250, closes #4221
- replace BUILD_DEPENDS by DEPENDS to fix shared library dependency errors that are mostly detected at runtime only.
- related packages: `synocli-net, tcl, he853 (HomeEasy)`
=> fix build dependencies

spk/sonarr/src/service-setup.sh
_Motivation:_  Explain here what the reason for the pull request is.
=> Add 88f6282 to archs needing mono workaround

cross/zsh/Makefile, spk/zsh-static/Makefile, spk/zsh/Makefile
_Motivation:_ zsh is not published with the recent archs (geminilake, v1000)
_Linked issues:_  fixes #4117 (when published)
=> update zsh revision

native/go/Makefile, native/go/digests
_Motivation:_ Update golang compiler to 1.15.5
Fixes multiple security issues: CVE-2020-28366, CVE-2020-28367, CVE-2020-28362
=> go: update to 1.15.5 (includes security fixes)

mk/spksrc.common.mk, mk/spksrc.python-wheel.mk
_Motivation:_  Since pip v20.3 the parameter -b is not supported anymore
_Linked issues:_  closes #4280
=> remove deprecated pip option -b

cross/autossh/Makefile, cross/openssh/Makefile, spk/synocli-net/Makefile
_Motivation:_  Output binary uses the `$(STAGING_INSTALL_PREFIX)` instead of $(INSTALL_PREFIX) leading to an non-existing path once installed when setting the `ac_cv_path_ssh` build parameter.
_Linked issues:_  #4250
=> Autossh fix ac_cv_path_ssh

Dockerfile
_Motivation:_  I am almost sure we will need `jq`  for DSM7 framework
- add jq for json with bash scripts
=> add jq to dev environment

cross/radarr/Makefile, cross/radarr/digests, spk/radarr/Makefile, spk/radarr/src/service-setup.sh
With the in app update to version 3.0.0.4204 of Radarr the Synology service startup reports the package launch as failed if updated. This PR corrects the PID file reference allowing the startup to report correctly in the Package Center as well as updates the build to the stable v3.0.0.4204
_Motivation:_  To update Radarr to v3 release and correct service startup on Synology
_Linked issues:_  Fixes issue https://github.com/SynoCommunity/spksrc/issues/3987 and issue https://github.com/SynoCommunity/spksrc/issues/4285, previously identified via https://github.com/SynoCommunity/spksrc/issues/3987#issuecomment-700010196
=> Update Radarr to v3

.vscode/settings.json
_Motivation:_  I've switched to [VSCode](https://code.visualstudio.com/) and excluding these files fixes a performance warning.
=> VSCode: Exclude folders from file watch

mk/spksrc.spk.mk
_Motivation:_  When debugging package compilation it is really useful to be able to only remove spk package creation files.
_Linked issues:_  None
=> spk.mk: Add a new spkclean option for package specific build files

Dockerfile, README.rst
_Motivation:_  Default Debian 10 `ninja` version is suitable for compiling environment requirement `mesa+ninja`
_Linked issues:_  #4307
=> framework: add ninja-build and fix Debian 10 manual installation doc

spk/homeassistant/Makefile, spk/homeassistant/src/requirements.txt
_Motivation:_  Unfortunately some integrations fail with recent package update
_Linked issues:_ #4341, closes #4343
Fixed integrations:
The google Nest integration does not work anymore due to cross compilation error (but works with v0.114.2-9) .
=> Fix homeassistant integrations

cross/erlang/Makefile
_Motivation:_  Seen error in github build action while building dependency-list
_Linked issues:_  followup of #4320
Solution for github build action error:
```
Building dependency list...
make[2]: *** No rule to make target 'dependency-flat'.  Stop.
make[1]: *** [../../mk/spksrc.dependency-tree.mk:31: dependency-flat] Error 2
```
=> fix cross/erlang/Makefile

mk/spksrc.cross-meson-env.mk, mk/spksrc.spk.mk
_Motivation:_  Revert error output introduced by #4348 
Any error thrown by make $(errror ...) breaks the dependency-list target.
`make dependency-list` is required by github build action. 
As fix error output is replaced by warning.
The target `all-supported` failed too. The pre-build of native dependencies must not call `make dependency-list`.
- use warning output instead of error to avoid failure with make dependency-list
- replace make dependency-list by depends variables to pre-build native dependencies
=> update meson build

cross/fdupes/Makefile, cross/pcre2/Makefile, cross/pcre2/PLIST, spk/synocli-file/Makefile
- fix fdupes dependencies in synocli-file
- always build libpcre2-32.so
- fix definition of PCRE2_CLI_FULL=1 (without export it was not available at copy-target)
_Motivation:_  fdupes and pcre2 tools have missing references
_Linked issues:_  closes #4353
=> synocli-file: fix pcre2 tools and fdupes

mk/spksrc.cross-meson-env.mk, mk/spksrc.dependency-tree.mk
_Motivation:_  Fix dependency-list target to allow error exit in Makefiles
_Linked issues:_  follow up of #4347, #4348 and #4349
Recover error handling for meson config file definition, that broke the github build action due to failures in `make dependency-list`
=> fix dependency targets

cross/libjpeg/digests
_Motivation:_  Build of spks depending on cross/libjpeg would no longer be passing
Basically the archives have changed.
Manually checked the difference between the two archived contents and it's XML resources which have been changed (fixed, really) inside.
[jpegsrc.v9c.tar.gz (old one)](https://github.com/SynoCommunity/spksrc/files/5789596/jpegsrc.v9c.tar.gz) vs 
[jpegsrc.v9c.tar.gz (new one)](https://github.com/SynoCommunity/spksrc/files/5789599/jpegsrc.v9c.tar.gz)
To be fair, another option could have been to ask was this file changed. But I must confess I don't know any of the contributors nor any of the owners so...
=> cross/libjpeg: archive contents were fixed

cross/libewf/Makefile, cross/libewf/digests
_Motivation:_  While working on https://github.com/SynoCommunity/spksrc/pull/4369 I noticed that the synocli-disk build was failing even without changes so I investigated and noticed that the libewf devs had removed their old releases (which were also all marked experimental). They did however provide new releases so I picked the most up to date release (no stable releases exist at all, so I had to take another experimental release) and bumped the libewf version to experimental-20201230 in order to fix the synocli-disk build
_Linked issues:_  Follow-up to (https://github.com/SynoCommunity/spksrc/pull/4364)
=> Bump libewf version to experimental-20201230 fixing synocli-disk build

spk/transmission/Makefile, spk/transmission/src/service-setup.sh, spk/transmission/src/wizard/install_uifile, spk/transmission/src/wizard/install_uifile_fre, spk/transmission/src/wizard/upgrade_uifile, spk/transmission/src/wizard/upgrade_uifile_fre
_Motivation:_  busybox shouldn't be required by transmission anymore as it was only used in dsm6 to get rid of legacy accounts and groups.
_Linked issues:_  Follow-up to (https://github.com/SynoCommunity/spksrc/pull/4364)
=> Remove busybox from transmission deps

mk/spksrc.cross-meson-env.mk
_Motivation:_  Solves building using meson environment.  Fix a merge conflicting changes between #4356 and #4349
_Linked issues:_  #4379
=> cross-meson.mk: Fix build issue - conflict commits #4356 #4349

cross/libicu/Makefile, cross/libicu/patches/armv7l/001-max_align_t.patch, native/libicu/Makefile, spk/znc/Makefile
_Motivation:_  `znc` spk package (depending on Python) wasn't building on "standard" architecture `hi3535`
=> libicu: fix build on hi3535 architecture

cross/tvheadend/Makefile
_Motivation:_  Trying to remove `native/python` dependency in order to free-up from python2
_Linked issues:_   #4303
=> tvheadend: Remove native/python dependency

mk/spksrc.service.mk
-a executes both left and right hand expressions.
When $SYNOPKG_DSM_VERSION_MAJOR is empty it shows a warning since "" is not an integer and evaluates to false.
Test case (as root):
```
root@dsm6 ~# /bin/sh /var/packages/transmission/scripts/service-setup log
/var/packages/transmission/scripts/service-setup: line 7: [: : integer expression expected
root@dsm6 ~# synopkg log transmission
The log file is /volume1/@appstore/transmission/var/transmission_temp.log
```
=> fix line 8: [: : integer expression expected

cross/cffi/Makefile, cross/numpy/Makefile, cross/numpy/patches/x64/001-fix-auto-detection-of-avx-512f-intrinsics.patch, cross/poetry/Makefile, spk/homeassistant/Makefile
_Motivation:_  I need numpy as a non optional dependency on another spk (namely bazarr).
This was fixed on the 20.x branch of numpy but hasn't been backported. I only picked it up manually (with minor adaptations).
Additionally some python wheel builds weren't working properly because of a lack of "build isolation" enforcement.
=> cross/numpy: fixed auto detection of avx-512f intrinsics

mk/spksrc.kernel.mk
_Motivation:_  `mrproper` needs to be ran after certain specific adjustments are made when done in cross/ or spk/* directory tree.
_Linked issues:_  #4399
=> kernel.mk: Forgot to reverse the logic for in package builds

mk/spksrc.kernel.mk
_Motivation:_  As kernels are now built into the spk/* package tree it requires a COOKIE_PREFIX for various mk execution output.
_Linked issues:_  #4399
=> kernel.mk: Set COOKIE_PREFIX for kernel builds

mk/spksrc.common.mk
_Motivation:_  Allows us to compare version strings in makefiles
_Linked issues:_ 
https://github.com/publicarray/spksrc/commit/50cf722677116ebff76f10dad1cd0bd8a3e1772b#commitcomment-46543476 
https://github.com/SynoCommunity/spksrc/pull/4395#discussion_r564971107
=> Framework: add version compare functions

cross/radarr/Makefile, cross/radarr/digests, spk/radarr/Makefile
_Motivation:_  To incorporate latest Radarr release code. Includes a fix to backup v0.2 DB as part of upgrade if it exists.
=> Update Radarr to v3.0.1.4259

cross/lidarr/Makefile, cross/lidarr/digests, spk/lidarr/Makefile, spk/lidarr/src/service-setup.sh
_Motivation:_  The in-app update to v0.8.0.2041 caused a startup issue. This amended PR is to move to v0.8.0.2042 which addresses this critical issue and re-base the package at the new version
_Linked issues:_  Resolves issue https://github.com/SynoCommunity/spksrc/issues/4409
=> Update Lidarr to v0.8.0.2042

cross/openssl/Makefile, cross/openssl/digests
_Motivation:_  Update OpenSSL to 1.1.1j (Security Updates of 16 Feb 2021)
=> update openssl to v1.1.1j

cross/erlang/Makefile
@DigitalBox98  you were right, there was a wrong erlang download location (in cross/erlang/Makefile).
=> fix erlang download link

Dockerfile
_Motivation:_  docker build fails due to pip changing the URL after a major version change
_Linked issues:_  #4422
=> Docker: fix new pip url

mk/spksrc.spk.mk
_Motivation:_  Build of spk packages without wizard fail for DSM < 7
_Linked issues:_  Followup of #4395
=> fix builds for DSM<7 without wizard files

native/python2/Makefile
_Motivation:_  make python2 compile again
_Linked issues:_  #4488
=> fix download url for pip of python 2.7

cross/sqlite/Makefile
_Motivation:_  Pretty sure sqlite shouldn't depend on speex.  Speeds up build of packages depending on sqlite a little.
=> Remove dependency of sqlite on speex (an audio codec)

mk/spksrc.spk.mk, spk/demoservice/PLIST
_Motivation:_  Finally fix wizard creation broken by #4395
_Linked issues:_  fixes #4489
- Fix missing wizards in packages introduced with #4489
- This is a working solution for packages without wizards as expected by #4489
- The solution of #4489 did not work, as the copied files where not detected with `ifneq ($(wildcard $(DSM_WIZARDS_DIR)/.*),)` and therefore not included in the package. (but a second build without `make clean` created the package with the wizard files - so it was hard to detect the error).
The solution uses duplicated statements as there is no solution found for logical OR conditions.
=> fix wizard creation

cross/libstdc++/Makefile
_Motivation:_  Not sure if this is needed. Only .NET packages rely on it at the moment.
=> libstdc++ add more architecture support

cross/sonarr/Makefile, cross/sonarr/PLIST, cross/sonarr/digests, mk/spksrc.spk.mk, spk/sonarr/Makefile, spk/sonarr/src/service-setup.sh, spk/sonarr/src/wizard/upgrade_uifile, spk/sonarr/src/wizard/upgrade_uifile_fre
⚠ To see which version you need: https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model 
⚠ Models that have `(x64)` listed on the wiki page should use the general x64 testing package.
I just did a successful upgrade from Sonarr v2 to this package (v3) with no issues. It would be great to get a few experienced users to test and share their success/results going from v2 to v3 with this package. @Safihre can you make packages for people to test with? Thank you!
_Motivation:_  To add a v3 Sonarr package
_Reference:_  https://github.com/SynoCommunity/spksrc/pull/3518#issuecomment-552331259
=> Update Sonarr to v3

mk/spksrc.cross-env.mk
_Motivation:_  Was missing from previous merged PR: 
- Export REQUIRE_KERNEL_MODULE to default ENV
- Fix KERNEL_ROOT to point to $(WORK_DIR)/linux
_Linked issues:_  #4526
=> kernel.mk: Missed cross-env kernel variable fix.

mk/spksrc.patch.mk
_Motivation:_  While helping on Fishell PR #4494 a patch for all `arm` arches would have been useful.  This PR aims to allow this.  Note that there is now a sort to remove any duplicate entries as looping over `ARM_ARCHS` creates duplicate entries from other `ARMvX_ARCHS` afterwards.
=> patch.mk: Add ARM_ARCHS group allowing patches/arm generic patches

mk/spksrc.service.mk
_Motivation:_  On DSM6 with latest update for DSM7 it creates, by default, a `conf/privilege` file while previous behavior did not.  Proposed patch revert back to this behavior on DSM <= 7.
_Linked issues:_  #4533 4533
=> DSM6: Keep previous behaviour and assume no file by default

mk/spksrc.service.start-stop-daemon, mk/spksrc.service.start-stop-status
_Motivation:_  Patch SYNOPKG_PKGVAR so it's available in older DSM versions.
_Linked issues:_  https://github.com/SynoCommunity/spksrc/pull/4545#issuecomment-818832332
=> Add $SYNOPKG_PKGVAR backwards compatibility to start-stop-status

mk/spksrc.service.installer.dsm7
_Motivation:_  Revert a breaking change of #4539
- revert overwriting files in ${SYNOPKG_PKGVAR} folder from target/var (introduced with #4539)
_Reference:_ [comment on spksrc.service.installer.dsm7 in  #4539](https://github.com/SynoCommunity/spksrc/commit/0eaccc5f0a45bfa91b505f7ed9750c987128c235?branch=0eaccc5f0a45bfa91b505f7ed9750c987128c235&diff=split#r49449742)
As linking into the merged PR is not very good, here is the comment of @publicarray 
> Dang I missed it, why change it? This is a regression or please let me explain how it was supposed to work.
> 
> DSM7:
> 
> `${SYNOPKG_PKGDEST}/var` => /var/packages/{package}/target/var
> `${SYNOPKG_PKGVAR}` => /var/packages/{package}/var
> 
> DSM6:
> `${SYNOPKG_PKGDEST}/var` => /var/packages/{package}/target/var
> `${SYNOPKG_PKGVAR}` => …
=> DSM7: revert var overwrite

cross/openssl/Makefile, cross/openssl/digests
_Motivation:_  OpenSSL version bump to 1.1.1k
_Linked issues:_  https://github.com/SynoCommunity/spksrc/pull/4541#
=> OpenSSL version bump to 1.1.1k

cross/expat/Makefile, cross/expat/PLIST, cross/expat/digests
_Motivation:_  I noticed in another pull request that the GitHub Actions build was failing because a package could not download `expat` v2.2.7. On the project website (https://sourceforge.net/projects/expat/files/expat/2.2.7/) I found that version of `expat` had been taken down because it has a vulnerability. In this PR I upgrade the version to the recommended v2.3.0.
N.B. I do not know if upgrading `expat` will cause any other issues for packages that depend on it.
=> Update expat to avoid vulnerable version

mk/spksrc.spk.mk
_Motivation:_  When providing kernel module packages we must not alow it to run on newer DSM versions.  Only acceptable point releases which equal to `<10` increase on build number such as:
* **COMPATIBLE**: Package built for DSM-6.2.3 = `6.2-25423` and point releases DSM-6.2.3 Update 3 = `6.2-25426`
* **INCOMPATIBLE:** Package built for DSM-6.2.3 = `6.2-25423` while DSM-6.2.4 = `6.2-25556`
_Linked issues:_  #4420, #4144
=> spk.mk: Limit os_max_ver to point release updates for kernel spk

cross/libstdc++/Makefile, cross/lidarr/Makefile, cross/radarr/Makefile, mk/spksrc.download.mk, mk/spksrc.generate-digests.mk, mk/spksrc.install-resources.mk
_Motivation:_  The previous solution was not handy and has duplicated code.
_Linked issues:_  #4566
###Remarks
Now a single `make digests` call works for packages with and without multiple source files to create the `digests` file.
=> generic solution for multifile digests (followup of #4566)

.github/actions/build.sh
_Motivation:_  spk/python folder was renamed to spk/python2 but package name is still python, so this little extra handling is required
_Linked issues:_  followup of #4406
The dependency resolver in the github build action needs extra handling for all packages with a folder name that does not match the package name (sonarr->nzbget, python2->python).
=> GH Action: fix build dependencies for python2

Dockerfile, README.rst, mk/spksrc.extract.mk
Some of the synology toolchain tarballs contain permissions that will make
extraction fail on MacOS Docker Host machines. Details are in #3570.
A simple fix for this issue is prepending the tar command with the
fakeroot command.
_Linked issues_: Fixes #3570, fixes #3523, closes #3524, #3428, fixes #3791
=> Wrap tar calls using fakeroot

Dockerfile
autoconf-archive is required to build python >= 3.8.9
=> add autoconf-archive to docker image

cross/lua/Makefile, cross/lua/PLIST, cross/lua/digests, spk/lua/Makefile
_Motivation:_  Pure CLI tools are now ready for DSM7
_Linked issues:_  #4524
=> update lua to v5.4.3

spk/flexget/Makefile, spk/flexget/src/requirements.txt
_Motivation:_  Another flexget update to avoid security issue with urllib3
=> update flexget to v3.1.117

cross/zlib/Makefile
_Motivation:_  packages with meson-build cannot link to libz.so
_Linked issues:_  closes #4478
fixed packages: rmlint, zstd
A lot of packages depend on cross/zlib and/or cross/glib. To ensure those are no affected, I checked some:
=> fix zlib-so-linking with meson-build (#4478)

cross/ruby/Makefile, spk/ruby/Makefile
_Motivation:_  Ruby package does not support OLD_PPC_ARCHS 
_Linked issues:_ #4352
Ruby compiles for OLD_PPC_ARCHS with older cross/gdbm, but crashes at runtime.
=> ruby: declare old_ppc_archs as unsupported

cross/etherwake/Makefile, cross/etherwake/PLIST, cross/etherwake/digests, cross/etherwake/patches/001-create-Makefile.patch, cross/etherwake/patches/002-rename-binary.patch, diyspk/etherwake/Makefile, spk/synocli-net/Makefile
_Motivation:_  Add etherwake 
_Linked issues:_  closes #3602
=> synocli-net: add etherwake

mk/spksrc.service.mk
_Motivation:_  Revert the definition of shared folder resources for DSM6
_Linked issues:_  fixes #4653
- shared folder resource must be defined by a folder name only (and not an absolute path like /volume1/downloads)
- without a redesign of installation wizards it is not possible to use resource file for shared folder
=> avoid shared folder resource for DSM6

spk/nzbget/Makefile, spk/nzbget/src/service-setup.sh
_Motivation:_  Some cleanup to get new package version to publish for new archs
_Linked issues:_  closes #4631
- remove dsm5 -> dsm6 migration
- remove busybox dependency
- not compatible with DSM7 yet (still missing shared folders from wizard for DSM7).
=> Update nzbget to support new archs

cross/libtorrent/Makefile
_Motivation:_  deluge fails to install on armada370 based diskstations and was not yet published with current openssl (v1.1.x)
_Linked issues:_  closes #4516
Just a build on the current master fixed the installtion on my DS115j.
The package size shrinks by > 50% by removing the full python2 code from the package.
As the deluge package is built on the fly at installation, on my DS115j the installation needed > 30 minutes to complete (256 MB RAM)
This package is not ready for DSM7, as there is no solution for shared folders by wizard variables yet.
=> prepare deluge for publish

mk/spksrc.service.installer.dsm5, mk/spksrc.service.installer.dsm6, mk/spksrc.service.mk
_Motivation:_  Avoid DSM5 and DSM6 user definitions for DSM7
`USER` and `EFF_USER` must only be set when `SERVICE_USER` is defined in Makefile.
And replace such code in service-setup:
```
USER="{package-name}"
PRIV_PREFIX=sc-
SYNOUSER_PREFIX=svc-
if [ -n "${SYNOPKG_DSM_VERSION_MAJOR}" ] && [ "${SYNOPKG_DSM_VERSION_MAJOR}" -lt 6 ]; then EFF_USER="${SYNOUSER_PREFIX}${USER}"; else EFF_USER="${PRIV_PREFIX}${USER}"; fi
```
for DSM7 to:
```
USER="sc-{package-name}"
EFF_USER="sc-{package-name}"
```
=> Fix dsm7 service setup

cross/uriparser/Makefile, cross/uriparser/PLIST, cross/uriparser/digests
_Motivation:_  Version 0.91 declared buggy, need to update to newer version AND migrate to using `cmake`
_Linked issues:_  #4681
=> uriparser: Update from broken 0.91 to version 0.95 and use cmake

cross/tvheadend/PLIST, cross/zap2epg/Makefile, cross/zap2epg/PLIST, cross/zap2epg/digests, spk/tvheadend/Makefile, spk/tvheadend/PLIST, spk/tvheadend/src/requirements.txt, spk/tvheadend/src/service-setup.sh
_Motivation:_  TVH lacks of built-in TV grabber as the XMLTV project is pretty much all using perl with target compiled CPAN modules making cross-build not sustainable with the framework.  Changes in this PR incorporate zap2epg python EPG grabber directly to TVH.  This allows using built-in routine tasks from TVH without needing additional cron jobs.
_Linked issues:_  Superseeds previous `zap2it` standalone package #4608 and include `requests` python wheels which closes #4678
- Currently pending the merge upstream of https://github.com/edit4ever/script.module.zap2epg/pull/37
=> [WIP] Add zap2epg TV grabber to tvheadend

cross/zap2epg/Makefile, cross/zap2epg/digests
_Motivation:_  Fix digests by using latest git hash and add @hgy59 comments from https://github.com/SynoCommunity/spksrc/pull/4680#pullrequestreview-687843261
_Linked issues:_  #4680
=> Zap2epg fixes

cross/cppunit/Makefile
_Motivation:_  Does not build on DSM7 otherwise.  Fix imported from `libicu`
_Linked issues:_  https://github.com/SynoCommunity/spksrc/pull/4576/checks?check_run_id=2867078521
=> cppunit: DSM7 build usual C99 fix

spk/chromaprint/Makefile, spk/comskip/Makefile, spk/ffmpeg/Makefile, spk/tvheadend/Makefile
_Motivation:_  Prepare for releasing official packages for `ffmpeg`, `tvheadend`, `chromaprint`, `comskip`
_Linked issues:_  #4686, #4576, #4680, #4545
=> ffmpeg+chromaprint+comskip+tvheadend: Version bump for release

.gitignore, Makefile, mk/spksrc.common.mk, mk/spksrc.download.mk, mk/spksrc.spk.mk
_Motivation:_  As we progress into supporting DSM7 and as a perquisite to building recently merged PR, I want to be able to build both officially supported DSM in one shot using the regular `make all-supported`.  Also, downloading of distrib package files is still an issue with current code.  This PR is attempt to fix both issues:
a) allowing multi DSM builds and
b) fix parallel build download issue
c) fix parallel build of native/*
d) output individual `build-` log files for better tracking of each arch build
_Linked issues:_  
```
$ make setup
Creating local configuration "local.mk"...
Setting default toolchain version to DSM-6.1
Setting default toolchain version to DSM-7.0
```
That leads into the following after `make all-supported`:
```
$ tree ffmpeg -L 1
ffmpeg
├── …
```
=> spksrc: Allow multiple DSM for all-supported

mk/spksrc.spk.mk
_Motivation:_  I made an error when trying to add file descriptor locking against `native` compiling for parallel builds.  The reason I had first hit the issue is that the native build hook wasn't properly being handled in the first place.  Code change removes the `flock` and call-up `$(MAKE) dependency-list` instead to generate full dependency list.  It looks for `native`, builds them and then move on to the parallel building of all archs to be processed.
_Linked issues:_  #4689
=> spk.mk: Fix native compile for parallel builds

cross/ruby/Makefile, cross/ruby/digests, native/ruby/Makefile, native/ruby/digests, spk/ruby/Makefile
_Motivation:_  Another cli package ready for DSM7
=> Ruby: Update to v3.0.1

Makefile
Spaces where added at some point in local.mk. Why?
_Motivation:_  This is needed for GitHub actions, specifically when using it to publish: https://github.com/SynoCommunity/spksrc/pull/4491/files.
=> Fix setup-synocommunity command

mk/spksrc.service.mk
Using ﻿jq would override the field incorrectly if the length of `SPK_GROUP` was shorter than
`sc-$(SPK_USER)`. Parts of the old value would still be present in the output
This is an issue with using `$@ 1<>$@` to write and read from the same file and value
_Motivation:_  Explain here what the reason for the pull request is.
=> fix SPK_GROUP

cross/znc/Makefile, cross/znc/PLIST, cross/znc/modules/clientbuffer.cpp, cross/znc/modules/palaver.cpp, cross/znc/modules/push.cpp, spk/znc/Makefile, spk/znc/src/service-setup.sh
_Motivation:_  A very usefull module who is still absent in the actual version of ZNC
_Linked issues:_  closes #4279
I saw that the makefile for ZNC compile all the cpp files who are present in module dir so I just have to add the .cpp file for client buffer in /modules dir and add clientbuffer.so in the PLIST file. All compilation are done and .spk packages can be found here: https://github.com/jaloji/spksrc/releases/tag/1.8.2-17
For each new updates of ZNC all the module must be recompiled with the new version.
=> Add clientbuffer module to znc

Dockerfile, README.rst
_Motivation:_  The development environment needs sponge command to use `jq` for in place modification.
_Linked issues:_  required by #4781, #4693
- add moreutils for sponge command
- add sudo to use docker image as regular user
This is a precondition to install native packages from repository as proposed in #4693.
=> update deveopment environment

.github/workflows/docker.yml, Dockerfile
For Docker Hub the secrets need to be added to GitHub: `DOCKERHUB_USERNAME` `DOCKERHUB_TOKEN`. If docker hub is not required I can remove it. The image/package would be still be build and uploaded onto GitHub. (packages are found here https://github.com/orgs/SynoCommunity/packages?repo_name=spksrc)
=> Build docker image using github actions

mk/spksrc.service.mk
_Motivation:_   jq does not create valid json when username is already set
_Linked issues:_  This error popped up with the publish of #4602 
With already set `"username": "USER"` jq appends an `}` at the end of the privilege file and thus makes it invalid.
=> fix package user in privilege file

mk/spksrc.cross-dotnet-env.mk, spk/jellyfin/Makefile, spk/radarr/Makefile
https://github.com/SynoCommunity/spksrc/issues/4790
https://github.com/SynoCommunity/spksrc/issues/4546
https://github.com/publicarray/spksrc/issues/28
https://github.com/dotnet/runtime/issues/56706
=> dotnet: mark armadaxp and alpine as unsupported

.github/actions/build-tag.sh, .github/actions/build.sh, .github/actions/build_status.sh, .github/workflows/build.yml, mk/spksrc.spk.mk
_Motivation:_  Fixes `local.mk` with spaces. It makes it much easier to find the error line in a long log file. No more grepping or hunting for it. And this PR allows us to build any package on demand manually.
Here is an example build: https://github.com/publicarray/spksrc/runs/3432175214?check_suite_focus=true
And the output:
```
BUILD STATUS
SUCCESS:
none.
UNSUPPORTED (skipped):
none.
Error: ERRORS:
2021.08.26 11:37:20 - squidguard: (x64-7.0) FAILED
See log file of the build job to analyze the error(s).
Last 15 lines of the build log:
$ make TCVERSION=7.0 ARCH=x64 -C ./spk/squidguard
make[2]: Leaving directory '/github/workspace/spk/squidguard/work-x64-7.0/unrar'
find /github/workspace/spk/squidguard/work-x64-7.0/install//usr/local/squidguard/ \! -type d -printf '%P\n' | sort | \
diff …
```
=> CI: fix parallel builds. Add manual builds and print more details on error

spk/rabbitmq/src/service-setup.sh
_Motivation:_  recent update of rabbitmq did not work on DSM-5
_Linked issues:_  fixes #4806
=> rabbitmq: fix setup for dsm5

cross/openssl/Makefile, cross/openssl/digests
_Motivation:_   Fixes for CVE-2021-3711 [High severity] and CVE-2021-3712 [Moderate severity]
_Linked issues:_  https://github.com/SynoCommunity/spksrc/issues/4211#issuecomment-907757166, #4820
- borgbackup
- boxbackup-client
- deluge
- domoticz
- duplicity
- ejabberd
- erlang
- ffmpeg
- ffsync
- flexget
- fossil-scm
- git
- haproxy
- homeassistant
- icecast
- irssi
- itools
- jackett
- memcached
- mercurial
- monit
- mosh
- mosquitto
- mtproxy
- mutt
- ntopng
- octoprint
- python
- python3
- python38
- rdiff-backup
- ruby
- rutorrent
- sabnzbd
- salt-minion
- shairport-sync
- stunnel
- synocli-disk
- synocli-file
- synocli-monitor
- synocli-net
- transmission
- tvheadend
- umurmur
- vim
- znc
=> update openssl to v1.1.1l

mk/spksrc.cross-dotnet-env.mk, spk/jellyfin/Makefile, spk/radarr/Makefile
Reverts SynoCommunity/spksrc#4793
Thanks @AnonTester So  one .NET app leads to Invalid Instruction on one CPU and the other one on a  different CPU? I give up. I'll just mark it in the wiki pages. Maybe a future .NET / jellyfin / radarr update magically fixes it. 
https://github.com/SynoCommunity/spksrc/issues/4546#issuecomment-906818900
=> Revert "dotnet: mark armadaxp and alpine as unsupported"

mk/spksrc.service.mk
It was a beta thing and never worked correctly, or more likely I did not know how it was supposed to work.
`SPK_GROUP` was never used (proof with `rg -g 'spk/**/Makefile' 'SPK_GROUP'` ) and should be `GROUP` anyway e.g. `sc-download` 
Files will have `$username:$groupname` as the package file owners.
Relates to conversation here: https://github.com/SynoCommunity/spksrc/issues/4524#issuecomment-877112301
starts around: https://github.com/SynoCommunity/spksrc/issues/4524#issuecomment-871166899 and https://github.com/SynoCommunity/spksrc/issues/4524#issuecomment-869634575
=> DSM7: Set synocommunity as the default group

mk/spksrc.common.mk, mk/spksrc.compile.mk
_Motivation:_  
1. PSTAT_LOG value is not redirected to the proper directory when ran outside of `spk/*` or `cross/*` for native, toolchain or other directories.  The following captures the parent pid to try to figure out where the "real" working directory is, and thus send PSTAT_LOG output always at the right place.
2. It now also shows the arch as being native, toolchain, toolkit, etc... when ran outside of `spk/*` or `cross/*`
_Linked issues:_  Follow-up to #4859
=> common.mk: Fix PSTAT_LOG value when not in cross/* or spk/*

.github/actions/build.sh, .github/actions/download.sh, .github/actions/prepare.sh, .github/workflows/build.yml
_Motivation:_  Try to cache downloaded files in digests folder for faster run of github build action
_Linked issues:_  https://github.com/SynoCommunity/spksrc/pull/4866#issuecomment-922116351
This gives some improvements for the github build action, as the dependency-list is created only once in the prepare job and not for the download and every build job again.
The download job downloads all referenced source files and add those to the cache for the current workflow.
And the build jobs use the source files in distrib folder from that cache.
=> add github download action

cross/ffmpeg/Makefile
_Motivation:_  Add support for DASH Demuxing
_Linked issues:_  #4639
=> ffmpeg: Add dash demuxer support (requires libxml2)

cross/ripgrep/Makefile, spk/synocli-file/Makefile
When building synocli-file the dependencies from other packages include
PCRE2 and contaminate the build for ripgrep. The lib was found and
dynamically linked. Setting PCRE2_SYS_STATIC=1 ensures static linking
>Enabling the PCRE2 feature works with a stable Rust compiler and will attempt to automatically find and link with your system's PCRE2 library via pkg-config. If one doesn't exist, then ripgrep will build PCRE2 from source using your system's C compiler and then statically link it into the final executable. Static linking can be forced even when there is an available PCRE2 system library by either building ripgrep with the MUSL target or by setting PCRE2_SYS_STATIC=1.
From https://github.com/BurntSushi/ripgrep#building
_Linked issues:_  #4878
=> Fix ripgrep #4878

cross/bat/Makefile, cross/bat/PLIST, cross/bat/digests, cross/exa/Makefile, cross/exa/PLIST, cross/exa/digests, cross/zlib-ng/Makefile, cross/zlib-ng/PLIST, cross/zlib-ng/digests, diyspk/bat/Makefile, diyspk/exa/Makefile, mk/spksrc.cross-rust.mk, spk/synocli-file/Makefile
_Motivation:_  add rust tools 'bat' (#4877) and 'exa' (#4876)
_Linked issues:_  closes #4876, closes #4877, #4820
=> synocli-file: add rust tools 'bat' and 'exa'

cross/jellyfin-web/Makefile, cross/jellyfin-web/digests, cross/jellyfin/Makefile, cross/jellyfin/digests, spk/jellyfin/Makefile
_Motivation:_  Update jellyfin to 10.7.7
=> Update jellyfin 10.7.7

cross/berkeleydb/Makefile, cross/ruby/Makefile, cross/ruby/digests, native/ruby/Makefile, native/ruby/digests, spk/ruby/Makefile
_Motivation:_  Another package that needs openssl update
_Linked issues:_   #4820
=> ruby: update to v3.0.2

spk/python310/Makefile
_Motivation:_  While updating from 3.9 to 3.10 this got lost in translation...
_Linked issues:_  #4937
=> python310: Fix display name

spk/sickchill/src/requirements.txt
Continuation from https://github.com/SynoCommunity/spksrc/pull/4920#issuecomment-961795426
fixes:
```
2021/11/05 17:45:12	ERROR: Cannot install cloudscraper==1.2.58, httplib2==0.20.2, packaging==21.2 and pyparsing 3.0.4 (from /volume1/@appstore/sickchill/share/wheelhouse/pyparsing-3.0.4-py3-none-any.whl) because these package versions have conflicting dependencies.
2021/11/05 17:45:12	The conflict is caused by:
2021/11/05 17:45:12	    The user requested pyparsing 3.0.4 (from /volume1/@appstore/sickchill/share/wheelhouse/pyparsing-3.0.4-py3-none-any.whl)
2021/11/05 17:45:12	    cloudscraper 1.2.58 depends on pyparsing>=2.4.7
2021/11/05 17:45:12	    httplib2 0.20.2 depends on pyparsing!=3.0.0, !=3.0.1, !=3.0.2, !=3.0.3, <4 and >=2.4.2; python_version > "3.0"
2021/11/05 17:45:12 …
```
=> Sickchill: Followup

cross/libsodium/digests, native/yasm/Makefile
See: https://github.com/SynoCommunity/spksrc/pull/4951#discussion_r746493700
Just in-case the cert expires again
=> native/yasm: use github release & cross/libsodium: update digests

cross/libsodium/Makefile, cross/libsodium/digests
libsodium `-stable` is a moving target: https://github.com/SynoCommunity/spksrc/pull/4963#issuecomment-966669734
=> move libsodium to point releases

mk/spksrc.pre-check.mk, spk/debian-chroot/BROKEN, spk/pyload/BROKEN
_Motivation:_  Extracting trivial build fixes from #4797 to keep only things in scope of that rather large PR.  This patchset enforce package to compliance to DSM7 and allow marking packages as BROKEN.
1. Packages still using non-standard setup script (e.g. `src/installer.sh`) dates from pre-DSM6 and should be marked as incompatible with DSM7 to avoid building it and provide clean github-action outputs.  This is done by checking if the package is making use of the `INSTALLER_SCRIPT` such as `INSTALLER_SCRIPT = src/installer.sh`.  This necessarily means that it hasn't been migrated to DSM6+ default framework method using `SERVICE_SETUP = src/service-setup.sh`.  As such there is not value at trying to build them for DSM7 and are being excluded from the build process, thus reducing time to …
=> Comply to DSM7 and set as broken

mk/spksrc.wheel-env.mk, spk/python310/Makefile, spk/python310/src/requirements-crossenv.txt
_Motivation:_  With the redesign wheels no longer uses `none-any` suffix but rather the mathing `uname -m` of the NAS architecture machine name.  This PR address some of the shortfalls where wheels have extra arguments in their platform tag that needs to be reworked.
_Linked issues:_  #4980 and https://github.com/SickChill/SickChill/issues/7672#issuecomment-980395077
=> [WIP] Wheel name fix

mk/spksrc.service.mk, mk/spksrc.spk.mk
Create `config` file with same id as `INFO` file.
_Motivation:_  DSM7 notification not working as INFO file of package and config file are not aligned in naming convention.
_Linked issues:_  [https://github.com/SickChill/SickChill/issues/7694#issuecomment-986926967](https://github.com/SickChill/SickChill/issues/7694#issuecomment-986926967)
Thus `synodsmnotify` even if strings were configured correctly would not resolve their i18n text strings.
@th0ma7 I don't know the knock on effects of this modification to other parts of the build. Also the other choice may be to modify the `spksrc.spk.mk` file lines 204 to 206 to change the INFO file instead.
=> INFO and config alignment spksrc.service.mk

mk/spksrc.service.installer.dsm7, mk/spksrc.service.installer.functions, spk/demoservice/Makefile, spk/demoservice/PLIST
_Motivation:_  Extract from #4797 in order to enable usage of `rsync` instead of copy.  Updated method is such as:
1. uses a dedicated function to synchronize `target/var` to `target/../var`
2. allow providing updated `var` configuration files without overwriting existing (e.g. uses `.new` suffix)
3. allow upgrading DSM6 `var` data to DSM7 at pre/postupgrade using temporary storage
_Linked issues:_  #4797
=> installer.dsm7: Use rsync to synchronize var directory

mk/spksrc.common.mk
_Motivation:_  Default `sh` under make is limited and PR such as #4971 requires more extensive shell functionalities.
_Linked issues:_  #4971
=> common.mk: Allow more extensive Bash shell environment

spk/homeassistant/src/requirements-crossenv.txt, spk/sabnzbd/src/requirements-crossenv.txt
_Motivation:_  Rename requirement entries to match strict Pypi naming
_Linked issues:_  #4971
=> Rename requirement entries to match strict Pypi naming

spk/beets/src/requirements-crossenv.txt
_Motivation:_  With latest python310 update beets requirements versions where not enforced using `==`.  This address this using strict enforcing.
_Linked issues:_  #4971
=> beets: Enforce strict requirement versions

mk/spksrc.wheel.mk
_Motivation:_  The cat python-cc.mk + eval ends-up producing the following error:
```
/bin/bash: line 0: .: filename argument required
.: usage: . filename [arguments]
```
There probably is another workaround but in the meantime this fixes it.
=> wheel.mk: Use default sheel to fix makefile eval

spk/nzbget/Makefile, spk/nzbget/src/service-setup.sh, spk/nzbget/src/wizard/install_uifile, spk/nzbget/src/wizard/install_uifile_fre, spk/nzbget/src/wizard/upgrade_uifile, spk/nzbget/src/wizard/upgrade_uifile_fre
_Motivation:_  This package needs update for shared folder creation for DSM 7
_Linked issues:_  probably fixes #4814, #4765, #4524. closes #4304, #4271
https://github.com/SynoCommunity/spksrc/issues/4524#issuecomment-983288508
https://github.com/SynoCommunity/spksrc/issues/4524#issuecomment-990796764
We still have to solve permission issues...
=> NZBget: update package for DSM 7

mk/spksrc.service.installer.dsm6
_Motivation:_  output of service_restore function is not added to linterller log on DSM 6
@th0ma7 thanks for the hint
=> fix dsm 6 installer log

mk/spksrc.common.mk
_Motivation:_  PR #5007 breaks the INFO file generation
_Linked issues:_  revert #5007
=> fix descriptions in INFO file

mk/spksrc.copy.mk, mk/spksrc.plist.mk
_Motivation:_  packages with files that have spaces in name can't be built.
_Linked issues:_  
Found this errors while working on a package for `Ombi` that contains a file `logo original.png`.
Got two errors:
- copy_target that uses tar failed
- When using PLIST.auto there are other errors
As latest stable ombi is still on .NET 5 and current versions with .NET 6 are prerelease (and didn't run), I want to publish this fix now.
=> fix PLIST for filenames with spaces

cross/pillow/Makefile, cross/pillow/digests, spk/beets/Makefile, spk/beets/src/requirements-cross.txt, spk/beets/src/requirements-crossenv.txt, spk/beets/src/requirements-pure.txt
_Motivation:_ The package hasn't been updated in a while.
_Linked issues:_  #4934
https://github.com/beetbox/beets/blob/master/setup.py#L87
[install.txt](https://github.com/SynoCommunity/spksrc/files/7448920/log.txt)
Test build: https://seby.io/download/synology-7.0/beets_noarch-dsm7_1.5.0-7.spk
=> beets: update to 1.5.0 & Dependencies

cross/bazarr/PLIST, mk/spksrc.install.mk
_Motivation:_  bazarr was no longer packaged properly
=> Fix bazarr build to use PLIST.auto

cross/libjpeg/Makefile, cross/libjpeg/PLIST, cross/libjpeg/digests
_Motivation:_  Build failures in #5050 due to changes in libjpeg related to the newer release version 9e (as it seems they also repackaged the older version 9d).  Using the opportunity to update the library.
_Linked issues:_  #5050
=> libjpeg: Update from version 9d to 9e and change URL source

mk/spksrc.copy.mk, mk/spksrc.install.mk, mk/spksrc.plist.mk
_Motivation:_  A but was introduced in an earlier PR #5018 where PLIST entries with `*` are not being handled anymore.
_Linked issues:_  https://github.com/SynoCommunity/spksrc/pull/5044#issuecomment-1004404717
With https://github.com/SynoCommunity/spksrc/pull/5046/commits/d442ce2c46d8aa41683375733def1a54134feb7f commit I tested succesfully:
=> copy.mk: Revert change as it does not handle * PLIST entries

spk/python310/Makefile, spk/python310/src/requirements-pure.txt
_Motivation:_  I had forgotten to re-enable `wheel` + `setuptools` at python310 install.  Re-enabling.
_Linked issues:_  n/a, caught-up before activating latest update.
=> python310: Re-enable wheel+setuptools isntallation

cross/nano/Makefile, cross/nano/digests, diyspk/nano/Makefile, diyspk/nano/src/service-setup.sh, spk/synocli-file/Makefile, spk/synocli-file/src/service-setup.sh
Enables a default config with syntax highlighting support
**Usage:**
e.g. `env TERM=xterm-color nano /volume1/web_packages/adminer/index.php`
An alternative per user setting:
```sh
echo "include /var/packages/synocli-file/target/share/nano/*.nanorc" >> ~/.nanorc
env TERM=xterm-color nano /volume1/web_packages/adminer/index.php
```
_Linked issues:_  https://discord.com/channels/732558169863225384/732559466721181738/926808496236806165 @bokkoman
FYI More syntax support is available from: https://github.com/scopatz/nanorc
=> Nano 6.0 with default config and syntax highlighting

cross/libjpeg/digests
- they changed the copyright date in jcparm.c to 2022, without creating a new revision
Fixes #
=> fix digests of libjpeg

cross/ruby/Makefile, cross/ruby/PLIST, cross/ruby/digests, native/ruby/Makefile, native/ruby/digests, spk/ruby/Makefile
Upgrade ruby to latest stable release v3.1.0.
https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/
DSM: 7.0
Arch: denverton
```shell
$ uname -a
Linux nas 4.4.180+ #42218 SMP Mon Oct 18 19:26:24 CST 2021 x86_64 GNU/Linux synology_denverton_rs820+
$ sudo synopkg install ~/work/ruby_denverton-7.0_3.1.0-10.spk 
Password: 
{"error":{"code":0},"results":[{"action":"upgrade","beta":false,"betaIncoming":false,"error":{"code":0},"finished":true,"installReboot":false,"installing":true,"language":"enu","last_stage":"started","package":"ruby","packageName":"Ruby","pid":2567,"scripts":[{"code":0,"message":"","type":"stop"},{"code":0,"message":"","type":"preupgrade"},{"code":0,"message":"","type":"preuninst"},{"code":0,"message":"","type":"postuninst"},{"code":0,"message":"","type":"preinst …
```
=> ruby: Upgrade ruby to v3.1.0

mk/spksrc.spk.mk
_Motivation:_  Until now it is not possible to exclude specific archs from a generic arch
_Linked issues:_  solution for https://github.com/SynoCommunity/spksrc/issues/5030#issuecomment-1007364569
=> adjust INFO file to exclude archs that are not supported

cross/readline/Makefile
current version of cross/readline fails to build.
=> fix readline

mk/spksrc.copy.mk, spk/plowshare/PLIST
remove error log of missing PLIST files in spk folders
Fixes # 
encouraged by @ymartin59 in discord
_Another topic: when reviewing packages, I find it "stupid" to create so many empty "PLIST" files - I guess the "makefiles framework" may be improved to adapt to the lack of PLIST file (and consider it as empty) - any volunteer to propose such improvement?_
=> make empty PLIST files in spk folders obsolete

cross/libjpeg/Makefile, cross/libjpeg/digests
Content of libjpeg source archive is updated again without changing the file name.
if version 9e is not stable yet, we probably might downgrade to version 9d.
This is a follow up to #5078 and #5060. The libjpeg source changed while my integration testing of #5078.
It reverts the libjpeg archve location introduced by #5053.
=> fix libjpeg download

mk/spksrc.wheel.mk
1. This is another fix to suppress obsolete build error output (like #5080) 
2. Ensure it exit with error when failure to build a wheel.
=> avoid error output for packages without wheels

cross/mg/Makefile, cross/nnn/patches/DSM-1.2/001-avoid-file-offset-64-for-32-bit-archs-on-srm1.patch, spk/synocli-file/Makefile
Some more fixes for synocli-file
- exclude nnn for unsupported archs
- fix build of nnn for SRM-1.2
- fix build of mg for OLD_PPC_ARCHS
=> Fix synocli-file

cross/sabnzbd/Makefile, cross/sabnzbd/digests, cross/unrar/Makefile, cross/unrar/digests, spk/sabnzbd/Makefile, spk/sabnzbd/src/config.ini, spk/sabnzbd/src/requirements-pure.txt
=> Update SABnzbd to 3.5.0

mk/spksrc.spk.mk
- fix the creation of conf/privilege file (bugfix for #4930)
- #4930 changed the conf/resource file creation and broke the privilege file creation due to missing folder (e.g. for syncthing armv7-1.2)
=> fix conf file creation

spk/syncthing/Makefile, spk/syncthing/src/ca_reloader.sh
follow up of #5117
- revert to use SERVICE_CERT_RELOAD
=> syncthing: fix SERVICE_CERT_RELOAD

native/go/Makefile, native/go/digests
Upgrade go to 1.17.6.
```
go1.17.6 (released 2022-01-06) includes fixes to the compiler, linker, runtime, and the crypto/x509, net/http, and reflect packages. See the Go 1.17.6 milestone on our issue tracker for details. 
```
https://github.com/golang/go/issues?q=milestone%3AGo1.17.6+label%3ACherryPickApproved
The CI is broken because of bad checksums for gitea. May be https://github.com/SynoCommunity/spksrc/pull/5088 would fix the problem
=> Upgrade native/go to 1.17.6

spk/python310/Makefile
Forgot to bump package version thus it never made it to supersede server-side package version.  Follow-up to #5101
=> python310: Bump package version for publishing

spk/homeassistant/Makefile
homeassistant: Issue with numpy on armv5 no longer exists
Fixes # Relates to on-going work on #5043
=> homeassistant: Issue with numpy on armv5 no longer exists

.github/actions/download.sh, mk/spksrc.cross-env.mk, mk/spksrc.tc.mk
This allows from spksrc/kernel/syno* directories to call-up `make download` which will only download the toolchain without
actually extracting it.
This greatly reduces disk size on github-action when pre-downloading kernels.
Part of https://github.com/SynoCommunity/spksrc/pull/5095 PR split.
=> spksrc: Allow downloading without extracting the toolchain

.github/actions/build.sh, mk/spksrc.cross-cc.mk, mk/spksrc.cross-dotnet.mk, mk/spksrc.cross-go.mk, mk/spksrc.cross-rust.mk, mk/spksrc.install-resources.mk, mk/spksrc.spk.mk
This PR address the issue with the exit code on error.  
1. There are corner-cases where builds does not exit with proper exit error signal. After further looking into it this appear to be due to the tee pipe where the exit code is from the later command. The way to properly handle this is through the `${PIPESTATUS[0]}` using `bash` shell variable which provides the output from the first command from the pipe sequence.
2. In extra to that, all instances of `-@$(MAKE)` have been replaced with `@$(MAKE)` to allow passing errors
3. Additional github-action success test is being used to confirm that the resulting package has been created or not.
Part of #5095 PR split.
=> Fix make exit status

mk/spksrc.download.mk
The following options allow wget to retry in case of error.  It also print the real and full command line to the log file.
Part of https://github.com/SynoCommunity/spksrc/pull/5095 PR split.
=> download.mk: Allow multiple retries and echo real cmd line

.github/workflows/build.yml
Instead of having 1 huge result, lets split the results based on `arch`.
Is there any reason not to do this?
=> Separate packages for each arch

.github/actions/build.sh
With latest changes it now `exit 2` on pre-check.mk causing an error on github-action.  The following aims at validating this before confirming that this really is an error.
Fixes https://github.com/SynoCommunity/spksrc/pull/5162#issuecomment-1078058126
=> Pre check false-negative with github-action

spk/nzbget/Makefile
This lowers the size of the NZBGet SPK from 30MB to 14MB.
We could also just do this `git clone` during installation script, then the package would shrink to only a few MB.
But it would add the `git` dependency. Is that worth it?
=> Use shallow clone when including NZBGet tools

.github/workflows/build.yml
Since we never use it, let's remove it.
=> Remove Release step from Build action

cross/git/Makefile, spk/git/Makefile
- use -std=gnu99 instead of -std=c99 to get rid of runtime errors on 32bit archs (arm and ppc)
Fixes #5196
=> git: fix for 32bit arm and ppc archs (fixes #5196)

mk/spksrc.copy.mk
Path passed to generate tar archive was missing a `/../` suffix.  Included other smaller changes as proposed by @hgy59.
Fixes #5213
=> copy.mk: Fix staging path for var & target/var

mk/spksrc.directories.mk
Found by @hgy59 is another fix for https://github.com/SynoCommunity/spksrc/pull/5163
> without this fix, I got the error below in urbackup.log on DSM 7
```
... ERROR: Cannot set working directory to directory /var/packages/urbackup/target/../var
```
Fixes #5163
=> directories .mk: avoid .. in INSTALL_PREFIX_VAR

toolchain/syno-aarch64-6.1/Makefile, toolchain/syno-aarch64-6.2.2/Makefile, toolchain/syno-aarch64-6.2.3/Makefile, toolchain/syno-aarch64-6.2.4/Makefile, toolchain/syno-aarch64-6.2/Makefile, toolchain/syno-aarch64-7.0/Makefile
toolchain: aarch64 cannot be a sub-arch of itself.
Post #5238 aarch64 disapeared from the radar...
=> toolchain: aarch64 cannot be a sub-arch of itself

mk/spksrc.spk.mk
spk.mk: Typo in #5238, while code was still functional it shoulf have called `make arch-<arch>-<version>` insteaf of `make build-arch-<arch>-<version>` as otherwise it skips a section of code.
Fixes #5238
=> spk.mk: Must call arch-<arch>-<version> insteaf of build-arch-<>

Dockerfile, README.md
Dockerfile: Add autopoint as mandatory dependency for some use-cases for `autogen.sh`
Relates to #5095
=> Dockerfile: Add autopoint as mandatory dependency for autogen.sh

cross/dotnet-runtime/Makefile, mk/spksrc.plist.mk
PLIST.auto support was broken since it was always generating PLIST which would be including everything which **preexisted** before a package installation procedure was run.
Fixes #5233
=> Fixed PLIST.auto support

native/go/Makefile, native/go/digests
Update go to 1.18.1
Fixes CVE-2022-28327, CVE-2022-24675, CVE-2022-27536
=> update go to 1.18.1

mk/spksrc.service.installer.dsm5, mk/spksrc.service.installer.dsm6
fix shared folder creation in installers for dsm5 and dsm6
- create shares with empty user lists for rw access.
Fixes #4357
=> dsm5/6 installer: fix share creation (close #4357)

cross/openssl/Makefile, cross/openssl/PLIST, cross/openssl/digests
security and bug fixes
- The c_rehash script allows command injection (CVE-2022-1292)
- remove c_rehash script as declared obsolete anyway
=> update openssl to v1.1.1o

spk/radarr/Makefile, spk/radarr/src/service-setup.sh
add @appdata folder migration for DSM7 as wrong folder was used in SPK_REV 15 of the package
Fixes #5265
=> radarr: fix @appdata folder for DSM7

spk/radarr/Makefile, spk/radarr/src/service-setup.sh, spk/radarr/src/wizard/upgrade_uifile, spk/radarr/src/wizard/upgrade_uifile_fre
- backup and restore existing radarr distribution to prevent downgrade
- adjust upgrade wizard (fre still needs translation)
To avoid troubles as in #5271 version 20220513-17 is removed in the repository.
Fixes #5271
=> radarr: prevent downgrade on package update

cross/fuse/PLIST, spk/borgbackup/Makefile, spk/borgbackup/src/requirements-crossenv.txt
borgbackup: Enable llfuse support and package pure-python wheels
Fixes #5204 and #4217
=> borgbackup: Enable llfuse support and package pure-python wheels

cross/syncthing/Makefile, cross/syncthing/digests, native/go/Makefile, native/go/digests, spk/syncthing/Makefile
Update go to latest release.
Fixes:  "syscall: check correct group in Faccessat" https://go-review.googlesource.com/c/go/+/399539/
=> go: update to 1.18.2 (security update)

cross/sqlite/Makefile
- SQLITE_ENABLE_UNLOCK_NOTIFY is required for owntone (#4337)
- this PR helps to minimize github build action in #4337
=> sqlite: enable unlock notifications

spk/synocli-kernel/Makefile, spk/synocli-kernel/src/synocli-kernelmodule.sh
Fix KVER to omit extra-version and fix UDEV rule check
Fixes #5286
=> Fix KVER to omit extra-version and fix UDEV rule check

mk/spksrc.spk.mk
spkclean: TC cmake filename changed to tc_vars.cmake
Follow-up to #5280
=> spkclean: TC cmake filename changed to tc_vars.cmake

toolchain/syno-x64-6.1/Makefile, toolchain/syno-x64-6.2.2/Makefile, toolchain/syno-x64-6.2.3/Makefile, toolchain/syno-x64-6.2.4/Makefile, toolchain/syno-x64-6.2/Makefile, toolchain/syno-x64-7.0/Makefile, toolchain/syno-x64-7.1/Makefile
There is an issue in spkrepo (https://github.com/SynoCommunity/spkrepo/issues/86) with too long file names. This is a quick fix by removing unsupported archs from generich x64 archs with DSM 7+.
- add broadwellntbap to DSM 6
- remove unsupported archs from DSM 7 (dockerx64, x86, x86_64)
=> update generic x64 archs

spk/synocli-file/Makefile
- unfortunately version_gcc is not available in spk/ Makefile
- use DSM version to evaluate supported gcc for rnm and nnn
Fixes #5351
=> synocli-file: fix include of nnn and rnm tools (#5351)

mk/spksrc.archs.mk, mk/spksrc.pre-check.mk, mk/spksrc.spk.mk
While working on another package using dotnet (ombi) this is intended to remove specific archs from generic archs.
i.e. remove unsupported armv7 archs from packages built for armv7.
- remove unsupported archs from generic archs in arch list of spk packages
- introduce Makefile variable UNSUPPORTED_ARCHS_TCVERSION to define arch-tcversion tuples as unsupported
- define DOTNET_UNSUPPORTED_ARCHS to be used in packages depending on dotnet
- #5301
-
=> Framework: enhance unsupported archs handling

cross/syncthing/Makefile, cross/syncthing/digests, spk/syncthing/Makefile, spk/syncthing/src/config.xml
When Syncthing tries to apply POSIX permissions on DSM, that will clear out the existing ACLs, leading to [strange permission problems](https://forum.syncthing.net/t/sync-frozen-on-synology-nas-dsm-7/18465).  Include a minimal folder defaults configuration in the shipped config.xml template file, which enables the option in the defaults for newly added folders.
**NOTE:** This will only apply to new installations, as the config template is only used during the first installation.  Existing folders will not be changed either.
Syncthing updated to latest upstream release v1.20.3.  The `SPK_REV` was not bumped, as the previous update to v1.20.1 had not yet been published.
=> syncthing: Set Ignore Permissions option by default for new folders

cross/boost_1.70/Makefile, cross/cereal/Makefile, cross/fish/Makefile, cross/jsoncpp/Makefile, cross/libaom/Makefile, cross/mbedtls/Makefile, mk/spksrc.common.mk
Remove version_gcc and use ${TC_GCC} post cross-cc.mk.  It hapens that function `version_gcc` does not always behave as expected as shown in issue https://github.com/SynoCommunity/spksrc/issues/5401
Fixes relates to #5398
Note that I expect `boost_1.78` to be fixed part of PR #5398
=> Remove version_gcc and use ${TC_GCC} post cross-cc.mk

cross/par2cmdline/Makefile, cross/par2cmdline/digests, cross/par2cmdline/patches/88f6281/c++11-to-c++0x.patch, cross/sabnzbd/Makefile, cross/sabnzbd/digests, cross/unrar/Makefile, cross/unrar/digests, spk/sabnzbd/Makefile
This is a follow-up to #5398 which includes changes to the `service-setup.sh` script.  This update will ensure that the permission adjustments are being propagated to next package release.
Fixes n/a
=> Sabnzbd update to version 3.61

mk/spksrc.spk.mk
The error was added by #5390
- avoid to set a default value for TCVERSION, as it might be evaluated later
- fixes the build of packages with REQUIRED_MIN_DSM (like mkvtoolnix, nodejs_v16)
Fixes mkvtoolnix and nodejs_v16 builds in #5414
=> Avoid default value for TCVERSION (followup to #5390)

spk/deluge/Makefile, spk/deluge/src/service-setup.sh
deluge: Fix Tracker Status Error certificate verify failed
Fixes #5420
=> deluge: Fix Tracker Status Error certificate verify failed

spk/deluge/Makefile, spk/deluge/src/core.conf
deluge:Enforce listen ports 6881-6891 like previously
Fixes #5425
=> deluge:Enforce listen ports 6881-6891 like previously

Dockerfile
Docker: Install `rustc` & upgrade image to Debian 11 bullseye.  This PR is only aimed at adding `rustc` compiler onto our default docker image.  It's integration is within PR #5435 but it requires the docker image being updated in master in order to allow github-action to work.
Clone my copy of this PR:
```
$ git clone https://github.com/th0ma7/spksrc.git
$ cd spksrc
$ git checkout docker-rustc-debian11
```
Create the updated docker image (may need `$ sudo usermod -aG docker $USER` for proper user permissions):
```
$ docker build - < Dockerfile
...
Successfully built 882a0451f1bb
```
Access the docker image:
```
$ docker run -it -v $(pwd):/spksrc 882a0451f1bb /bin/bash
```
Build a `python310` package or what ever you are interested at testing:
```
root@2ff602f23b71:/spksrc# cd …
```
=> Docker: Install rustc & upgrade image to Debian 11 bullseye

spk/rdiff-backup/Makefile, spk/rdiff-backup/src/requirements-crossenv.txt, spk/rdiff-backup/src/requirements-pure.txt, spk/rdiff-backup/src/requirements.txt
rdiff-backup: Update to version 2.0.5 and adjust requirements
Fixes #
=> rdiff-backup: Update to version 2.0.5 and adjust requirements

spk/memcached/Makefile, spk/memcached/src/service-setup.sh
Fixing regression introduced on DSM 6 installation procedure where the web package part wasn't installed (nor uninstalled for what it's worth).
Fixes https://github.com/SynoCommunity/spksrc/issues/5343
=> Memcached: fix DSM 6 installation procedure

.github/actions/prepare.sh, .github/workflows/build.yml
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Gh action output

README.md, spk/homeassistant/Makefile, spk/homeassistant/src/requirements-crossenv.txt
This is a simple repack of the latest (at time of branch) HomeAssistant.  This seems to work on the few uses I have on my DS1819+ (denverton-7.0) (running DSM 7.0.1-42218 Update 4).  Install did stop me until Python-3.10 was installed (which is probably @th0ma7 's work).
Of note, several concerns and blockers have been raised to consider around a HomeAssistant update; I don't specifically fix any of them except half of the two-part "update HA so that <something else>" (#5362).  Indeed, I'm doing this to unblock Tuya for myself, but I've only just upgraded to this without installing a cloud-poll Tuya yet.
I want to make this available to be able to audit the other open HA issues and see if it helps them at all, or we can update this reports.
I also want to call attention(re #5043) to …
=> 20220802 bump homeassistant 2022 7 7

cross/gmp/Makefile, cross/nettle/Makefile, cross/nettle/PLIST, cross/nettle/digests
- update nettle to v3.8.1
- disable assembler for older compilers (i.e. DSM < 6.0)
- optimize code
This is a follow up to #5486 as the build for arch-x86-5.2 failed (aria2 depends on cross/nettle via cross/gnutls)
=> nettle: update and fix for older compilers

cross/aria2/Makefile, spk/aria2/Makefile, spk/synocli-net/Makefile
aria2: DSM < 6.0 is not supported
exclude aria2c from **synocli-net** for unsupported archs
this is another follow up to #5486
=> aria2: fix supported archs

cross/python310/Makefile, native/python310/Makefile
Separated from #5478 (to minimize the github build time in #5478)
- add maturin 0.13.7 wheel to python 3.10 (native/python310 and python 3.10 crossenv)
- required to cross compile orjson wheel
- not supported with ARMv5_ARCHS and OLD_PPC_ARCHS
=> Python 3.10: add maturin to build system

cross/openjpeg/Makefile, cross/zlib/Makefile
This is an extract of #5414 where it fixed the usage of OpenEXR format, rsvg-convert (at runtime) and gdk-pixbuf.
- the generated zlib.pc had wrong prefix 
- this caused problems in dependent libraries and binaries
=> Fix cross/zlib

spk/imagemagick/Makefile
- fix extra_install for arch-x86-5.2
=> imagemagick: fix installation for DSM 5.x

cross/syncthing/Makefile, cross/syncthing/digests, mk/spksrc.copy.mk, mk/spksrc.cross-go.mk, native/go/Makefile, native/go/digests, spk/demoservice/Makefile, spk/demoservice/PLIST, spk/demoservice/src/service-setup.sh, spk/syncthing/Makefile, spk/syncthing/src/service-setup.sh
go 1.19 is required to build nomad 1.4.3
=> native/go: update to v1.19

spk/headphones/Makefile, spk/headphones/src/config.ini, spk/headphones/src/service-setup.sh, spk/headphones/src/wizard/install_uifile, spk/headphones/src/wizard/install_uifile_fre, spk/headphones/src/wizard/upgrade_uifile, spk/headphones/src/wizard/upgrade_uifile_fre
update headphones package as current version depends on Python >= 3.7
- update headphones to Python 3.10
- update for DSM 7 compatibility
Fixes #5457
=> headphones: update to Python 3.10

spk/sickchill/BROKEN
- sickchill was declared as broken with #5414, but meanwhile fixed in #5458
=> sickchill: remove BROKEN

cross/mono/patches/002-explicit-use-of-python2.patch, native/mono/patches/002-explicit-use-of-python2.patch
This is another followup to #5441.
With the updated dev. env. default python is not python 2 anymore.
- patch makefile templates for explicit use of python 2
=> mono: fix build with updated dev. env.

cross/cloudflared/Makefile, cross/cloudflared/digests, spk/cloudflared/Makefile
Update to 2022.12.1
- cloudflared now attempts to try other edge addresses before falling back to a lower protoocol.
- cloudflared tunnel no longer spins up a quick tunnel. The call has to be explicit and provide a --url flag.
- cloudflared will now randomly pick the first or second region to connect to instead of always connecting to region2 first.
Upstream changelog: https://github.com/cloudflare/cloudflared/blob/master/RELEASE_NOTES
=> cloudflared: update to 2022.12.1

native/go/Makefile, native/go/digests
Update go to latest release which includes security fixes.
Fixes CVE-2022-41717, CVE-2022-41720
=> go: update to 1.19.5 (security update)

.github/actions/build.sh, mk/spksrc.cross-rust-env.mk, mk/spksrc.tc-rust.mk, spk/python310/Makefile, spk/python310/src/requirements-crossenv.txt, spk/python311/Makefile, spk/python311/src/requirements-crossenv.txt
This tries to fix #5581
- fix export of CARGO_HOME and RUSTUP_HOME
- fix issue when toolchain caching keeps rustc status file (`toolchain/syno-<arch>-<tcversion>/work/.rustc_done`) in cases where distrib folder install of cargo/rustc isn't existing.
=> Fix rustc builds on github-action

spk/sonarr3/Makefile, spk/sonarr3/src/config.xml, spk/sonarr3/src/service-setup.sh, spk/sonarr3/src/wizard/install_uifile, spk/sonarr3/src/wizard/install_uifile_fre, spk/sonarr3/src/wizard/upgrade_uifile, spk/sonarr3/src/wizard/upgrade_uifile_fre
This corrects a bug in Sonarr v3 (#5515) where an upgrade from legacy Sonarr v2 was not blocked (in DSM6). This results in the distribution containing two sets of binaries and AppData directories which can break the deployment. This bug also creates issues with upgrades to Sonarr v4 (#5524) since the correct installed version cannot be determined.
Once published, it is recommended that Sonarr v3 (Version 20221216-21) be unpublished to avoid future use.
=> Sonarr v3: fix block on legacy (v2) upgrades

cross/cloudflared/Makefile, cross/cloudflared/digests, spk/cloudflared/Makefile
Update to 2023.1.0
Upstream changelog: https://github.com/cloudflare/cloudflared/blob/master/RELEASE_NOTES
=> cloudflared: update to 2023.1.0

mk/spksrc.cross-meson-env.mk
A typo in armv7 and armv7l `MESON_HOST_CPU_FAMILY` variable leads to failure to build on arm.
=> meson-env.mk: Fix typo in arm architecture failing for armv7-7l

spk/jellyfin/Makefile
followup to #5585
to clarify that most archs (32-bit archs) are not supported anymore
=> jellyfin: add note for unsupported archs to changelog

mk/spksrc.archs.mk, mk/spksrc.service.installer.dsm5, mk/spksrc.service.installer.dsm6, mk/spksrc.service.installer.dsm7, mk/spksrc.service.installer.functions
These changes to the framework were motivated by (a) install errors with the `load_variables_from_file` function (b) inconsistent arch exclusions for dotnet packages. This PR contains the following:
1. Fixes bug in `call_func` arguments used by `load_variables_from_file` function
2. Add `Makefile` variables for dotnet 6.0 arch exclusions (core and servarr)
Follow up of #5570
Fixes #5574 (adds helper)
=> Framework: fix installer, add arch vars

spk/sonarr3/Makefile, spk/sonarr3/src/service-setup.sh
Amends https://github.com/SynoCommunity/spksrc/pull/5591 to update service setup `GROUP` variable to exclude DSM7 (deprecated in DSM7).
=> Sonarr v3: fix for service setup

cross/openssl/Makefile, cross/openssl/digests
openssl: Update from version 1.1.1s to 1.1.1t
Major changes between OpenSSL 1.1.1s and OpenSSL 1.1.1t [7 Feb 2023]
Fixed X.400 address type confusion in X.509 GeneralName ([CVE-2023-0286](https://www.openssl.org/news/vulnerabilities.html#CVE-2023-0286))
Fixed Use-after-free following BIO_new_NDEF ([CVE-2023-0215](https://www.openssl.org/news/vulnerabilities.html#CVE-2023-0215))
Fixed Double free after calling PEM_read_bio_ex ([CVE-2022-4450](https://www.openssl.org/news/vulnerabilities.html#CVE-2022-4450))
Fixed Timing Oracle in RSA Decryption ([CVE-2022-4304](https://www.openssl.org/news/vulnerabilities.html#CVE-2022-4304))
=> openssl: Update from version 1.1.1s to 1.1.1t

mk/spksrc.spk.mk
In some builds that included wizard UI files based on shell scripts, the shell scripts didn't execute during the installation wizard under DSM6 because they lacked the execute bit set (https://github.com/SynoCommunity/spksrc/pull/5524#issuecomment-1374808403 and https://github.com/SynoCommunity/spksrc/pull/5455#issuecomment-1432118636). This issue occurred because the current [`spksrc.spk.mk`](https://github.com/SynoCommunity/spksrc/blob/master/mk/spksrc.spk.mk) set the execute bit as part of a block that evaluated the contents of the parent folder based on wildcards. However, for Makefiles, wildcards are evaluated during parsing and are not re-evaluated when the containing statement is executed (see: [The Trouble with $(wildcard)](https://www.cmcrossroads.com/article/trouble-wildcard)). …
=> Framework: fix for wizard file permissions

cross/mono/Makefile, native/mono/patches/001-relocate-specialfolders.patch, native/mono_58/patches/001-relocate-specialfolders.patch, spk/mono/Makefile
This PR is to update the patch files to use `/var/packages/mono/var` instead of `/var/packages/mono/target/var` for DSM 7 compatibility.
Follow up of #5522
Fixes #5051, #5354
=> Mono: fix DSM 7 compatibility

spk/sabnzbd/src/service-setup.sh
This is a minor correction to the service setup script to address the following:
1. Only set `GROUP` variable for DSM 6 (deprecated in DSM 7)
2. Correct option for `shopt` function call (https://github.com/SynoCommunity/spksrc/pull/5594#issuecomment-1429534830)
Follow up of #4748
Fixes #
=> Sabnzbd: Fix service setup script

cross/glib/Makefile, cross/glibmm/Makefile, cross/libsigc++/Makefile
Issue not encountered on github-action but does hapens on local builds using containers.  When processing dependencies it hapens a collision point where `glib` main cookie conflicts with sub-dependencies.  This lead to expectation that sub-dependency (e.g. `glib-latest`) is already download while it is not the case.
Fix is relatively simple and involves renaming main `cross/glib|glibmm|ligsigc++` so `PKG_NAME` variable always differs from sub-dependency.  Adding `-main` solves the issue:
```
PKG_NAME = glib-main
PKG_NAME = glibmm-main
PKG_NAME = libsigc++-main
```
Fixes #
=> Fix for #5600 depends conflicting with sub-dependencies cookies

mk/spksrc.archs.mk
This is a follow up to #5596
- SRM armv7 archs do not support dotnet
=> avoid dotnet packages for SRM

mk/spksrc.cross-cmake.mk, mk/spksrc.tc-flags.mk
This PR solves two regressions introduced in #5658
1. In extremely rare case, mostly with software sources that doesn't fully respect CMAKE, including `PKG_CONFIG_SYSROOT_DIR` makes `intel-media-driver` fails. This `PKG_CONFIG_SYSROOT_DIR` is probably something to revisit.
2. Usage of `abspath` makes the `tc_vars.mk` clean and absent of any '//' and '../'.  Altough I had introduced it in pre-requisite variables leading to double-counting the toolchain path part of the generation of `*FLAGS` variables.  This was noticed only under `libraqm` part of ImageMagick build.
Follow-up to #5658
=> Regression Fix : PKG_CONFIG_SYSROOT_DIR and TC_SYSROOT pre-requisite variables

spk/rutorrent/Makefile, spk/rutorrent/src/conf/resource, spk/rutorrent/src/etc/php/conf.d/com.synocommunity.rutorrent.ini, spk/rutorrent/src/service-setup.sh, spk/rutorrent/src/wizard_templates/install_uifile.sh
This is fixing basically installation related concerns:
* When customizing the volume an invalid value was defined for the full path of the download location
* There were left over files from the previous PHP integration (5.6)
* Apache 2.4 dependency wasn't explicitely declared
* Watch dir configuration wasn't appropriately supported
Should fix #5668
=> rutorrent: fix volume customization in installation procedure and package dependencies

spk/deluge/Makefile, spk/deluge/src/requirements-pure.txt
deluge: Add chardet as yarss2 plugin dependency
Fixes #5674
=> deluge: Add chardet as yarss2 plugin dependency

mk/spksrc.spk.mk
spk.mk: Allow generating `publish-<arch>-<version>.log` files.  This allows tracking manual publishing of packages online.
=> spk.mk: Allow generating publish-<arch>-<version>.log files

mk/spksrc.archs.mk
This is a follow-on from #5602 and adds the exclusions for `alpine` and `alpine4k` based on investigation in https://github.com/SynoCommunity/spksrc/issues/5302#issuecomment-1487986989 and https://github.com/SynoCommunity/spksrc/issues/5574#issuecomment-1488478681.
Fixes # 
Closes #5302
Closes #4546
=> Framework: Update dotnet 6.0 exclusions

cross/filebrowser/Makefile, cross/filebrowser/digests, native/nodejs/Makefile, native/nodejs/digests, spk/filebrowser/Makefile
So far native/nodejs is used to build the following packages
- jellyfin
- gitea
- filebrowser
filebrowser has an issue that is fixed here (while updating filebrowser to the latest version)
packages under development that depend on native/nodejs are
- navidrome #5376
- node-red #5407
=> native/nodejs: update to active LTS version (and update filebrowser)

mk/spksrc.depend.mk, mk/spksrc.spk.mk
If one of the dependencies (or a kernel module) fails to build, the build continues anyway. This takes more time than necessary and makes the real error harder to spot in the logs.
(this doesn't touch any packages)
=> Bail early if dependency or kernel module fails to build

.gitignore, mk/spksrc.spk.mk
This PR was motivated by inconsistencies observed in the package publish process. It was noted that when the package is sent to the repository, there was no checking to confirm that the package was successfully received and added. This PR seeks to add this functionality.
Fixes #
=> Framework: Add publish validation check

mk/spksrc.spk.mk
This is a follow-on from #5701 to remove the `-e` option for echo which is not POSIX compliant.
Fixes #
=> Framework: Amend publish validation check

cross/jellyfin-web/Makefile, cross/jellyfin-web/digests, cross/jellyfin/Makefile, cross/jellyfin/digests, native/dotnet-sdk-6.0/Makefile, native/dotnet-sdk-6.0/digests, spk/jellyfin/Makefile, spk/jellyfin/src/service-setup.sh
1. Update jellyfin to 10.8.10 (Stable hotfix release for 10.8.z release branch)
2. Update dotnet to 6.0.16 (Security patch)
3. Fix dotnet dependencies for DSM 7.2
Fixes #
=> Jellyfin: Update to v10.8.10

cross/openssl3/Makefile, cross/openssl3/digests, cross/openssl3/patches/aarch64-6.1/001-fix-asm-arch-for-old-gcc.patch
As openssl 1.1.1 will be EOL in a few months, it is time to provide a openssl v3 package for all archs.
_OpenSSL 1.1.1 was released on 11th September 2018, and so it will be considered EOL on 11th September 2023. It will no longer be receiving publicly available security fixes after that date._
Currently all of the spk packages depending on openssl use version 1.1.1.
Shortly I will provide an update of erlang that supports openssl v3.
Since openssl v1.1 and v3 have some differences in the API it will take some time, until all packages and their dependencies are updated (if ever).
=> openssl3: update to v3.1.0

cross/sqlite/Makefile, cross/sqlite/digests
udpate sqlite from v3.39.3 to v3.42.0
Fixes #
=> sqlite: update to v3.42.0

cross/libstdc++/Makefile
- use sources added to synocommunity spksrc repo
the debian repo used to download sources for cross/libstc++ does not provide the sources (of gcc-6) anymore.
Fixes #5715, fixex #5720, fixes  #5370 and others
This fixes the build of all packages depending on cross/libstdc++
- dotnet-runtime 
- jackett 
- jellyfin 
- lidarr 
- ombi 
- prowlarr 
- radarr 
- readarr 
- sonarr
=> update sources for libstdc++

cross/rutorrent/Makefile, cross/rutorrent/digests, cross/rutorrent/patches/002-fixing-default-value-for-local-hosted-mode.patch, spk/rutorrent/Makefile, spk/rutorrent/src/requirements-pure.txt, spk/rutorrent/src/service-setup.sh
Upgrade rutorrent 3.10 to 4.1.5 + migrated to python 3.11
Binaries are available here: https://github.com/smaarn/spksrc/releases/tag/rutorrent-4.1.5-rc-1
=> rutorrent: upgrade 3.10 => 4.1.5

.github/workflows/build.yml
fix for publish of noarch packages (like #5236 
- noarch build for DSM 6.x must be at least version 6.1
=> fix github action to build noarch 6.1

cross/cloudflared/Makefile, cross/cloudflared/digests, spk/cloudflared/Makefile
Update to 2023.5.1
- You can now stream your logs from your remote cloudflared to your local terminal with `cloudflared tail <TUNNEL-ID>`. This new feature requires the remote cloudflared to be version 2023.4.1 or higher.
- Migrated to devincarr/quic-go to unblock go 1.20 support as the old lucas-clemente/quic-go will not get go 1.20 support.
- Due to the nature of QuickTunnels (https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/do-more-with-tunnels/trycloudflare/) and its intended usage for testing and experiment of Cloudflare Tunnels, starting from 2023.3.2, QuickTunnels only make a single connection to the edge. If users want to use Tunnels in a production environment, they should move to Named Tunnels instead. …
=> cloudflared: update to 2023.5.1

cross/openssl/Makefile, cross/openssl/digests, cross/openssl3/Makefile, cross/openssl3/digests
- openssl3 update to v3.1.1
- activate asm for aarch64 < DSM 7
- forgot to activate asm after fix with patch ()
- patch is still required as fix is merged after 3.1.1 (will be fixed in 3.1.2)
- openssl update to v1.1.1u
=> openssl: CVE-2023-2650

.github/workflows/build.yml, Makefile, spk/umurmur/Makefile, toolchain/syno-aarch64-6.2.4/patches/define_scsi_ioctl_tagged_enable_disable.patch, toolchain/syno-evansport-6.2.4/patches/define_scsi_ioctl_tagged_enable_disable.patch, toolchain/syno-x64-6.2.4/patches/define_scsi_ioctl_tagged_enable_disable.patch
Update DSM6 default version from 6.1 to 6.2.4 due to toolchain removals
Fixes n/a
=> Update DSM6 default version from 6.1 to 6.2.4 due to toolchain removals

.github/actions/prepare.sh, cross/chromaprint/Makefile, cross/iperf3/Makefile, mk/spksrc.dependency-tree.mk
This PR was initiated by the fact, that the prepare job of the github build action takes a large amount of time.
Local analysis showed that it takes > 60 seconds to evaluate the dependency-list for each package that depends on ffmpeg.
before, the "Evaluate dependencies" step of the "Prepare for Build" job took about 6 to 10 minutes.
with this fix, it takes about 3 minutes.
=> Fix GitHub prepare action

cross/openssl3/patches/aarch64-6.2.4/001-fix-asm-arch-for-old-gcc.patch
fix openssl3 for aarch64 with DSM 6.2.4
=> openssl3: add aarch64 patch for DSM 6.2.4

cross/python310/Makefile, cross/python311/Makefile, spk/python310/Makefile, spk/python311/Makefile
py310-311: Re-include openssl 1.x until all py-spk migrated over
Fixes #5800
=> py310-311: Re-include openssl 1.x until all py-spk migrated over

cross/micro/patches/001-disable-vcs-stamping.patch, spk/synocli-file/Makefile
- cross/micro: use -buildvcs=false to disable VCS stamping
- add openssl update info to changelog
=> synocli-file: fix build of micro

cross/misc-util-linux/Makefile, cross/misc-util-linux/PLIST, cross/uhubctl/Makefile, cross/uhubctl/PLIST, cross/uhubctl/digests, diyspk/uhubctl/Makefile, spk/synocli-misc/Makefile
add `zramctl` and `uhubctl` to synocli-misc package
Closes #5749, closes #5825
=> synocli-misc: add zramctl and uhubctl

toolchain/syno-88f6281-5.2/Makefile, toolchain/syno-armv7-1.2/Makefile, toolchain/syno-ipq806x-1.2/Makefile, toolchain/syno-ppc853x-5.2/Makefile, toolchain/syno-x64-5.2/Makefile, toolchain/syno-x86-5.2/Makefile
- add DSM 5.2 toolchains not provided by Synology anymore
- limited to toolchains for models that do not support DSM 6
- add SRM 1.2 toolchains not provided by Synology anymore
- for SRM only generic armv7-1.2 and ipq806x-1.2 are provided
=> Add toolchains for DSM 5.2 and SRM 1.2

cross/urw-base35-fonts/Makefile
This is a fix for dependent packages `ntopng` and `imagemagick`
- original archive of free ghostscript fonts is not reachable anymore
=> use urw-base35-fonts from synocommunity repo

mk/spksrc.python.mk, mk/spksrc.spk.mk
Related to #5820
- fix remove of symlinks for python-wheel dependencies
- take only cross/ dependencies since build prints "===>  Downloading toolchain" or "===>  Setting-up toolchain" to dependency-flat
Fixes the grep error reported in https://github.com/SynoCommunity/spksrc/pull/5869#issuecomment-1709314476
=> fix spksrc.python.mk

.github/actions/prepare.sh, mk/spksrc.pre-check.mk
Avoid log output of `UNSUPPORTED_ARCHS` when dependency-list (or dependency-tree) target is used.
=> Disable supported archs checks for dependency evaluation

.github/actions/build.sh, .github/actions/prepare.sh
When publishing packages that depends on others when built, ensure to only publish the package requested and not it's dependency.  This hapens for instance when publishing `deluge` whereas `python311` will get built as pre-depend package.  Currently it will publish both packages online thus generating errors as pre-depend package is most probably already published, thus colliding.
Fixes #5870
=> Attempt at fixing publishing whith dependent packages

.github/actions/build.sh, .github/workflows/build.yml
Attempt no. 2 at fixing publishing whith dependent packages
Fixes #5870 and relates to #5874
=> Attempt no. 2 at fixing publishing whith dependent packages

cross/libpng/Makefile
libpng: Fix cmake args and disable static library.  This in turns allow building with `debug_symbols` enabled.
Relates to #5879
=> libpng: Fix cmake args and disable static library

spk/synocli-devel/Makefile
followup to #5882 to avoid build of llvm for x86-5.2.
=> synocli-devel: avoid llvm for DSM 5.2

cross/tdu/Makefile
follow-up to #5898
tdu: fix build in some constellations
- fix disable VCS stamping
Fixes #
=> synocli-disk: fix tdu build

mk/spksrc.service.installer.functions
This is a follow up to #5649
- fix initialization of SHARE_NAME from SHARE_PATH
There is another issue with migration of shared folder handling from `SERVICE_WIZARD_SHARE` to `SERVICE_WIZARD_SHARENAME` variables.
On DSM 6 the migration does not work on package upgrade without an upgrade wizard that provides the share configuration again and reloads the wizard variable from previous installation (found in etc/installer-variables).
=> fix shared folder handling

spk/owncloud/Makefile, spk/owncloud/src/conf_6/resource, spk/owncloud/src/service-setup.sh, spk/owncloud/src/web/owncloud.json, spk/owncloud/src/wizard_templates/install_uifile.sh, spk/owncloud/src/wizard_templates/install_uifile.yml, spk/owncloud/src/wizard_templates/install_uifile_fre.yml, spk/owncloud/src/wizard_templates/uninstall_uifile.sh, spk/owncloud/src/wizard_templates/upgrade_uifile.sh
This is a follow-on from #5912 which fixes the PHP FPM handling in DSM 6 by making all functions run as the `http` user. Code has also been added to revert modification to PHP template defaults from previous versions.
Fixes #
=> ownCloud: Update PHP FPM in DSM 6

cross/owncloud/Makefile, cross/owncloud/digests, spk/owncloud/Makefile, spk/owncloud/src/service-setup.sh, spk/owncloud/src/wizard_templates/install_uifile.sh
1. Update ownCloud to version 10.13.3
2. Improved backup function
3. Added upgrade check on install from archive
Fixes #
=> ownCloud: Update to v10.13.3

spk/owncloud/Makefile, spk/owncloud/src/wizard_templates/install_uifile.sh, spk/owncloud/src/wizard_templates/uninstall_uifile.sh
This aims to rectify the concern highlighted in #5949 by addressing a bug in the installation wizard that inaccurately indicates multiple PHP profiles. This issue is specifically noticed in DSM 7 installations and is a consequence of modifications introduced in #5920. The underlying cause of this bug can be traced back to a logic error within a DSM 6 feature.
Fixes #
=> ownCloud: Fix bug in wizard scripts

spk/selfoss/Makefile, spk/selfoss/src/wizard/install_uifile.sh, spk/selfoss/src/wizard/install_uifile_fre.sh
This addresses a bug identified in pull request #5916, where the installation wizard incorrectly detects multiple PHP profiles. This issue is specific to DSM 7 installations, making the concern irrelevant for these cases. It's important to clarify that the initial implementation was intended as an enhancement exclusively for DSM 6 users.
Fixes #
=> Selfoss: Fix bug in wizard scripts

spk/tt-rss/Makefile, spk/tt-rss/src/wizard_templates/install_uifile.sh, spk/tt-rss/src/wizard_templates/install_uifile.yml, spk/tt-rss/src/wizard_templates/install_uifile_fre.yml, spk/tt-rss/src/wizard_templates/uninstall_uifile, spk/tt-rss/src/wizard_templates/upgrade_uifile.sh
This addresses a bug identified in pull request #5923, where the installation wizard incorrectly detects multiple PHP profiles. This issue is specific to DSM 7 installations, making the concern irrelevant for these cases. It's important to clarify that the initial implementation was intended as an enhancement exclusively for DSM 6 users.
Fixes #
=> tt-rss: Fix bug in wizard scripts

mk/spksrc.archs.mk
This pull request enhances the clarity of dotnet 6.x exclusions by revising existing definitions, streamlines the documentation by consolidating notes and history, and introduces specific exclusions for ARMv7 under DSM 6.2.
Fixes #
=> [Framework] Update arch exclusions for dotnet

spk/cops/Makefile, spk/cops/src/conf/resource, spk/cops/src/conf_6/resource, spk/cops/src/service-setup.sh, spk/cops/src/wizard_templates/upgrade_uifile.sh, spk/cops/src/wizard_templates/upgrade_uifile.yml, spk/cops/src/wizard_templates/upgrade_uifile_fre.yml
This builds upon the developments in PR #5957 by introducing an upgrade wizard. The wizard is designed to identify the presence of a data share; if none is found, it extracts the library folder name to propose it as the designated data share for the upgrade. This enhancement addresses issues in previous packages where the absence of a defined data share led to upgrade failures.
Fixes #5961
=> COPS: Enhance Upgrade Process for Legacy Versions

mk/spksrc.strip.mk, spk/python311/Makefile
This PR fixes :
1. `debug_info` symbols enablement where as at strip time symbols would be removed in some cases
2. ensures to check within wheels if `libatomic.so` is needed
In turns this removes unrelated changes from #5879 in order for it to solely focus on the qoriq rust issue.
=> Enhance debug_info symbols + libatomic in wheels (follows-up to #5879)

cross/sabnzbd/Makefile, cross/sabnzbd/digests, spk/sabnzbd/Makefile, spk/sabnzbd/src/requirements-crossenv.txt, spk/sabnzbd/src/requirements-pure.txt, spk/sabnzbd/src/service-setup.sh, spk/sabnzbd/src/wizard/install_uifile, spk/sabnzbd/src/wizard/upgrade_uifile, spk/sabnzbd/src/wizard/upgrade_uifile.sh
Update SABnzbd to 4.2.1.
@mreid-tt @hgy59 Do I need to change anything about the shared folder handling? It's a bit unclear to me.
I look at Transmission, but it seems that is more complicated than SABnzbd needs?
=> Update SABnzbd to 4.2.1

cross/openssl/Makefile, cross/openssl/digests
There are still some packages not updated to openssl3
The previous version 1.1.1v is not available for download anymore.
=> openssl: update to v1.1.1w

mk/spksrc.service.installer.functions
This proposed framework update aims to rectify issues associated with Python-based package installations. Specifically, it addresses a situation where, in the presence of installation errors, the system erroneously reports a successful installation to the user.
Fixes #5926
=> [Framework] Add error detection to python pip calls

mk/spksrc.cross-cc.mk
cross-cc.mk: Echo an error message indicating to first run `make setup` when using `make all-supported` from cross
Fixes #5994
=> cross-cc.mk: Msg. to run make setup first when using all-supported

cross/ruby/Makefile, cross/ruby/PLIST, spk/ruby/Makefile
- update dependency to cross/openssl3
- holdback update to newer ruby version (not compatible with toolchains lacking c++11 compiler)
- update packages in repo to support newer archs (#5993)
- reduce package size (compile with -O2 instead of -O3, strip ruby *.so files)
Closes #5993
=> ruby: update to use openssl3

cross/memcached/Makefile, cross/memcached/digests, cross/phpmemcachedadmin/Makefile, spk/memcached/Makefile, spk/memcached/src/conf/resource, spk/memcached/src/service-setup.sh
- update memcached
- update to php 7.4 to fix DSM 7 installations (#5745)
- remove obsolete user cleanup code (for DSM 5 to DSM 6 upgrade)
Fixes #5745
=> memcached: update to v1.6.23

cross/zsh/Makefile, spk/zsh-static/Makefile, spk/zsh/Makefile
include pcre and cap libraries in zsh and zsh-static packages
Fixes #6014
=> zsh: include pcre and cap libraries

mk/spksrc.service.installer.functions
This fixes the generic installers that are broken with #5927 for all SRM and DSM < 6.0 packages.
=> fix generic installers

.github/actions/build.sh, mk/spksrc.spk.mk
Fix build disk space - System.IO.IOException: No space left on device
- Create a new cleanup call `make clean-source` which only removes the `work-<package>*` source directories
- Call both `make clean-source` and `make spkclean` after builds through github-action
Fixes #
=> Fix build disk space - System.IO.IOException: No space left on device

cross/libutempter/Makefile, cross/mosh/Makefile, spk/mosh/Makefile
- update openssl to v3.1.5
- remove -O2 from cppflags as it is the default
- adjust links for libutempter
Fixes #
=> mosh: update openssl library

cross/pcre2/Makefile, cross/pcre2/PLIST, cross/pcre2/digests, cross/ripgrep/Makefile, diyspk/ripgrep/Makefile
The build of synocli-file package fails in the github build action, but succeeds locally.
The build was ok, when synocli-file was updates with [build #6454](https://github.com/SynoCommunity/spksrc/actions/runs/8396981472)
Error first seen in [build #6464](https://github.com/SynoCommunity/spksrc/actions/runs/8428082116)
The build is failing for ripgrep when building sys-prce2 with
```
error: failed to run custom build command for `pcre2-sys v0.2.9`
```
and the error is
```
pcre2-sys@0.2.9: upstream/src/pcre2_match.c:5448:32: error: ‘PCRE2_DISABLE_RECURSELOOP_CHECK’ undeclared (first use in this function); did you mean ‘PCRE2_ERROR_RECURSELOOP’?
```
Trying the following:
Probably it is an issue with rust 1.77.0 realeased on 2024.03.21.
The latests successful build of synocli-file by a …
=> synocli-file: try to fix build of ripgrep

spk/synocli-file/Makefile
This is a left over of #6052 where only the cross/zlib dependency ordering was addressed.
- the order is caused by conflicting dependencies of cross/mc and cross/rmlint
- when cross/libblkid is built first, the order of building mc and rmlint does not matter anymore
Fixes #
=> synocli-file: resolve the ugly dependency order

cross/sabnzbd/Makefile, cross/sabnzbd/digests, spk/sabnzbd/Makefile
Update SABnzbd to 4.2.3.
Simple update. If no remarks I'll merge and publish end of the week.
=> Update SABnzbd to 4.2.3

mk/spksrc.publish.mk
- make publish-arch-* must include make arch-* (broken by #6002)
Fixes #
=> fix make publish

Makefile, mk/spksrc.publish.mk
This is another attempt to fix the publishing of packages by github action (broken by #6002)
- ~make setup-synocommunity triggers "make setup" and this fails when mk/spksrc.test-rules.mk is included~ 
fixed in #6066
- add checks for empty PUBLISH_URL and PUBLISH_API_KEY in spksrc.publish.mk
- print PUBLISH_URL variable when publishing
=> spksrc.publish.mk: add checks for empty variables

mk/spksrc.common.mk
common.mk: Fix BASEDIR to manage github-action workspace directory.
When using github-action the `spksrc` repository sits under `/github/workspace`.  Therefore the `BASEDIR` value set in `spksrc.common.mk` is not taking this into account, making publishing to file as `make setup-synocommunity` had failed previously with the following:
```
2024-04-06T10:42:28.7394231Z ##[group] ---- initialize build
2024-04-06T10:42:29.5904113Z mk/spksrc.common.mk:59: ../../mk/spksrc.archs.mk: No such file or directory
2024-04-06T10:42:29.5905666Z make: *** No rule to make target '../../mk/spksrc.archs.mk'.  Stop.
2024-04-06T10:42:29.7350751Z sed: can't read local.mk: No such file or directory
2024-04-06T10:42:29.7510857Z ##[endgroup]
```
Above that error can be seen the actual path being used by …
=> common.mk: Fix BASEDIR to manage github-action workspace directory

mk/spksrc.archs.mk, mk/spksrc.common.mk
arch.mk: Fix BASEDIR to manage github-action workspace directory
Fixes: https://github.com/SynoCommunity/spksrc/pull/6061
Follow-up to: https://github.com/SynoCommunity/spksrc/pull/6066 and https://github.com/SynoCommunity/spksrc/pull/6064 (thnx @hgy59) and broken by https://github.com/SynoCommunity/spksrc/pull/6002
=> arch.mk: Fix BASEDIR to manage github-action workspace directory

README.md
Allow to run ghcr.io/synocommunity/spksrc from ARM machines:
```console
$ docker run -it -v $(pwd):/spksrc -w /spksrc -e TAR_CMD="fakeroot tar" ghcr.io/synocommunity/spksrc /bin/bash
Unable to find image 'ghcr.io/synocommunity/spksrc:latest' locally
latest: Pulling from synocommunity/spksrc
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
See 'docker run --help'.
```
Workaround without this fix is to specify arch with `--platform=linux/amd64`:
```shell
$ docker run --platform=linux/amd64  -it -v $(pwd):/spksrc -w /spksrc -e TAR_CMD="fakeroot tar" ghcr.io/synocommunity/spksrc /bin/bash
```
P.S.: I tried to add platform, but there is some broken package installation for i386.
=> doc: Enhance Docker platform specification in documentation

cross/sabnzbd/Makefile, cross/sabnzbd/digests, spk/sabnzbd/Makefile, spk/sabnzbd/src/requirements-crossenv.txt, spk/sabnzbd/src/requirements-pure.txt
=> Update SABnzbd to 4.3.2

cross/c-ares-1.28/Makefile, cross/c-ares-1.28/PLIST, cross/c-ares-1.28/digests, cross/c-ares-latest/Makefile, cross/c-ares-latest/PLIST, cross/c-ares-latest/digests, cross/c-ares/Makefile, cross/c-ares/digests
c-ares has removed source from former location
- update c-ares to v1.29.0
- limit c-ares to v1.28.1 for OLD_PPC_ARCHS
- c-ares sources are now available on github only
related to #6126 and #6127
=> c-ares: update and fix download link

cross/owncloud/Makefile, cross/owncloud/digests, spk/owncloud/Makefile, spk/owncloud/src/conf/resource, spk/owncloud/src/web/owncloud.json
1. Update ownCloud to version 10.14.0
2. Enable `iconv` php module
Fixes #
=> ownCloud: Update to v10.14.0

.github/workflows/build.yml, spk/synocli-monitor/Makefile
related to https://github.com/SynoCommunity/spksrc/pull/6123#issuecomment-2158070307
Disable the toolchain cache for qoriq to force the build of custom qoriq rust.
This PR updates the toolchain cache keys to include the related digests file only.
=> fix qoriq rust with github build

cross/transmission/Makefile, cross/transmission/digests, spk/transmission/Makefile
This pull request includes the following:
1. Update to Transmission v4.0.6 (bugfix-only release)
2. Include patched source for missing linked submodules
Fixes #6146
=> Transmission: Update to 4.0.6

cross/freetype/Makefile, cross/llvm-latest/Makefile, mk/spksrc.cross-cmake.mk, mk/spksrc.kernel.mk
Misc fixes:
1. freetype URL change
2. missing `CMAKE` argument at configure (needed for `llvm`)
3. `llvm` fix due to missing `-D` for ffi configure call
4. remove duplicate `digests` call in `kernel.mk`
Fixes #
=> Misc fixes

cross/node-exporter/Makefile, cross/node-exporter/digests, spk/node-exporter/Makefile
Update node-exporter to latest current version (1.8.1). I successfully installed it on DS418 running DSM 7.2.1.
=> Update node exporter to 1.8.1

cross/filebrowser/Makefile, cross/filebrowser/digests, spk/filebrowser/Makefile
=> filebrowser: update to v2.30.0

mk/spksrc.service.installer.functions
- this is a leftover of shared folder redesign (#5649)
- DSM 7 does not allow to call synohare (Permission denied)
Fixes #
=> fix initialization of SHARE_PATH variable on DSM 7

cross/jellyfin-web/Makefile, cross/jellyfin-web/digests, cross/jellyfin/Makefile, cross/jellyfin/digests, spk/jellyfin/Makefile
update jellyfin to 10.9.7 version
update jellyfin to 10.9.7 version
=> update jellyfin 10.9.7

Dockerfile, README.md, cross/ffmpeg4/Makefile, cross/ffmpeg5/Makefile, cross/ffmpeg6/Makefile, mk/spksrc.cross-cmake-env.mk
Update default spksrc image to Debian12
Fixes #
=> Update default spksrc image to Debian12

cross/fd/Makefile, cross/fd_8.7.0/Makefile, cross/python310/Makefile, cross/python311/Makefile, cross/xz/Makefile, cross/xz/PLIST, cross/xz/digests, cross/xz/patches/001-liblzma_fix_movzw_compatibility.patch, mk/spksrc.cross-rust-env.mk
1. `xz`: Update from version 5.6.1+really5.4.5 to 5.6.2
2. Fix python 3.10-3.11 builds.
3. Fix build issue for hi3535 related to fd-8.7.0 with newer rustc >= 1.80.1 (now version fixed to 1.77.2 like ARMv5)
Superseeds part of https://github.com/SynoCommunity/spksrc/pull/6200
=> xz: Update from version 5.6.1+really5.4.5 to 5.6.2

mk/spksrc.cross-cmake.mk, mk/spksrc.cross-ninja.mk, mk/spksrc.native-cmake-env.mk, mk/spksrc.native-cmake.mk, native/llvm-14.0-build/Makefile, native/llvm-14.0-build/digests, native/llvm-14.0/Makefile, native/llvm-14.0/digests, native/llvm-9.0-build/Makefile, native/llvm-9.0-build/patches/001-fix-missing-header-limits.patch
1. Noticed issues with native cmake building
2. Adding native llvm 14 - This is to be used as pre-compiled released on spksrc for fastening the IGC build from https://github.com/SynoCommunity/spksrc/pull/6166
=> native cmake fixes + add native llvm 14

cross/glib-2.66/patches/001-fix_asm_older_compiler.patch
glib-2.66: add 001-fix_asm_older_compiler.patch
Fixes needed for PR #6166
=> glib-2.66: add 001-fix_asm_older_compiler.patch

cross/git/Makefile, cross/git/digests, spk/git/Makefile
Changelog: https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.46.1.txt
=> Update git to 2.46.1

mk/spksrc.native-cmake.mk
native-cmake.mk: Fix build whereas install wouldn't be probed - When fixing `native/libmysql` to work with new debian image using legacy cmake, it was also converted to using ninja by default like cross-cmake.  An re-ordering of the rule files was missing for it to work.
Fixes https://github.com/SynoCommunity/spksrc/pull/6220#issuecomment-2353544515
=> native-cmake.mk: Fix build whereas install wouldn't be probed

spk/ffmpeg5/Makefile, spk/ffmpeg6/Makefile
ffmpeg56: Only make x64 dependent to synocli-videodriver
=> ffmpeg56: Only make x64 dependent to synocli-videodriver

.github/workflows/build.yml
github-action: Revert x64,aarch64-7.2 in favor or #6247
=> github-action: Revert x64,aarch64-7.2 in favor or #6247

.github/workflows/build.yml
This PR introduces several updates to the build workflow, including:
- Added new input flags to optionally include specific architectures for SRM 1.2, DSM 5.2, DSM 6.2, DSM 7.1, and DSM 7.2 (required for Jellyfin).
- Introduced logic to generate a dynamic matrix of architectures based on user input (noarch architectures included by default).
- Made adjustments to conditionally include older DSM architectures, improving build flexibility and reducing unnecessary builds.
These changes optimise the build process, allowing more control over which architectures are built and improving workflow performance by excluding unused architectures.
Related to #6101
=> Framework: Add Configurable Build Architectures and Input Flags

mk/spksrc.ffmpeg.mk
- fix for build of ffmpeg dependent packages when ffmpeg is not prebuilt
=> fix ffmpeg build dependency

cross/intel-compute-runtime/Makefile
intel-compute-runtime: Fix to use OCL_ICD_VENDORDIR cmake variable
Fixes https://github.com/intel/compute-runtime/issues/758
=> intel-compute-runtime: Fix to use OCL_ICD_VENDORDIR cmake variable

native/dotnet-sdk-8.0/Makefile, native/dotnet-sdk-8.0/digests, spk/jellyfin/Makefile
This is a follow-on from #6201 to include the current version of .NET v8.0.8.
Fixes #
=> Jellyfin: Update v10.9.11 to include .NET v8.0.8

.github/actions/prepare.sh
- do not evaluate dependencies for broken packages
This is a small optimization to avoid the download of packages that will not be built.
This will be fixed by #6255, but since some more packages are declared broken, it will safe some cpu cycles until #6255 is merged.
=> github action: omit broken packages in dependency-list

spk/wallabag/Makefile, spk/wallabag/src/conf/resource, spk/wallabag/src/service-setup.sh, spk/wallabag/src/web/wallabag.json
This follow-up to #6232 addresses missing PHP extensions in the default installation and refines certain PHP settings. Special thanks to @j4w0r for their help in identifying the missing extensions not included in the [documentation](https://doc.wallabag.org/en/admin/installation/requirements).
Fixes #
=> Wallabag: Update PHP extensions

cross/intel-opencl-clang-140/Makefile, cross/intel-vc-intrinsics.src/Makefile, cross/intel-vc-intrinsics.src/digests, cross/intel-vc-intrinsics/Makefile, cross/intel-vc-intrinsics/digests
vc-intrinsics: Update to v0.20.1 and remove unecessary `USE_NATIVE_CMAKE` since docker image update to Debian 12.
Refers to https://github.com/SynoCommunity/spksrc/pull/6255
=> vc-intrinsics: Update to v0.20.1 and remove unused USE_NATIVE_CMAKE

cross/owncloud/Makefile, cross/owncloud/digests, spk/owncloud/Makefile, spk/owncloud/src/conf/resource, spk/owncloud/src/service-setup.sh, spk/owncloud/src/web/owncloud.json, spk/owncloud/src/wizard_templates/install_uifile.sh, spk/owncloud/src/wizard_templates/install_uifile.yml, spk/owncloud/src/wizard_templates/install_uifile_fre.yml, spk/owncloud/src/wizard_templates/uninstall_uifile.sh, spk/owncloud/src/wizard_templates/uninstall_uifile.yml, spk/owncloud/src/wizard_templates/uninstall_uifile_fre.yml, spk/owncloud/src/wizard_templates/upgrade_uifile.sh, spk/owncloud/src/wizard_templates/upgrade_uifile.yml, spk/owncloud/src/wizard_templates/upgrade_uifile_fre.yml
1. Update ownCloud to version 10.15.0
2. Use recommended MariaDB database ([migration guide](https://github.com/SynoCommunity/spksrc/wiki/ownCloud-Database-Migration))
3. Optimise initial ownCloud setup
4. Refine scripts for backup restoration
5. Fix scripts for uninstall validation
Fixes #
=> ownCloud: Update to v10.15.0

cross/mympd/Makefile, mk/spksrc.cross-meson.mk, mk/spksrc.native-meson.mk
In #6274 the build of mympd fails and some research was needed to find the problem ⛑️ 
- build mympd with CMake (disable ninja)
- mympd build was broken since CMAKE_USE_NINJA default value changed from 0 to 1 in #6002
=> mympd: fix build

cross/readline/Makefile
readline: Fix readline.pc to depend on ncursesw
Fixes issue when compiling python 3.13.0 - relates to https://github.com/SynoCommunity/spksrc/pull/6282
=> readline: Fix readline.pc to depend on ncursesw

spk/homeassistant/src/requirements-crossenv.txt
- update numpy to v1.24.4 to fix build with python311
=> homeassistant: adjust numpy to fix build

cross/readline/Makefile, cross/readline/digests
- update cross/readline from v8.2 to v8.2.13
- configure to use shared ncursesw library
- adjust patch of readline.pc introduced with #6283
This fixes the build of cross/bind for synocli-net that popped up in #6220 after #6283 was merged.
Fixes #
=> cross/readline: update and fix

cross/python310/Makefile, diyspk/pngquant/Makefile, mk/spksrc.cross-rust-env.mk, mk/spksrc.tc-rust.mk, spk/python310/Makefile, spk/python310/src/requirements-crossenv-numpy.txt, spk/python310/src/requirements-pure.txt, toolchain/syno-qoriq-6.2.4-rust/Makefile, toolchain/syno-qoriq-6.2.4-rust/digests
rust-qoriq: Update generation and use of 1.82.0 rust toolchain
Fixes https://github.com/SynoCommunity/spksrc/issues/6297
Versions available: https://releases.rs/docs/
=> rust-qoriq: Update to 1.82.0 rust toolchain

toolchain/syno-alpine-7.0/Makefile, toolchain/syno-alpine-7.1/Makefile, toolchain/syno-alpine4k-7.0/Makefile, toolchain/syno-alpine4k-7.1/Makefile
- fix definition of TC_GLIBC of alpine and alpine4k toolchain
this popped up in the analysis of #6309
Since we prefere the generic archs (ARMv7 in this case) this is not an issue so far.
=> toolchains: fix TC_GLIBC

cross/attr/patches/001-attributes_h-for-old-gcc.patch
- add patch to build cross/attr for OLD_PPC_ARCHS
Extracted from #6288 to limit the number of triggered packages to build.
This is a leftover of #5032
- current cross/tree of synocli-file fails (source archive is gone) updated in #6288
=> cross/attr: fix for older gcc

Makefile, mk/spksrc.spk.mk
- spksrc.spk.mk uses the github api to get the realname and the url of the package maintainer
- if you build packages too often (e.g. small diyspk packages) you can reach the api rate limit and the build fails
- for this case you can define DISABLE_GITHUB_MAINTAINER with any non empty value (1, true, ...) to avoid the api call
- if DISABLE_GITHUB_MAINTAINER is defined the MAINTAINER is used as defined and the MAINTERNER_URL is set to "https://github.com/SynoCommunity" if not defined in the package
=> local.mk: add option to disable github api call for maintainer

cross/bzip2/Makefile, cross/bzip2/src/bzip2.pc
bzip2: Add bzip2.pc pkgconfig file as missing by default
=> bzip2: Add bzip2.pc pkgconfig file

cross/icecast/Makefile, spk/icecast/BROKEN
- fix build of cross/icecast, broken by update of cross/libxml2 in #6329
=> icecast: fix build

cross/diesel/Makefile, cross/diesel/digests, cross/syncstorage-rs/Makefile, cross/syncstorage-rs/digests, spk/ffsync/Makefile
1. Update syncstorage-rs to v0.17.15
Fixes #
=> ffsync: Update syncstorage-rs to v0.17.15

cross/libpng/Makefile, cross/libpng/PLIST, cross/libpng/digests
taken from #6357 to reduce dependent packages
Fixes #
=> cross/libpng: update from v1.6.43 to v1.6.44

.github/workflows/build.yml
This PR introduces a conditional check to skip the build action when no dependent packages are identified, optimizing workflow efficiency and avoiding unnecessary builds.
Relates to #6366
=> Framework: Fix to handle empty matrix

cross/boost/Makefile, cross/boost_1.68/Makefile, cross/boost_1.70/Makefile, cross/boost_1.78/Makefile, cross/boost_1.82/Makefile
former (jfrog) source repository is not available anymore
=> update boost libraries sources

cross/navidrome/Makefile, cross/navidrome/digests, spk/navidrome/Makefile
=> navidrome: update to v0.54.3

cross/fengoffice/Makefile, cross/fengoffice/digests, spk/fengoffice/Makefile
1. Update Feng Office to version 3.11.4.14
Fixes #
=> Feng Office: Update to v3.11.4.14

cross/wallabag/Makefile, cross/wallabag/digests, spk/wallabag/Makefile
1. Update Wallabag to version 2.6.10
Fixes #
=> Wallabag: Update to v2.6.10

cross/memcached/Makefile, cross/memcached/digests, spk/memcached/Makefile
1. Update Memcached to version 1.6.34
2. Fix Apache 2.4 dependency (follow-on from #6005)
Fixes #
=> Memcached: Update to v1.6.34

cross/znc/Makefile, spk/chromaprint/Makefile, spk/comskip/Makefile, spk/ffmpeg5/Makefile, spk/ffmpeg6/Makefile, spk/ffmpeg7/Makefile, spk/znc/Makefile
some changes taken from PR #6255 to reduce number of dependent packages:
- changes that trigger ffmpeg*
- changes that trigger python311 (except vim, separated in PR #6398)
Fixes #
=> prepare redesign of dependency list

cross/gpac/Makefile, cross/gpac/PLIST, cross/gpac/patches/001-configure.patch, spk/gpac/Makefile
- follow up to #6004
- PLIST must contain own files only
- update revision.h patching
- remove variable in DEPENDS for #6255
Fixes #
=> gpac: fix build

cross/cloudflared/Makefile, cross/cloudflared/digests, spk/cloudflared/Makefile
⚠️ This is the 2nd try for this PR, [first one](https://github.com/SynoCommunity/spksrc/pull/6390) was closed because I wrongly submitted it against the `master` branch. Oops.
Updates cloudflared package to 2025.1.0 version
I only tested the `arch-v1000-7.2` toolchain build because that's what I have (DS1621). I don't think there is any issue for other architectures. But others can test & confirm.
=> update cloudflared to 2025.1.0 (2nd try)

cross/syncstorage-rs/Makefile, cross/syncstorage-rs/digests, spk/ffsync/Makefile
1. Update syncstorage-rs to v0.18.2
Fixes #
=> ffsync: Update syncstorage-rs to v0.18.2

mk/spksrc.publish.mk
related to https://github.com/SynoCommunity/spksrc/pull/6406#issuecomment-2613837511
This is a hotfix since publish python311 and related packages is broken
- avoid PYTHONPATH definition for http tool
- PYTHONPATH is defined spksrc.crossenv.mk and was introduced with #6282
Fixes #
=> fix publish

cross/bzip2/Makefile, cross/freetype/Makefile, mk/spksrc.python.mk
python313 hi3535 arch freetype fix - error in bzip2.pc pkgconfig file creation and freetype build error due to missing dependency.
Relates to https://github.com/SynoCommunity/spksrc/pull/6409
=> python313 hi3535 arch freetype fix

cross/ezstream/Makefile, cross/icecast/Makefile, cross/libshout/Makefile, cross/libtheora/Makefile, cross/speex/Makefile, spk/icecast/Makefile
- update openssl to v3
- update curl to v8.4
- optimize some libraries
=> icecast: update openssl

spk/flexget/Makefile, spk/flexget/src/requirements-crossenv-greenlet-v1.txt, spk/flexget/src/requirements-crossenv-greenlet-v3-gcc4.txt, spk/flexget/src/requirements-crossenv-greenlet-v3.txt, spk/flexget/src/requirements-crossenv.txt, spk/flexget/src/requirements-pure.txt
1. Update FlexGet to version 3.13.16
Fixes #6395
=> FlexGet: Update to v3.13.16

cross/berkeleydb/Makefile, cross/ntopng/Makefile, mk/dependency-list.sh
follow up to #6255
not all dependencies were found.
also the former implementation with make dependecy-list did not find all dependencies
`cross/berkeley` is such a dependency that was lacking in the dependency list (it was lacking in the pre #6255 version too).
Fixes #
=> Fix dependency list

mk/spksrc.python.mk, mk/spksrc.spk.mk, mk/spksrc.wheel.mk
Add wheel top-level status cookie and mark armv5 as unsupported >= python 3.12
Relates to comments:
- Mark armv5 as unsupported: https://github.com/SynoCommunity/spksrc/pull/6422#issuecomment-2614601077
- Add top-level wheel status cookie https://github.com/SynoCommunity/spksrc/pull/6409#issuecomment-2614492794
=> Add wheel top-level status cookie and mark armv5 as unsupported >= python 3.12

cross/dtv-scan-tables/Makefile, cross/dtv-scan-tables/PLIST, cross/dtv-scan-tables/digests, cross/libsodium/Makefile, cross/libsodium/PLIST, cross/libsodium/digests
This PR includes the following changes:
1. Update to libsodium v1.0.20
Fixes #
=> cross/libsodium: update to v1.0.20

mk/spksrc.wheel.mk
wheel.mk: Avoid processing when WHEELS variable is empty
Fixes :
- https://github.com/SynoCommunity/spksrc/pull/6456#issuecomment-2663677717
- https://github.com/SynoCommunity/spksrc/pull/6437#issuecomment-2663022414
=> wheel.mk: Avoid processing when WHEELS variable is empty

cross/jellyfin/Makefile, spk/jellyfin/Makefile, spk/jellyfin/src/fonts/fonts.conf, spk/jellyfin/src/service-setup.sh
1. Add a default font for library thumbnails
2. Add custom Fontconfig directory and configuration file
3. Updates the service setup script with custom environment variables
Republish of #6459
Fixes #
=> Jellyfin: Republish with font fix

cross/ripgrep/Makefile, mk/spksrc.cross-rust-env.mk, toolchain/syno-qoriq-6.2.4-rust/Makefile, toolchain/syno-qoriq-6.2.4-rust/digests, toolchain/syno-qoriq-6.2.4/Makefile
This resolves recent build failures in #6454 and #6471 when building `qoriq-6.2.4` packages, which reported an "invalid custom toolchain name" after a recent Rust update. The fix applies a custom toolchain channel prefix aligned with the [documented standard](https://rust-lang.github.io/rustup/overrides.html#toolchain-file-settings) for toolchain files.
Follow-on from #5879.
Fixes #
=> Ensure valid custom toolchain name for qoriq-6.2.4 (powerpc-unknown-linux-gnuspe)

mk/spksrc.service.installer.dsm7
- do not print deleted files to installer log when removing all files on uninstall
The generic uninstall function on dsm7 supports the removal of all installed data.
When removing all files, every file is logged to the installer log of the packag.
This floods the installer log with (IMHO) unimportant information.
When a python package is uninstalled with this option, all files in the pip cache (in the var folder) are printed to the installer log For Home Assistant with a lot of wheels and package data there are > 60'000 lines printed and the log file gets immediatly rotated.
=> make dsm7 uninstall less verbose

cross/kiwix-tools/Makefile, cross/libmicrohttpd/Makefile, cross/libmicrohttpd/PLIST, cross/libmicrohttpd/digests, cross/libxapian/Makefile, cross/libxapian/PLIST, cross/libxapian/digests, cross/libzim/Makefile, cross/libzim/PLIST, cross/libzim/digests, spk/kiwix/Makefile, spk/kiwix/src/service-setup.sh
- add parameter --monitorLibrary to auto reload libraries (#6242)
- update libzim from v9.1.0 to v9.2.3
- update libxapian from v1.4.25 to v1.4.27
- update libmicrohttpd from v0.9.75 to v1.0.1
Fixes #6242
=> kiwix: Support library auto reload

cross/sabnzbd/patches/002-fix-virtualization-detection.patch, spk/sabnzbd/Makefile
This is a follow-on from #6501 to address failed platform detection error:
```
failed to execute systemd-detect-virt: No such file or directory
```
Fixes #
=> SABnzbd: Revision for 4.5.0

spk/mercurial/Makefile, spk/mercurial/src/requirements-crossenv.txt, spk/mercurial/src/requirements-pure.txt, spk/mercurial/src/service-setup.sh
mercurial: Update hg from 6.5 to version 7.0 and python 3.12
Fixes n/a
=> mercurial: Update hg from 6.5 to version 6.9.1 and python 3.12

cross/chromaprint/Makefile
This PR updates the GitHub download URLs in affected cross package Makefiles to conform to the new recommended formats. Legacy URLs that relied on the `/archive` endpoint have been revised so that the full download URL is constructed from an updated base URL (either using the releases/download or tag archive format).
An external script (provided separately) was used to perform the automated update. Only packages with GitHub-based PKG_DIST_SITE entries were processed; packages with non‑GitHub URLs were left unchanged. In this update, one package required modifications while all others already use working URLs.
All changes were verified via checksum comparison as part of the automated update process.
Fixes #6521
=> Update GitHub Download URLs in Cross Package Makefiles

spk/borgbackup/Makefile, spk/borgbackup/src/requirements-crossenv.txt, spk/borgbackup/src/requirements-pure.txt, spk/borgbackup/src/service-setup.sh
1. Update borg to 1.4.1
2. Update borgmatic to 2.0.3
3. Migrate to Python 3.12
Fixes #
=> Borg: Update to v1.4.1 and migrate to Python 3.12

spk/synocli-disk/Makefile
- followup to #6509
- exclude mergerfs for all DSM 5.2
Fixes #
=> synocli-disk: fix for x86-5.2

cross/syncstorage-rs/Makefile, cross/syncstorage-rs/digests, cross/syncstorage-rs/patches/001-update-ring.patch, spk/ffsync/Makefile, spk/ffsync/src/requirements-crossenv-greenlet-v1.txt, spk/ffsync/src/requirements-crossenv.txt, spk/ffsync/src/requirements-pure.txt, spk/ffsync/src/service-setup.sh
1. Update syncstorage-rs to v0.18.3
2. Migrate to Python 3.12
3. Update MariaDB references
Fixes #
=> ffsync: Update to v0.18.3 and migrate to Python 3.12

mk/spksrc.archs.mk, toolchain/syno-x64-7.1/Makefile, toolchain/syno-x64-7.2/Makefile
follow up to #6574 
- add arch r1000nk for DS725+
- add arch geminilakenk for DS425+ (and maybe for DS225+, DS625slim)
- still no toolchains and kernel sources available for x25 models
=> add more x25 models

.github/actions/download.sh, mk/spksrc.download.mk, mk/spksrc.main-depends.mk
This change refactors the existing `download.sh` script to run in strict mode (`set -euo pipefail`), adds a global `ERR` trap for clear error and line reporting, and verifies that `make` is installed before proceeding. It preserves the two loops that handle cross-package (`download-all`) and Python-wheel (`download-wheels`) downloads — now iterating with clearer variable names and inlined progress echoes — while appending a `checksum` invocation to the cross-package download step. Finally, it combines `NOARCH_PACKAGES` and `ARCH_PACKAGES` into a Bash array for reliable empty checks and prints a succinct “All downloads completed successfully.” message, ensuring full parity with the old behavior but with much stronger error visibility and integrity verification.
Fixes #
=> Build Script: Add strict mode, error trapping, and checksum verification

cross/libsodium/Makefile
- libsodium.org is down atm.
Related to #6603
=> cross/libsodium: use github to download source

cross/cloudflared/Makefile, cross/cloudflared/digests, spk/cloudflared/Makefile
1. Update to 2025.6.1
2. Switch back to regular go since https://github.com/cloudflare/cloudflared/commit/96ce66bd302872c41605f167775f7abe0681cb95 removed the requirement for cloudflare-go in favor of go >= 1.24
2025.6.1
- 2025-06-16 TUN-9467: add vulncheck to cloudflared
- 2025-06-16 TUN-9495: Remove references to cloudflare-go
- 2025-06-16 TUN-9371: Add logging format as JSON
- 2025-06-12 TUN-9467: bump coredns to solve CVE
- 
2025.6.0
- 2025-06-06 TUN-9016: update go to 1.24
- 2025-06-05 TUN-9171: Use `is_default_network` instead of `is_default` to create vnet's
2025.5.0
- 2025-05-14 TUN-9319: Add dynamic loading of features to connections via ConnectionOptionsSnapshot
- 2025-05-13 TUN-9322: Add metric for unsupported RPC commands for datagram v3
- 2025-05-07 TUN-9291: Remove dynamic …
=> cloudflared: update to 2025.6.1

cross/memcached/patches/ppc853x/000-remove-use-of_pthread_setname_np.patch, cross/memcached/patches/ppc853x/001-ajdust-typedefs-for-older-gcc.patch
- adjust existing patch
- add patch to fix typedef for older gcc
Fixes #6492
=> fix memcached for OLD_PPC_ARCHS

mk/spksrc.cross-cc.mk, mk/spksrc.cross-cmake.mk, mk/spksrc.cross-dotnet.mk, mk/spksrc.cross-go.mk, mk/spksrc.cross-rust.mk, mk/spksrc.directories.mk, mk/spksrc.install-resources.mk, mk/spksrc.main-depends.mk, mk/spksrc.spk.mk
Since a while when invoking a build it hapens that all dependencies ends-up also with a `work-<arch>-<version>/tc_vars.cmake|meson*|mk`. Expected behavior is for the location to be unique under the current directory from where the build was invoked.
Fixes #
=> Fix WORK_DIR for toolchain configuration file location

cross/openssl3/Makefile, cross/openssl3/digests
openssl3: Update from version 3.5.0 to 3.5.1
Fixes n/a
=> openssl3: Update from version 3.5.0 to 3.5.1

cross/libgcrypt/patches/002-avoid-duplicate-declartions.patch
- add patch to fix build of libgcrypt with old gcc
- follow up to #6644 to fix build for ppc853x-5.2
Fixes #
=> cross/libgcrypt: fix build with old gcc

cross/git/Makefile, cross/git/patches/001-avoid-use-of-getrandom.patch, spk/git/Makefile
Avoid use of getrandom to fix git on DSM 7 too.
As reported in #6666, on DSM 7 getrandom is not available at runtime (despite it is defined in the toolchain).
Fixes #6666
=> Fix git for DSM 7

cross/bottom/patches/88f6281/001-pin_dependencies_for_rust_1.77.patch, cross/dua_2.30.0/patches/88f6281/001-pin_dependencies_for_rust_1.77.patch
- update patches for armv5 tools built with rust 1.77
pin dependencies for rust 1.77
recently updated dependencies are `rayon` and `rayon-core`
Other fixes for synocli-file tools are WIP in #6668
Fixes #
=> armv5 rust fixes

cross/libpng/Makefile, cross/libpng/PLIST, cross/libpng/digests, cross/libtiff/Makefile, cross/libtiff/PLIST, cross/libtiff/digests
- update cross/libpng from v1.6.44 to v1.6.50
- update cross/libtiff from v4.6.0 to v4.7.0
Libraries with common dependencies.
Separated from next update of imagemagick.
Fixes #
=> Update libraries: libpng, libtiff
